### ISSUE TITLE
[Interface] Hide artist icons and add more info

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#100]
iPhone SE 2016 iOS 15.3, Amperfy 1.0.8 (4)

I would like to propose removing the artist icons in all artist views, or at least having it as a selectable option.

Maybe even add some more info like number of tracks (better name than songs) and total play time?

<img width="320" alt="IMG_46945B6C468C-1" src="https://user-images.githubusercontent.com/47334163/152687489-8e2e639f-0aef-4f07-b271-daca2c1a1f24.png">

The icons take up a lot of valuable screen real estate for no good reason.

![IMG_FD16F96197F8-1](https://user-images.githubusercontent.com/47334163/152686483-492ccc90-de1d-4841-b4ef-249b03d6dc96.jpeg)

![IMG_46945B6C468C-1](https://user-images.githubusercontent.com/47334163/152686556-75bceb97-1583-474b-9d1e-1ce5d5eea26a.jpeg)

**Comment by bbsixzz** [comment]
Even better, move the tree dots to the top nav bar.

![FED281E7-D849-4490-8024-C1A36975CB09](https://user-images.githubusercontent.com/47334163/152690249-9f421dba-5427-46c7-b07f-050c005920cf.jpeg)

**Comment by BLeeEZ** [comment]
Thanks for the input. I will take a look at design when I have time. The additional information is already implemented in a private feature branch.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
