### ISSUE TITLE
[Question]: Dealing with login screen when developing

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#101]
So I finally got my macOS on Linux setup working :)
![image](https://user-images.githubusercontent.com/21057514/153233618-f0769df9-f580-4e42-a761-62ab33ed848d.png)

I was wondering how you deal with the login screen when testing the app, I guess you would automate it somehow so you didn't have to log-in every time you launch the app. Currently I can't seem to login in any case using the latest Ampache Develop and Amperfy, do you know if this is because of using Amperfy in the simulator or possibly because I'm using macOS from a VM? 

I tried to login using https, the ampache api and a login token.

**Comment by BLeeEZ** [comment]
The simulator has persistent memory. You only have to login once.
I have no experience with macOS in a VM. Do you reach your Ampache server from within your VM (via safari or chrome)?
The login via simulator should be exactly the same as from your real device.

**Comment by sandersantema** [comment]
Ah that's very nice. Internet connection is working perfectly fine so I guess it might have something to do with the latest Ampache development version, given that it's working fine on my iPhone where I'm already logged in and I had some trouble logging in on another app as well but that's just a guess.

This is the error reported when logging in: 
```
2022-02-10 17:27:35.138581+0100 Amperfy[1385:29281] [boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics
2022-02-10 17:27:35.280610+0100 Amperfy[1385:29281] [boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics
2022-02-10 17:27:35.325723+0100 Amperfy[1385:26814] [BackendProxy] Server url is reachable. Status code: 200
2022-02-10 17:27:35.397304+0100 Amperfy[1385:29281] [boringssl] boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics
2022-02-10 17:27:35.430454+0100 Amperfy[1385:23735] [Ampache] Couldn't get a login token.
```

I tried with both the api-key and with a password, http and https (although my server is https). Could you possibly try logging in again? That way we might be able to determine whether it's a problem with my setup. If possible it would also nice to test it out using the latest Ampache Development version if possible. If that works for you I think we can be fairly certain it's an error on my side.

**Comment by BLeeEZ** [comment]
Looking through your posted log, the connection itself seems fine. The server is reachable and a xml answer is returned. It seems like a problem with your credentials.
You can send me credentials (amperfy@familie-zimba.de) and I can try to login to your server, but it seems very much like an server/credentials issues.
