### ISSUE TITLE
[Feature request] Sort podcasts by date

### ISSUE THREAD

**Issue by MarkWieczorek** [BLeeEZ/amperfy#104]
Podcasts are currently organized by folders, which makes it very difficult to determine when new podcasts are available. It would be great if you could have the option to sort the podcasts by at least "show" and "date". Other useful sort options might be "played", "unplayed", "saved", and "downloaded".

**Comment by BLeeEZ** [comment]
Sounds good. This should be quite easy to implement.
I think I will add the sort options "Podcast" and "Recent".
Podcast: show the same hierarchy as it is now.
Recent: show all podcast episodes sorted by date.

**Comment by BLeeEZ** [comment]
I have added this filter for podcast grouped and episodes sorted by release date.
