### ISSUE TITLE
[Feature request] Create and manage playlists

### ISSUE THREAD

**Issue by MarkWieczorek** [BLeeEZ/amperfy#105]
At the present time, playlists are simply read from the server. However, it would be very useful if you could create playlists in Amperfy, and also add items to the playlist (such as by swiping or the context menu).

**Comment by BLeeEZ** [comment]
This is already available.
Via long press on songs you are able to add the song to a playlist or create a new playlist and it to that.
Artists/Albums also have this functionality via a press on the blue (...)-button -> "Add to playlist".
You can also add all songs from the player queue to a playlist: Player -> (...)-button (upper right corner) -> "Add all songs to playlist".

**Comment by BLeeEZ** [comment]
In the next version v1.1.0 it is also possible to add songs to playlist via swipe.

**Comment by MarkWieczorek** [comment]
Thanks for the quick response. I now see that this is indeed available for music, but it doesn't look like it has been implemented for podcasts (which is my reason for opening this issue).

**Comment by BLeeEZ** [comment]
Yes you are right. This functionality is not available for podcast episodes.
The "Add To Playlist" API function doesn't support podcast episodes at Ampache and Subsonic backend.

**Comment by BLeeEZ** [comment]
This should be resolved with feature request #102.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
