### ISSUE TITLE
[Feature request] Scrobble songs played when offline

### ISSUE THREAD

**Issue by el-tiuri** [BLeeEZ/amperfy#106]
It’d be great if songs played while offline were synced with the server when going back online. Play:sub does this, to give an example.

**Comment by BLeeEZ** [comment]
Sounds good. I add it to the feature list.

**Comment by BLeeEZ** [comment]
The feature is implemented in this commit 8cd927fa0d0009df63aca3d53314282a6314a8c4.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.

**Comment by bbsixzz** [comment]
I can't make this work with Amperfy 1.1.2 (3) and Navidrome v0.49.3

I play a cached track with offline mode off while connected to 4G.

After playing the track I connect to my home network using VPN and Amperfy doesn't scrobble the track that was previously played.

Rebooting the app doesn't push the "offline" scrobble either.

If I play a new track while connected to my home network with VPN scrobbling works.

I could connect to VPN at all times and have no problem but I just want clarification how this is supposed to work or if this is a bug.

**Comment by BLeeEZ** [comment]
When you are in offline mode or no network is reachable the song gets added to the database with upload required flag.
When you switch to online mode or the app gets restarted the flagged songs gets scrobbled from database. 
The check for network reachability is always used in the scrobble class. So if the songs gets scrobbled when you are in VPN and online mode, the offline scrobbled songs should work too.

**Comment by bbsixzz** [comment]
Ok thank you that's exactly what I thought, what I'm saying is it doesn't work for me.

I think I know what's going on. 

I did a test listening to a cached track while disconnected from wifi using only cellular.

After the track finished I connected to my home network with VPN over cellular and the scrobble came through!

However, if I have wifi on and am connected to a different network (not my home network) the same procedure doesn't work.

It seems like there is a specific wifi off flag requirement for this to work.

**Comment by el-tiuri** [comment]
I’m also having issues with this. Wouldn’t it make more sense to see if the server is available, rather than looking at network connectivity? After all, scrobbling is dependent on the server itself, which can be unavailable even if your phone is connected to the internet.

**Comment by el-tiuri** [comment]
In addition, upon testing some more again, it seems like all the scrobbles are timestamped for the moment the device goes online again, rather than the moment they were played. This seems like a bit of an oversight as well.

**Comment by el-tiuri** [comment]
I took a look at the code, hoping I could write a fix myself (at least for the time stamp issue). As far as I understand the date a song is played *is* cached, but that time stamp just isn’t used when pushing the play to the server (it explicitly uses date: nil). It seems like an easy fix, but it’s been a long while since I’ve coded. 

Would you accept a PR to fix this, @BLeeEZ? If so, I think I’ll invest the time in reading up a bit and trying to write a fix.

**Comment by BLeeEZ** [comment]
I am happy for every incoming PR.

**Comment by bbsixzz** [comment]
Hey @BLeeEZ beta has expired, is there a pause over the summer or just no more betas moving forward? 

Cheers

**Comment by BLeeEZ** [comment]
Hi, there is currently nothing to test. I will release a new beta when enough features are ready to test.
