### ISSUE TITLE
[Feature Request]: Having separate server urls for internal/external connection

### ISSUE THREAD

**Issue by kgarner7** [BLeeEZ/amperfy#107]
I saw this on another iOS app prior to switching to amperfy, but the feature was that you could have two different URLs for the same server: one that is "internal" (e.g. 192.168.1/24), and one that was "external" (e.g. https://music.example.com). Importantly, you could switch between the two urls (so if you were at home, you could benefit from being on the same network, while away, you could still have access).

I understand from #66 that changing the server url could be problematic, but was wondering if it would be possible to support this feature as the two urls should represent the same server.

**Comment by BLeeEZ** [comment]
I take a look at it if #66 is still a blocking issue for this feature.

**Comment by kgarner7** [comment]
Amazing! Thanks.
