### ISSUE TITLE
[BUG] Detail information about library elements via long press - overlapping button

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#109]
iPhone SE 2016 iOS 15.4.1, Amperfy 1.1.0 (1)

This is an excellent addition, however the `Cancel` button overlaps `Remove from Cache`.

Scrolling is not available but the card can still be dismissed with a down swipe.

![IMG_5680](https://user-images.githubusercontent.com/47334163/162550938-dec15757-4c83-487a-8942-6454cc14be2e.PNG)

**Comment by BLeeEZ** [comment]
Good to know. I haven't tested it with a partial downloaded album. This is why the "Download" and the "Remove from Cache" button are displayed at the same time. I will fix that.

**Comment by BLeeEZ** [comment]
This should be fixed with ff555a920de65301ac1c0e8bbce864659789b9b4.
The view is now embedded in a scroll view.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
