### ISSUE TITLE
Cydia Package

### ISSUE THREAD

**Issue by AshotN** [BLeeEZ/amperfy#11]
This might be a bit of an odd request. But since you don't seem to be hosting the App on the official App Store. Would you possibly consider hosting it for Jailbroken devices? Or perhaps just have an IPA file available for download.

Thanks for the client either way!

**Comment by BLeeEZ** [comment]
To create an IPA file export of Amperfy, an Apple developer subscription is needed. Basically the same reasons apply here like for the official App Store too. Currently I am not willing to do this yearly subscription. In principal I have no problem to release the app on Cydia. 
Thank you for your request.

**Comment by AshotN** [comment]
I believe there is a way to bypass the requirement for creating an IPA. I remember creating an app a long time ago for internal use and there was XCode patchers. 

A quick search brought this up. 
https://medium.com/m%CE%BBgn%CE%BEt%CE%BBr/how-to-export-a-ipa-file-from-xcode-without-a-dev-account-bac8b2645ad3

I’d try it myself, but my old Mac Mini is out of date and slow as hell. So it would take me a while to get setup.

**Comment by BLeeEZ** [comment]
Yes you are right. I followed this guide: https://stackoverflow.com/questions/35403969/how-to-create-ipa-without-apple-developer-program-in-xcode7

I released [v0.3.1](https://github.com/BLeeEZ/amperfy/releases/tag/v0.3.1)
I provide from now on the Amperfy.ipa in the releases.

Please note that v0.3.1 is validated against https://github.com/ampache/ampache/commit/910db0d6faf76d4c7dd9d71d6166c369b5d20305
Last time I checked Ampache v4.1.0 there were some problems, but I had no time for investigation.

**Comment by AshotN** [comment]
Well whatever issue you are having with Ampache 4.1.0, I'm one of the devs so maybe we can fix it!

I'll install your client on my phone and see how it goes!

Thanks.

**Comment by BLeeEZ** [comment]
Thank you for your offered help. After the merge of my pull request https://github.com/ampache/ampache/pull/2287 yesterday, the issue is solved. Amperfy v0.3.1 is now working correct with head of Ampache develop branch (https://github.com/ampache/ampache/commit/7f5d32785f3a0a212df755f97dd5ef432fa6493d).

I would appreciate to hear from you any kind of remarks, user experience, issues or feature requests.

**Comment by AshotN** [comment]
Would you be up for the Ampache organization to host a Cydia repo for your app. I use it personally, and I think if we got it hosted even for Jailbroken devices it could give the app some good exposure and make it a little easier to install.

**Comment by BLeeEZ** [comment]
You are right, with the presence in at least one app store the visibility should rise.
Do you mean to host an own repository or to submit the app on an already known repository (e.g. BigBoss, ModMyi, ...)?
Currently i don't own a jailbroken device. With this limitation it is difficult for me to verify that the latest Amperfy build runs in the jailbroken environment.

**Comment by BLeeEZ** [comment]
Amperfy is now officially available on the Apple App Store: [Amperfy Music](https://apps.apple.com/app/amperfy-music/id1530145038#?platform=iphone).
I will close this issues for now due to the lack of a jailbroken device and the availablity in the official App Store.

**Comment by AshotN** [comment]
Fair enough, it's on the App store no gain in putting it on Cydia.
