### ISSUE TITLE
[Interface] Mini player text alignment not centered

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#111]
iPhone SE 2016 iOS 15.4.1, Amperfy 1.1.0 (1)

Text alignment is not centered which looks ungainly.

![IMG_5699](https://user-images.githubusercontent.com/47334163/162647325-9fbc2f42-bcb5-4bf6-88d0-59bb66980b7c.PNG)

![IMG_5687](https://user-images.githubusercontent.com/47334163/162647370-9bdceecc-e4c5-4e7c-a96c-22d5c417fa8a.PNG)

**Comment by BLeeEZ** [comment]
Thank you for these detail reports, they help me a lot.
I fixed the alignment with 918a3832820236b612e6a6c1fa7a09844fe3c88b.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
