### ISSUE TITLE
[Feature request] Ability to download entire music library at once

### ISSUE THREAD

**Issue by el-tiuri** [BLeeEZ/amperfy#113]
It’d be useful to have the option to download your entire music library in one go, without having to download each individual album or artist - especially for devices without mobile internet (like quite some tablets).

Some extra ideas:
- Selecting the transcoding options would be good, specifically because file size really matters when talking about entire libraries
- Fetching all album art as well would be fantastic
- The ability to download the entire library *except for* certain artists, albums or songs would also be useful
- Making sure new music added to the library is downloaded to the device (without manually triggering the download option) would also be great.

Small side note: for anyone wanting to achieve this in the meantime, it’s possible to make a playlist of your entire library and download that - but I still feel like this would be useful as a separate feature.

**Comment by BLeeEZ** [comment]
Sounds good, I add it to the backlog.

**Comment by BLeeEZ** [comment]
Songs are getting synced in background with this commit b21ffb925d6794639395415772b593375d4a4ffa.
The background sync syncs all meta data in background. The percentage is visible in Settings -> Library.

"Auto download latests songs", "Auto download latest podcast episodes" and "download all songs" are coming next.

**Comment by BLeeEZ** [comment]
"Auto download latest songs" option is implemented in fdd72320539f1ffe2e0c05be670299f011cd89e6.
"Auto download latest podcast episodes" option is implemented in 90fa346901b76f31151852527c61033603692dce.
Button to add all songs in library to the download queue is implemented in 6fe786a5c4a0d87dbc22b839cf8595c3ab630c8f.
Button to add all artworks in library to download queue is implemented in 47905a8b96abad3bbd849d9835f92444d8cfb870.
