### ISSUE TITLE
[Feature request] Ability to fetch entire library at once

### ISSUE THREAD

**Issue by el-tiuri** [BLeeEZ/amperfy#114]
(Related to #113)

It’d be useful to fetch the entire music library without manually searching for music. I personally like to scroll through my music library to find something to listen to, which sadly isn’t feasible when my entire library isn’t fetched. This would make library statistics more useful as well.

**Comment by BLeeEZ** [comment]
Sounds good, I add it to the backlog.

**Comment by BLeeEZ** [comment]
This feature is implemented in b21ffb925d6794639395415772b593375d4a4ffa.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
