### ISSUE TITLE
[Feature request] Ignore “the” and “a” when sorting alphabetically

### ISSUE THREAD

**Issue by el-tiuri** [BLeeEZ/amperfy#115]
Right now, all artists, albums and songs starting with “the” or “a” are sorted under T or A respectively, while the standard way of sorting ignores these words. Could this please be changed or at least be an option you could toggle?

Thanks for your work on this fantastic app, by the way.

**Comment by bbsixzz** [comment]
Good idea.

**Comment by BLeeEZ** [comment]
After trying to implement this feature for a few days I fount out that it is not that simply to accomplish.
As stated here: https://stackoverflow.com/questions/5892450/core-data-sorting-by-transient-property-workaround properties that are calculated (name property of artists with out "the" or "a") can not be used as sort property.
The approach to scan over all artists and write the name to a second property is way too clunky in my opinion. This feature is for now not going to be implemented. If some one has a better approach to this feature and can send me a pull request, I would be happy to merge it.

**Comment by el-tiuri** [comment]
Hi, I don't know exactly how you implemented searching, but I found something things that might perhaps help. V2 of ID3 tags support data fields for how an item should be sorted. I don't know if Amperfy ever reads the ID3 tags directly or if this is all done through the subsonic API though.
