### ISSUE TITLE
[Interface] Add play status for currently playing track in the list

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#116]
iPhone SE 2016 iOS 15.4.1, Amperfy 1.1.0 (1)

To help with orientation it would be useful to indicate the currently playing track in the list.

![IMG_DDF7A5BBFD8A-1](https://user-images.githubusercontent.com/47334163/163075941-71b47c87-bb58-49ac-b8d8-2568e7fa539c.jpeg)

<img width="375" alt="IMG_D5AB7F53F86A-1" src="https://user-images.githubusercontent.com/47334163/163076250-0eaf88dc-876b-4113-bafa-75372f96aaa3.png">

**Comment by BLeeEZ** [comment]
Is implemented in 15abb0a88bbbd2dcb4d35fdf716d16908eb5dad9.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
