### ISSUE TITLE
[Interface] Cramped affordances in mini player sheet

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#119]
iPhone SE 2016 iOS 15.4.1, Amperfy 1.1.0 (1)

The icons are placed very close together which causes easy mistakes.

I've tapped the podcast icon multiple times by mistake which pauses the music immediately.

Consider moving it to the left side so that an accidental tap doesn't cause as much trouble.

![IMG_C35222CB7047-1](https://user-images.githubusercontent.com/47334163/163680626-d5410692-7e63-4050-aa89-f9c6d9522f08.jpeg)

**Comment by BLeeEZ** [comment]
Done in 2d23bbfab1f70f6b938e8cf72b5528d3b4fcaaf3.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
