### ISSUE TITLE
[Feature request] X-Callback URL Support (or Shortcuts support)

### ISSUE THREAD

**Issue by peterhajas** [BLeeEZ/amperfy#120]
It'd be awesome if Amperfy supported X-Callback URLs (or Shortcuts), so it could be integrated with other systems.

For example:

- getting list of artists, albums, tracks
- starting playback of artists, albums, tracks

**Comment by BLeeEZ** [comment]
Sounds cool. I add it the feature list.

**Comment by BLeeEZ** [comment]
After some restructuring Amperfy now supports the first Siri Shortcut commando "Search And Play":

![Simulator Screen Shot - iPhone 11 - 2022-06-11 at 19 13 24](https://user-images.githubusercontent.com/17556018/173197873-8c128e93-525c-411d-9a18-827363446551.png)

![Simulator Screen Shot - iPhone 11 - 2022-06-11 at 19 14 25](https://user-images.githubusercontent.com/17556018/173197894-088bb174-77ea-464f-b4af-27f1c51ac6d0.png)

Is this what you requested? Do you have other commands in mind? Title, input parameter, result would be helpful.

**Comment by BLeeEZ** [comment]
X-Callback-URLs are now supported. Following the current supported URLs. I added a new view to settings to directly show the documentation of the URLs in Amperfy itself.

![Simulator Screen Shot - iPhone 11 - 2022-06-13 at 20 26 25](https://user-images.githubusercontent.com/17556018/173420112-59cd4660-3fa4-4c53-9b3f-17bbd0b248cc.png)

![Simulator Screen Shot - iPhone 11 - 2022-06-13 at 20 27 09](https://user-images.githubusercontent.com/17556018/173420262-9589f090-2cc7-4bfc-9349-399501c5726f.png)

**Comment by peterhajas** [comment]
This is awesome, thank you! I played with the Shortcuts support on the Testflight beta and this is exactly what I was hoping to have.

Thanks for making a great GPL iOS app!
