### ISSUE TITLE
[Bug] App crash when playing tracks from search results

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#122]
iPhone SE 2016 iOS 15.4.1, Amperfy 1.1.0 (1)

https://user-images.githubusercontent.com/47334163/167300188-ce548a79-db54-4f68-b507-8557150c87ca.MOV

**Comment by BLeeEZ** [comment]
Yes you are right. I can reproduce this crash on my device too. This will be fixed.

**Comment by BLeeEZ** [comment]
Fixed in 799f5064f5a029a6239887b255596e7d5e000497

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
