### ISSUE TITLE
[Interface] Album view buttons visual feedback

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#123]
iPhone SE 2016 iOS 15.4.1, Amperfy 1.1.0 (1)

Please implement visual feedback when tapping Play and Shuffle buttons.

![31B12A34-5EC8-4CD8-AF6B-EC0C9128B193](https://user-images.githubusercontent.com/47334163/167300681-7c470217-17df-48a8-97ac-44bb8c06f76d.png)

A simple color fade works great like in the long tap sheet.

![E9BF3F3A-F195-4A72-9E70-B0270D967682](https://user-images.githubusercontent.com/47334163/167300618-675ee1ab-b77d-4747-902d-5d5f23d295d6.png)

**Comment by BLeeEZ** [comment]
Thank you, you are right. I noticed that the icon itself behaves correct, but the text color stays white during active press. This will be fixed.

**Comment by BLeeEZ** [comment]
Fixed in ffaac2cd1fe32f350ce18d647cc92c455c2b2a46.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
