### ISSUE TITLE
Improve Accessibility by making it obvious which files are downloaded/cached and which are not

### ISSUE THREAD

**Issue by metalune1** [BLeeEZ/amperfy#124]
Below I attached a screenshot of a monochrome display and as you can see, there is no way to see which files are downloaded.

![image](https://user-images.githubusercontent.com/78986003/167360938-cbd8e626-56ca-4125-8c61-2041c83132b1.jpeg)

**Comment by metalune1** [comment]
awesome!

**Comment by BLeeEZ** [comment]
Fixed in b70f367506d8c02a35fc3a7ba4b6956965375829:

Song table cells:
<img width="407" alt="Bildschirmfoto 2022-05-13 um 20 36 42" src="https://user-images.githubusercontent.com/17556018/168346397-5422b12e-c8cd-4bc4-957e-1565a17bb34b.png">

Podcast table cells:
<img width="403" alt="Bildschirmfoto 2022-05-13 um 20 37 48" src="https://user-images.githubusercontent.com/17556018/168346387-291afeb4-0136-4167-a96f-a96a65db9add.png">

**Comment by metalune1** [comment]
awesome!

**Comment by metalune1** [comment]
I love this project

**Comment by bbsixzz** [comment]
This is great, but I would like to request it be shown in Song/Album/Artist view as well.

Once again I think iSub does it well without overcrowding the right side which shows track length as per my request https://github.com/BLeeEZ/amperfy/issues/126

![IMG_F7CDB5C781DF-1](https://user-images.githubusercontent.com/47334163/169925033-1bf7faf1-c7e3-4974-8bc4-9431a9692973.jpeg)

Apple does it like this but has no track length, but maybe a small icon would work too.

![IMG_9F53E96D9013-1](https://user-images.githubusercontent.com/47334163/169925364-2fd87297-992c-4ec6-873d-07a4d36220bd.jpeg)

**Comment by BLeeEZ** [comment]
If a album/artist/playlist/... is completely cached: "Cached" is written in the detail header: 0111561e52b97b1b3c1fe6c081b58c47df214a35

**Comment by bbsixzz** [comment]
I think this doesn't really do anything, the whole idea is to see at a glance when scrolling the album or artist view which albums/tracks are cached. 

If all albums in artist view are cached then the text cached appears, but if only a few are cached you have no idea.

This also relates to #161 that no longer displays a list which could be better used display extra info like exemplified.
