### ISSUE TITLE
[Interface] Track number alignment

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#125]
iPhone SE 2016 iOS 15.5, Amperfy 1.1.0 (2)

The track number is not aligned to the track name.

I know there are two rows (to include track artist), but it would look better if the track number was aligned to the first row.

![IMG_450CA7FECA07-1](https://user-images.githubusercontent.com/47334163/169921403-64da2b40-2402-4b31-b6e8-2e7b4cea728a.jpeg)

The distance to the track name should be increased slightly as well.

![IMG_9F53E96D9013-1](https://user-images.githubusercontent.com/47334163/169922284-8521f14e-ca0e-49ec-9fe7-47013656ea4d.jpeg)

**Comment by BLeeEZ** [comment]
The distance between title and track number is increased in 6bd08fdd5650d5dd45438738434a06f9e8d0da2d.
I tested the alignment with the title and I personally prefer the vertical center style -> For now no changes.

**Comment by bbsixzz** [comment]
Ok that's fine, thanks!
