### ISSUE TITLE
[Interface] Individual track length

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#126]
iPhone SE 2016 iOS 15.5, Amperfy 1.1.0 (2)

Please add track length to individual tracks like in iSub.

Both in Album/Songs view and in the mini player.

![IMG_B99E826F19A9-1](https://user-images.githubusercontent.com/47334163/169922526-0c53a673-3fb3-47a7-8df2-016557d3f8a5.jpeg)

**Comment by BLeeEZ** [comment]
I don't think I will add this information to the table cell directly. From my point of view this clutters the table view up. The information is displayed in the DetailView via a long press. Apple Music and Amazon Music does it the same way.

**Comment by BLeeEZ** [comment]
I added an option (in 29dbe6b) to the settings view under "Display" -> "Song Duration".
With this settings the duration will be displayed in all song table rows:

![Simulator Screenshot - iPhone 15 - 2024-01-04 at 12 11 39](https://github.com/BLeeEZ/amperfy/assets/17556018/2e87b4e7-f798-47ab-a06a-57a66644989c)
