### ISSUE TITLE
[Interface] Inconsistent blue Artist and Album links, no animation

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#127]
iPhone SE 2016 iOS 15.5, Amperfy 1.1.0 (2)

The artist name is blue in the mini player but grey in the album view, could you please make both blue for consistency?

![IMG_74F34B7EFACE-1](https://user-images.githubusercontent.com/47334163/169922815-9303aa48-0404-42aa-8ed1-d7410d5077d4.jpeg)

I think the track name should also be blue in the mini player to indicate possible interaction.

![IMG_95F7F1B66D17-1](https://user-images.githubusercontent.com/47334163/169923062-7f90e03f-94ed-4eb8-8f1b-cdc6e8f1f14e.jpeg)

When the links are tapped a simple fade animation like on the Play and Shuffle buttons would give better feedback.

**Comment by BLeeEZ** [comment]
The blue artist names have been aligned in f545787956de4319710df79501a372a6bb7b258d. 
The visual feedback is not that easy to accomplish. The button is a simple overlay and has no effect on the displayed text. For that reason the text color can not be adjusted by a press.
