### ISSUE TITLE
[Bug] Show recently added, strange animation behavior

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#129]
iPhone SE 2016 iOS 15.5, Amperfy 1.1.0 (2)

The order is also still wrong as per https://github.com/BLeeEZ/amperfy/issues/94

https://user-images.githubusercontent.com/47334163/169925829-063b2e9b-f0dc-44db-a7d2-452e4dcd03ba.MP4

**Comment by BLeeEZ** [comment]
This bug is already fix in 17a5bcab5269f91cfbd2198d49394a04478c9204.

**Comment by BLeeEZ** [comment]
Can you confirm that this bug is not occurring on your device anymore?

**Comment by bbsixzz** [comment]
Yes the bug is fixed!

What about sorting bug https://github.com/BLeeEZ/amperfy/issues/94 ?

I think the reason it's wrong is because it sorts by name or rating, but not date added.

![Screenshot 2022-05-31 at 14 05 13](https://user-images.githubusercontent.com/47334163/171169673-1b5571dd-5b7a-4bb2-8d40-01ef4dace8e2.png)

**Comment by BLeeEZ** [comment]
No updates regarding the order. The order is a separate feature which I will track in the already open feature request: https://github.com/BLeeEZ/amperfy/issues/94
This will not be fixed in v1.1.0 due to the fact to finally release this version.
