### ISSUE TITLE
[Interface] Mini player next track button

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#130]
iPhone SE 2016 iOS 15.5, Amperfy 1.1.0 (2)

Please add a next track button to the mini player.

![171685BC-E026-4D50-991E-21D09A7163AE](https://user-images.githubusercontent.com/47334163/170006596-d2269cd8-a2c1-49dc-861b-01a0c1906fff.jpeg)

**Comment by BLeeEZ** [comment]
I am currently not sure if this feature will come. If it comes then in version v1.1.1.

**Comment by BLeeEZ** [comment]
Implemented in 31df8c9

**Comment by BLeeEZ** [comment]
This feature can be tested in v1.2.0 (1). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25
