### ISSUE TITLE
[Interface] Mini player sheet, tap track name to navigate to track location in album

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#131]
iPhone SE 2016 iOS 15.5, Amperfy 1.1.0 (2)

When tapping the track name in the mini player sheet it takes you to the top of the tracklist in the respective album.

Please make it so that it scrolls down to the location of the track in the album, this way you don't have to scroll and find it.

This is especially problematic for large albums.

**Comment by BLeeEZ** [comment]
Good idea. This is implemented in b9317febc835b2bc402e39ef157d34c633befa46.
