### ISSUE TITLE
Show Starred/Favourite Songs

### ISSUE THREAD

**Issue by tom-davies** [BLeeEZ/amperfy#138]
There should be a library section for starred/favourited songs to make this subset of tracks easier to download

**Comment by BLeeEZ** [comment]
What you can do is go to Songs -> filter for favorites via upper right button „Show favorites„ -> then press „…“ -> „Play all displayed songs“ -> open the mini Musik player and press „…“ -> „Add Context Queue to playlist“ -> create a new playlist and select it: with that you have all favorites in one playlist which can now easily be downloaded.

What I can think of is: Add a new method to „…“ in songs: „Download all displayed songs“ under „Play all displayed songs“.

**Comment by Tak-MK** [comment]
What about a section just below "Podcasts" that would be "Starred"? I also have starred folders that doesn't appear because they aren't neither artists/albums/songs :(

**Comment by BLeeEZ** [comment]
Direct navigation to favorite/recent artists/albums/songs from library is implemented in 185f8d39091be83fafcaa37d3e61ec75664f8081
Download those lists is implemented in dce64992691b450626ef2bc06662978a02b74b06

**Comment by BLeeEZ** [comment]
This feature is now available in the latest beta version 1.1.2 (1): https://github.com/BLeeEZ/amperfy/issues/25. Can you give me some feedback?
