### ISSUE TITLE
Unable to change or delete server

### ISSUE THREAD

**Issue by hec666** [BLeeEZ/amperfy#139]
Unable to change or delete server

**Comment by BLeeEZ** [comment]
Can please describe what you are doing to reproduce the error? Do you get an error message? Are you trying to change it via Settings -> Server -> Manage server URLs -> "+"-Button?

**Comment by hec666** [comment]
In the Manage Server Url there are only "+" Button to add a new Server, and "edit" button to edit current server.
There's no way to delete a server (tried also to swipe).
And with the "edit" button is impossibile to edit (see image, edit changhe in "done" button but there's no way to edit)
![3C518135-9742-43F7-AE1F-5F6F05FD34CA](https://user-images.githubusercontent.com/83774216/179345309-03137eb2-46dc-421e-8edc-7cc613eff7cf.png)

**Comment by BLeeEZ** [comment]
The edit button only allows the user to delete server entries from the list (not to allow editing existing server entries).
It is not possible to change a server settings. The reason for this is that if someone changes the server url, the password could be leaked by trying to authenticate at the new url with the username and password.. 
What you can do is: Create a new server entry via "+". In that you enter your new server url (the server url you have adjusted). Then press on the new server entry to switch to it (the tick indicates the active server entry). After that you can delete the old server entry via Edit and the delete symbol.
Please let me know if this solved your issue.

**Comment by hec666** [comment]
Sorry but it seems to be impossible to delete a server, to delete or modify) every time I need to remove and reinstall the app.
First of all, il also impossible to change the username, also for testing with a  new server:
For this purpose, I've tried to connect at a public demo server (demo.ampache.dev) and to do this, I've must add a "demo" user at my server (to have same username at 2 servers).
Then, removed en installed amperfy, reconnect to my server with "demo" user and it's all'ok.
Trying to add a second server (demo) but failed for "autentication error".
Then, removed en installed amperfy again, trying to add for first the demo server, it's connected, but the app crashed when syncing.:
So i've removed en installed amperfy again and connect is ok with my proper serv and user.

I've thought that almost the possibility to delete the server without remove/install the entire app will be appreciated.

Please note that i've also encountered problems of authentication with the public demo server (demo.ampache.dev).
In the past I've authentication problems also with my ampache server based on Nextclowd (you can find previous messages here on github), now I'm testing a new docker server to use your app (that is very good and I appreciate so much)  and enjoy my music, and i'ts work fine (except this modify/delete problem).
Thanks for your support and patience.
Best regards
