### ISSUE TITLE
Request feature : add Smart Playlist

### ISSUE THREAD

**Issue by YasserAntonio** [BLeeEZ/amperfy#14]
Hello,

Been using for few weeks now and  Amperphy is really cool. I just wanted to play the lastest songs I added on ampache using a smart list but it seems they dont show up on the playlists tab in the app. Is there a way to add them ? 

Many Thanks !

**Comment by BLeeEZ** [comment]
Hi,
thank you for your request.
Yes, currently smart lists are not supported. But to enable smart lists should be quite simple.

https://github.com/BLeeEZ/amperfy/blob/master/Amperfy/Api/Ampache/PlaylistParserDelegate.swift#L34-L42
In the previous mentioned lines the playlist id must be checked for Integer or a string in form of 'smart_' + Integer.

If you want the feature as fast as possible, you can do it for yourself and create a pull request.
I don't have a running development setup at the moment.
I think the earliest point in time to implement the feature is the holiday season.

**Comment by BLeeEZ** [comment]
Amperfy now supports Ampache's smart playlists with this 6231b0ac87cfbc156a4c973bf9cbde5a3b95bf73 commit.

**Comment by YasserAntonio** [comment]
Just received the commit mail, You rock ! Thanks !
