### ISSUE TITLE
Carplay not loading anything

### ISSUE THREAD

**Issue by mfat** [BLeeEZ/amperfy#140]
Amperfy loads all my songs on iPhone but nothing is shown in Carplay. Songs, Albums and Artists are all empty.

**Comment by BLeeEZ** [comment]
Have you tried to completely close Amperfy and restart it? The problem here is that CarPlay starts an own instance of Amperfy. In this instance some flags are not set if the sync occurred not long ago. I had a similar problem while testing. After some time the items should occur.

**Comment by mfat** [comment]
Yeah I tried killing Amperfy on the iPhone and opening it again. No luck.

**Comment by BLeeEZ** [comment]
I completely reworked CarPlay in this commit: f7b1c22374479e48014783851d8db46f99ec5f3f
With that CarPlay should work reliable and it has new features.

**Comment by BLeeEZ** [comment]
The reworked CarPlay screen is now available in the latest beta version 1.1.2 (1): https://github.com/BLeeEZ/amperfy/issues/25. Can you give me some feedback?

**Comment by rbeith** [comment]
Carplay still isn't showing any songs, artists, or albums in the latest version.

**Comment by jffgrumpy** [comment]
Thanks to the developers on building and maintaining the app.

I can also confirm that songs, artists or albums do not show up.

Some other CarPlay specific things I've noticed.

Loading playlists is very very slow and often crashes the app.

While using CarPlay and listening to music via Amplerfy and another sound plays (like a notification from a text message, navigation directions, locking the phone etc) I've had it where once said notification sound finishes, Amperfy doesn't play audio even though the song is still playing on the screen (CarPlay).  It seems the music is interrupted and sometimes it doesn't resume the audio like it should.  Most of the time it works but some of the time the audio doesn't come back.

I will say, of all the apps I've tried, while still not perfect, Amperfy usually starts playing audio when I start my car, that is, assuming you were playing music via Amperfy when you turned the car off.  Maybe I'm older but when I start my car and expect the radio to resume last state, either radio, Bluetooth music streaming or CarPlay music streaming.  From my experience, Amperfy is almost every time on Bluetooth and it some of the time on CarPlay.  But still more than most.

Thanks and keep up the good work.

**Comment by iamtheworstdev** [comment]
can confirm that carplay is completely broken

**Comment by jffgrumpy** [comment]
@iamtheworstdev  Mine is still been working other than the minor items I've noted above.  I don't see any updates for Amperfy since April. Perhaps iOS got an update and has broken Carplay for you? I should also mention I'm still on an iPhone 7 Plus running 15.7.8.  Can you try a different phone on your stereo? Maybe unpair is and pair it again?

**Comment by BLeeEZ** [comment]
I am now finally able to recreate some mentioned issues. I am further investigating on this.

**Comment by Janhouse** [comment]
Also unable to use Amperfy with Carplay.
Actually it seems to be broken with all Ampache/Subsonic apps currently, even paid ones. So no pressure. :smile:

**Comment by stratacast** [comment]
I decided to pay for play:Sub to see if it worked there, it's better but still doesn't work. I can see everything EXCEPT songs, but now playing works. Amperfy shows nothing except for now playing.

**Comment by BLeeEZ** [comment]
CarPlay is completely reworked and can be tested in v1.2.0 (1).
It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25
Can you please give me feedback if Amperfy now shows elements in your cars?

**Comment by 3zero2** [comment]
I noticed yesterday that the latest TestFlight version has completely updated CarPlay. I don't think there is a way to list all songs or all albums though, correct?

**Comment by BLeeEZ** [comment]
I am sorry for that but Apple limits the number of entries in the lists.
Apple says that they limit the number due to fact that the user should focus on the street and they want to prevent the driver to scroll through endless lists.
This is why I only display specific sections.
To mitigate this problem I additionally added the big Siri button to help the users find what they want via voice commands.
@3zero2 You mentioned empty sections on CarPlay. Are they now populated and displayed correctly?

**Comment by 3zero2** [comment]
No need to be sorry at all @BLeeEZ . I was thinking just the same - a long list would certainly be a distraction whilst driving. It's understandable that Apple doesn't allow long lists.

As far as I have tested, the UI and the different subsections do indeed show what is expected. I don't use the podcast aspect and I have yet to try the queue. Will open issues if I notice anything amiss.

A very big well done on your code - thank you.

**Comment by stratacast** [comment]
Interesting. Plexamp has all my music and songs listed out. Are there certain rules for certain projects?

**Comment by 3zero2** [comment]
> Interesting. Plexamp has all my music and songs listed out. Are there certain rules for certain projects?

On CarPlay?

**Comment by stratacast** [comment]
> > Interesting. Plexamp has all my music and songs listed out. Are there certain rules for certain projects?
> 
> On CarPlay?

Yes on CarPlay

**Comment by Batwam** [comment]
> I am sorry for that but Apple limits the number of entries in the lists.

Do we know how many items are allowed? It does appear to list songs in the queue which can be quite a long list.

Edit: according to [this old reddit post](https://www.reddit.com/r/apple/s/yBDDrWdpxo), the limit only applies when the car is in motion. Maybe something to consider and allow to scroll through Artists/Albums when the car is still?

**Comment by Batwam** [comment]
Ok, I just generated 400+ playlists and the first 50 appear in the Playlist section. I can then click on them and play all songs for that artist, unfortunately it’s only for the first 50 artists 😅

I had a look at the Spotify Artists list, it actually only had 36 items so it looks like they essentially filter what they want to show to make it fit within the limit. For instance, you could show the 50 most played artists either in alphabetical order or starting with the most played ones.
