### ISSUE TITLE
Crashes in a lot of standard cases making the app unusable after update from 1.0.8

### ISSUE THREAD

**Issue by Mysgym** [BLeeEZ/amperfy#142]
Using and iphone 6 running ios12 on an ampache server (ampache API), haven´t updated the app in about 6 months (can't remember the exact version), now on 1.1.1

The following cases (non exhaustive, haven't tested everything) make the app instantly crash :
   - Doing any search in the "all" tab, works for the first one or two letters then crashes. Gibberish giving no results works fine
   - tapping the "cached" tab
   - most (not all) artists' pages (tapping the artists name anywhere), this is artist dependent and I cannot find a pattern 
 
 Nothing appears in the event log at the times of crashes. The app is basically unusable now

**Comment by BLeeEZ** [comment]
This is really difficult to recreate without knowing the initial Amperfy version.
I am sorry but the best solution is to uninstall and reinstall again.

**Comment by Mysgym** [comment]
After checking the update history I can say for sure that the version I was using before is 1.0.8.
uninstalling and reinstalling didn't help

**Comment by sandersantema** [comment]
I'm running amperfy `1.1.1 build number 2`, the latest develop version of ampache which is commit `857dafcde74bd0fc529a5db43467b5241bae80fc` at the time of writing using the ampache api and iOS `15.5` and `15.1`.

I wasn't able to replicate any of the crashes reported, so my guess would be that it's either got something to with the specific server setup or the iOS version.

**Comment by Mysgym** [comment]
Ampache server is running 5.4.1 which is latest at the time of writing. IOS 12 is deprecated for many apps nowadays, wouldn't be surprised if that was the issue.

I'll try to switch the ampache server to subsonic API, but the app crashes when requesting the "cached" tab, intuitively I'd say this tab has nothing to do with the server and proves the issue if from the app

**Comment by BLeeEZ** [comment]
I think the problem lies in iOS 12. In the past this particular version made some problems. Apple stopped support. It is not even possible to report crashes via TestFlight in iOS 12 anymore. This makes it really difficult for me to maintain Amperfy on this iOS version. The simulator can’t reproduce some issues too. I am sorry to say that but I can’t manage to maintain Amperfy for iOS 12 anymore. Sorry.

**Comment by Mysgym** [comment]
No worries, though you should mark the IOS app as requiring IOS13, so that IOS12 users can't download it, hopefully this will allow me to downgrade to the older functional version at the same time. Thank you for your app and your help !
