### ISSUE TITLE
[BUG]: Amperfy crashes periodically while downloading

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#143]
I'm running amperfy 1.1.1 build number 2, the latest develop version of ampache which is commit 857dafcde74bd0fc529a5db43467b5241bae80fc at the time of writing using the ampache api and iOS 15.5 and 15.1.

I believe this bug is quite old, possibly even from when the download system was introduced. I can't remember if I reported this earlier when the download system had other bugs however or if I simply forgot to ever report it. Feel free to delete this bug report if it's a duplicate. 

What happens is that amperfy crashes when downloading songs after a while. The app closes without any error, and resumes downloading after restarting. I'm very happy to see how well resuming the downloads works :smile:, although some downloads don't resume but I assume that would be fixed if this bug is fixed. What I assume is happening is that there's somehow a memory leak, the memory gets filled up and iOS kills the app after a while. 

This isn't that much of a problem since downloading still works but rather inconvenient when downloading lots of music (on a new iPhone for instance, luckily the iCloud support solves much of the problem :smile:) since you can't leave amperfy to download unattended and have to manually restart the app once in a while.

**Comment by BLeeEZ** [comment]
I have two questions to narrow the bug search:
- Is it crashing when one song takes a very long time to download?
- Does it occur when a lot of items are in the download waiting queue?

**Comment by BLeeEZ** [comment]
I found an other bug in the download manager that lead to app crashes. I hope this fixes this too: https://github.com/BLeeEZ/amperfy/commit/10e30e4f3f2746c814cc8a08e01e14c8591a3e5f

**Comment by sandersantema** [comment]
I finally got around to redownloading my library. It did indeed still crash once in a while, I'll try again whenever the beta with [10e30e4](https://github.com/BLeeEZ/amperfy/commit/10e30e4f3f2746c814cc8a08e01e14c8591a3e5f) comes out. 

There's still a significant difference between storage usage on my server and on my phone. On my server the used storage is `43 GB`/ `43829  MB`, output of: `du -sh` and `du -sm`. Although I don't actually know whether these are in `MB/ GB` or `MiB/ GiB`.

While amperfy reports a usage of `45.65 GB`. Is this as expected? A reason I could think of is that the cached album arts consume some space, although I have my album art set to only display ID3 artworks.

**Comment by sandersantema** [comment]
With the latest update this is ready for testing again right @BLeeEZ ?

**Comment by BLeeEZ** [comment]
Yes it can be tested.

**Comment by sandersantema** [comment]
Hi took me a bit of time to get around testing it and some more time fixing some errors unrelated to amperfy itself on my ampache servers but everything seems to work smoothly and I experienced no crashes downloading a library of 40GB :tada:

If this is not related to #175 I think it can be closed.
