### ISSUE TITLE
[Feature request]Support Chinese and Lyrics

### ISSUE THREAD

**Issue by suimt6** [BLeeEZ/amperfy#146]
I like this app very much,I've been using amperfy to play music from my local navidrome server,I think it's the best subsonic app so far.
If it's not particularly difficult, consider adding Chinese and Lyrics support.Thanks very much!
Embedded lyrics are now supported by both the Subsonic API and in the UI.
Thanks again for your contribution.

**Comment by BLeeEZ** [comment]
Thank you.
Currently no localisation is planned. This needs a complete restructuring of the UI and a huge amount of testing.
The ability to display lyrics sound interesting. After thinking through needed adjustments an a rough effort estimation, I don't think that this feature will come soon.

**Comment by JaxzKyd** [comment]
> After thinking through needed adjustments an a rough effort estimation, I don't think that this feature will come soon.

That's unfortunate 😔

i will be anticipating its arrival though 😁

**Comment by stefan1983** [comment]
+1 on lyrics support

**Comment by Batwam** [comment]
Hello, is there an update in the timing for lyrics integration? My understanding is that Navidrome supports synced lyrics (exclusively).

**Comment by yuygfgg** [comment]
> Hello, is there an update in the timing for lyrics integration? My understanding is that Navidrome supports synced lyrics (exclusively).

You can try my fork. It's only experimental and lyrics do not show in an pretty way. 
In fact, it's my first time to try to code. So it may be buggy. [here](https://github.com/yuygfgg/amperfy)

**Comment by BLeeEZ** [comment]
Thank you for the provided code.
This is a good first reference implementation.
Unfortunately this code breaks some of paradigms.
-  I want to support as much functionality as possible in offline mode. This means all lyrics need to be saved in database (core data). 
- I currently request always xml to be consistent with all other API functions.
- I don’t want that the user needs to create other accounts other than the Ampache/Subsonic account. The lyrics need to fetched via the provided subsonic API.
- All external frameworks need to be available via swift package manager.

I am currently planning to support lyrics in 1.2.2.
I will then use the OpenSubsonic API instead of Subsonic API for the lyrics feature.

**Comment by yuygfgg** [comment]
> Thank you for the provided code. This is a good first reference implementation. Unfortunately this code breaks some of paradigms.
> 
> * I want to support as much functionality as possible in offline mode. This means all lyrics need to be saved in database (core data).
> * I currently request always xml to be consistent with all other API functions.
> * I don’t want that the user needs to create other accounts other than the Ampache/Subsonic account. The lyrics need to fetched via the provided subsonic API.
> * All external frameworks need to be available via swift package manager.
> 
> I am currently planning to support lyrics in 1.2.2. I will then use the OpenSubsonic API instead of Subsonic API for the lyrics feature.

Glad to hear you will be adding support for lyrics. But I would still like some kind of online lyrics fetch because few people have their lyrics collection.

**Comment by Batwam** [comment]
> I am currently planning to support lyrics in 1.2.2.
I will then use the OpenSubsonic API instead of Subsonic API for the lyrics feature.

I think that this is the right move as my understanding is that the Subsonic API implementation in Navidrome strips out the timestamps in synced lyrics (for compatibility reason).

It's great to hear that this feature is coming soon. Will you implement synced lyrics and automatic scrolling?

**Comment by BLeeEZ** [comment]
Lyrics are now supported with 1723445f5721dfae13b3b5e500469390559e5833 and 05baeb4397dd943c36c62c16d48d87c223e2c2d1:

![Simulator Screenshot - iPhone 15 - 2024-06-18 at 19 32 15](https://github.com/BLeeEZ/amperfy/assets/17556018/11fae6e5-b56a-4481-9aa9-5ebc4de0d9be)
![Simulator Screenshot - iPhone 15 - 2024-06-18 at 19 31 51](https://github.com/BLeeEZ/amperfy/assets/17556018/f5d00b9e-7d4e-4ba4-ad1f-719eedb66844)

**Comment by Batwam** [comment]
I'd be happy to test but I'm on the latest TestFlight version and can't seem to see it. Which app version is this in?

**Comment by BLeeEZ** [comment]
It is currently only available for developer builds. TestFlight beta versions are a lot of work so I only do them before bigger versions. Currently v1.2.1 is in testing so I am not adding new big features to complete the version as fast as possible. After the completion I prepare for v1.2.2 which will in the end contain the lyrics feature. It can take some time till this feature will be available on TestFlight.

**Comment by BLeeEZ** [comment]
The lyrics feature can now be test on iOS via TestFlight (https://github.com/BLeeEZ/amperfy/issues/25) in v1.2.2 (2).

**Comment by Batwam** [comment]
Works for me (navidrome, synced lyrics)

**Comment by tinusplotsklaps** [comment]
hi, I would like to TestFlight your app and need an invitation from a developer to start this. Do you know how to get such an invitation?

Kind regards, Martijn

**Comment by BLeeEZ** [comment]
@tinusplotsklaps hi, it should be sufficient to click on the link (https://testflight.apple.com/join/HCZzB1fU) and join via TestFlight. There is no other invitation needed. Could you share a screenshot of the requested invitation?

**Comment by tinusplotsklaps** [comment]
sorry for the late reply. Your link works well. The new features are great!

**Comment by suimt6** [comment]
Thank you very much for supporting lyrics. Can Carplay add dynamic lyrics display?

**Comment by Batwam** [comment]
That would be neat but pretty sure it can't.
