### ISSUE TITLE
[Bug] Play from artist view wrong order

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#147]
iPhone SE 2016 iOS 15.6, Amperfy 1.1.1 (2)

Playing all albums from artist view adds the tracks in alphabetical order causing a big mess instead of sorting them correctly by album.

https://user-images.githubusercontent.com/47334163/183984594-0841f1fa-75f8-4908-99a8-8675efa956c6.MOV

**Comment by BLeeEZ** [comment]
I wouldn’t say this is a bug. It works as intended. The sorting order is discussable. I thought  „play“ in artist view should play all songs as displayed in artists songs section. I can understand that songs sorted by albums has benefits (for „play“ button). I think I will change it to your description order.

**Comment by bbsixzz** [comment]
Ok I understand! Thank you.

**Comment by BLeeEZ** [comment]
In this commit f0fcd5b35a930ebb605abab81cc61dfd980516bf the feature is implemented.
If you tab on Play in artists it will play all songs sorted by (album year and song track).
Tabbing on play in PopupDetail behaves in that way too.

**Comment by bbsixzz** [comment]
Very cool looking forward to it!

**Comment by BLeeEZ** [comment]
This feature is now available in the latest beta version 1.1.2 (1): https://github.com/BLeeEZ/amperfy/issues/25. Can you give me some feedback?

**Comment by bbsixzz** [comment]
This works, thank you!
