### ISSUE TITLE
ability to edit library

### ISSUE THREAD

**Issue by hellojaccc** [BLeeEZ/amperfy#148]
hi, first of all, thanks for creating this app. It's almost the only one with good design.

I think it'd good to be able to disable few things in library.

My server(lightweight music server) doesn't support podcast, so it has no use. Also i dont use genre(my music files doesnt support em). Not having to scroll down to see downloaded music would be very nice

![image](https://user-images.githubusercontent.com/71537512/185333996-edbf0880-d6a8-4315-8571-72254a7a5cdd.jpeg)

**Comment by BLeeEZ** [comment]
Sounds cool and not too much effort. I add it to the feature list.

**Comment by BLeeEZ** [comment]
With this commit 0977af5e9185d8443e2afece4f07e16d222d8e5c library entries can be changed in order and be hidden.

**Comment by BLeeEZ** [comment]
This feature is now available in the latest beta version 1.1.2 (1): https://github.com/BLeeEZ/amperfy/issues/25. Can you give me some feedback?
