### ISSUE TITLE
Music progress bar is broken after downloading

### ISSUE THREAD

**Issue by hellojaccc** [BLeeEZ/amperfy#149]
![image](https://user-images.githubusercontent.com/71537512/185334471-835ad320-e4d6-4daf-892b-afa92fe72aa4.png)

It automatically downloads while im listening to music, and after download finishes, my progress bar is broken.

**Comment by hellojaccc** [comment]
If i close that and play saved music again, this bug doesnt happen

**Comment by BLeeEZ** [comment]
Interesting... I need to investigate on this one.

**Comment by hellojaccc** [comment]
Hmm weird, it only happend when i use lightweight music server (lms) and after changing api server, this doesnt happen.

Other lms user may help with this issue.

**Comment by mneuburg-livefront** [comment]
Personally I've never seen the progress meter move, and it shows identical times at both ends. Nothing to do with server type or downloading. It's just broken. I've written directly to the developer, who seems not to believe me or my screen shots. 

![AmperfyTimes](https://user-images.githubusercontent.com/125824749/221719498-0b9b9f82-57bb-4a52-bad3-42a127fd2610.png)

**Comment by BLeeEZ** [comment]
@mneuburg-livefront I am ignoring you with intention. Amperfy is a free of charge App that I develop in my precious free time. Your way of communication is toxic. 
I asked you for additional information to fix your mentioned bugs but with your answer:

> I sent you a log. If you're not logging the info you need in order to see what I did, what the app said to the server, what the server said to the app, etc., maybe the logging should be improved.

You can't just say everything is not working and not doing the easiest look ups. Please uninstall Amperfy and leave me alone. You are the first person in 2 years GitHub developing to whom I need to say this...

**Comment by BLeeEZ** [comment]
@hellojaccc during implementing support for transcoding, I found out that this is a server issue. If the server transcodes a file, the playback duration cannot be provided correctly (it is a still open issue on Ampache). In these cases Amperfy will now display "--:--" as remaining time.

**Comment by BLeeEZ** [comment]
This bug fix can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25
