### ISSUE TITLE
Cannot stop the download attempts

### ISSUE THREAD

**Issue by Crisper-Dong** [BLeeEZ/amperfy#151]
The App is just great, but there's an issue:

I'm using amperfy on a relatively old iphone with relatively little storage, thus I disabled client download on the music server. The only download option in the settings page is the "Artwork download settings". Despite it being turned off, the app still constantly complains the error "API error 50". 
Is there a setting to turn off the download? 

PS: I always listen to some soft music before I go to sleep, I'd love to see a sleep timer feature to be added!

**Comment by BLeeEZ** [comment]
Thank you.
Did you disable the song cache setting too? Settings -> Player -> "Auto Cache Played Songs"
Regarding sleep timer. I like the idea. Could you please create a new "Issue" to track the feature separately from this bug.

**Comment by Crisper-Dong** [comment]
Solved. 
The feature request issue is submitted. [https://github.com/BLeeEZ/amperfy/issues/153](url)
