### ISSUE TITLE
Sleep Timer

### ISSUE THREAD

**Issue by Crisper-Dong** [BLeeEZ/amperfy#153]
I always listen to some soft musics before I fall asleep. However, every time I need to set a stop playing timer in "Clock", which is kinda frustrating.

I'd love to have a sleep timer feature!

**Comment by BLeeEZ** [comment]
The sleep timer feature is now available in the latest beta version 1.1.2 (1): https://github.com/BLeeEZ/amperfy/issues/25. Can you give me some feedback?

**Comment by Crisper-Dong** [comment]
Great! The feature is working as expected.
But the panel is kinda hard to access. Maybe it can be placed in the playback interface, beside the random/sequential button? 
Anyway, thanks~

**Comment by bbsixzz** [comment]
It's a nice feature but I think putting it in the playback interface would make it cluttered, not everyone uses it.
