### ISSUE TITLE
[FEATURE] option button to enable scrobbling for streamed songs

### ISSUE THREAD

**Issue by el-tiuri** [BLeeEZ/amperfy#154]
Amperfy has recently stopped syncing the playback of songs to my Navidrome server, meaning they couldn’t be scrobbled. Scrobbling works just fine when playing it from Navidrome’s web interface or when playing it through another app, so I’m pretty sure the issue lies with Amperfy.

**Comment by BLeeEZ** [comment]
Is offline mode deactivated? Amperfy only scrobbles when in online mode. Songs played in offline mode are saved and scrobbled when in online mode again.

Did you completely shutdown Amperfy via app switcher and restarted Amperfy again?

Are there any interesting log messages in Settings -> Support -> Event Log?

**Comment by el-tiuri** [comment]
Offline mode isn't enabled, and restarting the app didn't change anything either. Sadly, the logs don't show anything either. Would joining the beta help with getting more detailed logs, perhaps?

**Comment by BLeeEZ** [comment]
I looked through the code again and I found another check. Are you caching the songs? Amperfy doesn't perform a scrobble if the song is streamed. The server usually performs a scrobble by itself if a songs is requested via stream.

**Comment by el-tiuri** [comment]
That’s it! I re-enabled caching and now it works again. I’m using Navidrome as server, so I’m assuming something goes wrong there if it’s not explicitly requested to scrobble it, which does work with the other apps I use.

For now I’ve just re-enabled caching and I’ll just settle for occasionally emptying the cache.

**Comment by el-tiuri** [comment]
Could it perhaps be possible to add an option to explicitly scrobble even when streaming?

**Comment by BLeeEZ** [comment]
Yes, i can add this this button as a feature. I rename this open issue to keep track of this feature request.

**Comment by BLeeEZ** [comment]
Done in 43f44657fe0d9484646b54865206e1b8bfc7cf45

![Simulator Screenshot - iPhone 15 - 2024-02-25 at 12 54 52](https://github.com/BLeeEZ/amperfy/assets/17556018/82899c7a-7085-4a85-b6f1-5b037fe5bd0d)

**Comment by BLeeEZ** [comment]
This feature can be tested in v1.2.0 (1). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25
