### ISSUE TITLE
Album Artist instead of Artist

### ISSUE THREAD

**Issue by dbkc** [BLeeEZ/amperfy#155]
Currently it looks like the Artist list is using the ID3 Artist field where most apps for Air/subsonic and Plex are using the Album Artist to make the list a lot smaller and cleaner. Is it possible to either change to Album Artist or a toggle to switch the list to using that tag for the Artists list?

**Comment by BLeeEZ** [comment]
The subsonic API states [subsonic api](http://www.subsonic.org/pages/api.jsp):

> Starting with version [1.8.0](http://www.subsonic.org/pages/api.jsp#versions), the API provides methods for accessing the media collection organized according to ID3 tags, rather than file structure.
> 
> For instance, browsing through the collection using ID3 tags should use the `getArtists`, `getArtist `and `getAlbum `methods. To browse using file structure you would use `getIndexes `and `getMusicDirectory`.

This is reflected in Amperfy too. Artists, Albums and Songs are sorted via ID3 tag. The Directory section in Amperfy uses the file structure.

**Comment by dwkra** [comment]
For UI and UX sake I’d also like the ability to browse by Album Artist without having to use the Directory option. The Directory option misses all the nice modern UI elements, like artist images, that many media players/streamers have. 

With many popular genres of music featuring a different combination of artists on each track of their albums, browsing by Artist is significantly less desirable for than Album Artist. You can see in the screenshot I’ve attached I have two Gunna albums, but 18 extra Artist listings I have to browse through. 

![IMG_4806](https://github.com/BLeeEZ/amperfy/assets/48136288/cee1c916-499b-46c4-b5a7-d9ed0a3214a4)

**Comment by BLeeEZ** [comment]
Album artist filter is added via (https://github.com/BLeeEZ/amperfy/commit/5fcaa1b1acf41f309e918bd9473fc4ce4b1ea494). It is default on.
