### ISSUE TITLE
[Feature request] file info, hide items in libray panel

### ISSUE THREAD

**Issue by uprprc777** [BLeeEZ/amperfy#158]
Just some misc feature request.

Feature to view file infos like bit rate, encoder...

Feature to hide unwanted items in the library panel, e.g. hide the "genres" and "podcats".

**Comment by BLeeEZ** [comment]
With this commit 0977af5e9185d8443e2afece4f07e16d222d8e5c library entries can be changed in order and be hidden.

**Comment by uprprc777** [comment]
Great! Thank you!

**Comment by BLeeEZ** [comment]
Bitrate is now displayed too with this commit 2c3d3a61ff4a9b154d591f992c760e0d8278eb27.
Bitrate is the only missing information that is available via XML API.
