### ISSUE TITLE
[Feature] SupporttTranscoded files 

### ISSUE THREAD

**Issue by musiclandUSA** [BLeeEZ/amperfy#159]
Running the beta version of amperfy against the newest ampache (5.5.2 as of writing)

The app throws lots download errors, one for each song, all of them status code 1 file is empty.

I'm using AAC+ as the codec so I'm not sure if that is the cause, but it seemed to work fine with mp3 before I switched.

`-movflags +faststart` is set to be used.
`encode_args_m4a = "-vn -c:a libfdk_aac -profile:a aac_he -vbr 3 -movflags +faststart -f adts pipe:1"` is the ffmpeg command set

The only thing I can see from the logfile that might hint at an issue is this:

```
2022-09-20T11:55:17-04:00 [ampache] (/home/music/public_html/ampache/vendor/nyholm/psr7/src/MessageTrait.php:185) -> Header values must be RFC 7230 compatible strings.

2022-09-20T11:38:35-04:00 [ampache] (log.lib) -> [Runtime Error] Header may not contain NUL bytes in file /home/music/public_html/ampache/src/Module/Application/Playback/PlayAction.php(854)
```

The logfile for ampache shows successful encodes and files play fine through the web interface.

**Comment by BLeeEZ** [comment]
Amperfy uses the URL provided in the XML response to download songs.

Could you please navigate to your songs download URL in your browser and check if it contains the correct file.
It seams the Ampache server API does not return the correct file.

Use this URL to get some song responses for a album id (filter value):
http://x.x.x.x/ampache/server/xml.server.php?action=album_songs&auth=xxxx&filter=14712

Example song URL which is used to download files:
https://x.x.x.x/play/index.php?ssid=xxxx&type=song&oid=115&uid=4&player=api&name=Chi.Otic%20-%20Are%20we%20going%20Crazy.wma

**Comment by musiclandUSA** [comment]
I don't know what's supposed to go in `auth=` but I did pull these down by setting ampache to stream and pulling the playlist URLs inside:
```

https://servername.com/ampache/play/index.php?ssid=SSID&type=song&oid=10042&uid=2&name=Otis%20Redding%20-%20Mr.%20Pitiful.flac
https://servername.com/ampache/play/index.php?ssid=SSID&type=song&oid=603&uid=2&name=Andre%20Kostelanetz%20-%20It%20Came%20upon%20the%20Midnight%20Clear%20-%20Awayin%20a%20Manger.flac
https://servername.com/ampache/play/index.php?ssid=SSID&type=song&oid=10077&uid=2&name=William%20Bell%20-%20Everyday%20Will%20Be%20Like%20A%20Holiday.flac
https://servername.com/ampache/play/index.php?ssid=SSID&type=song&oid=11070&uid=2&name=Beatles%20-%20And%20I%20Love%20Her.flac
https://servername.com/ampache/play/index.php?ssid=SSID&type=song&oid=9379&uid=2&name=Stan%20Getz%20-%20Asturd%20Gilberto%20-%20The%20Girl%20From%20Ipanema%20-Unedited%20Stereo%20Remaster-.flac
https://servername.com/ampache/play/index.php?ssid=SSID&type=song&oid=10825&uid=2&name=Supremes-%20The%20-%20Stop-%20In%20The%20Name%20Of%20Love%20-Instrumental%20With%20BGV-.flac
https://servername.com/ampache/play/index.php?ssid=SSID&type=song&oid=9448&uid=2&name=Jimi%20Hendrix%20Experience-%20The%20-%20Red%20House.flac

```

**Comment by BLeeEZ** [comment]
Transcoding is now implemented and supported.
![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-22 at 21 03 21](https://github.com/BLeeEZ/amperfy/assets/17556018/988c5be4-9432-48cf-a69c-0b28dce4afef)

**Comment by BLeeEZ** [comment]
This feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25

**Comment by BLeeEZ** [comment]
Did you have time test the feature? Is it behaving as you expected?
