### ISSUE TITLE
Albums permanently vanishing when server inaccessible.

### ISSUE THREAD

**Issue by mediadev123** [BLeeEZ/amperfy#160]
Hello, 

First of all, I want to thank you for the hard work you put into the app. For the most part it works perfectly. Thank you very much.

I have had a problem where albums seem to completely and permanently vanish sometimes. This happens mostly when the server is offline. The easiest way to replicate it is by removing the DNS entries to said server. 

Here is a video that shows how albums are vanishing and they are not reappearing once the DNS entries have been restored: 

https://user-images.githubusercontent.com/109393230/196438211-4f56d424-2239-48a8-9557-19acef85a87e.mp4

This causes artists to be completely empty (unless their songs are either already cached or downloaded) but it also says that an artists has several albums and songs. For example: ![IMG_2135](https://user-images.githubusercontent.com/109393230/196437808-f9cbd04d-3b14-4dd0-b708-62c02ab65bc4.PNG)

Although this bug mostly happens when the DNS server stops working (for example when my home internet is down and I have to switch to mobile data + turn off my VPN), there are other, less reliable ways for this issue to occur. It would be great if artist's album info could be refreshed somehow.

**Comment by mediadev123** [comment]
Thanks for the fast response. The current beta seems to fix the problem (at least with the DNS stuff). Is there a way to resync all albums or do I have to reinstall the app?

**Comment by BLeeEZ** [comment]
Sorry to tell you, there is no resync. You need to reinstall the app.
