### ISSUE TITLE
[Request] Collection view & list view

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#161]
iOS 16.1 - Amperfy 1.1.2 (1)

Collection view is nice but could you please provide an option to have the old list view back? 

The list view is more compact and shows more albums per screen and number of tracks.

Maybe in this menu?

![Screenshot 2022-10-19 at 02 54 50 png](https://user-images.githubusercontent.com/47334163/196572285-064b65c9-1ef7-49ba-8b5b-321fe93b26c6.png)

Thank you

**Comment by BLeeEZ** [comment]
Switching between complete different list styles (TableView and CollectionView) is not that easy. It results in a lot of redundant code. Recent albums, favourite album and "all" albums are using this class. To copy that it results in lot more testing effort. I can switch back to list view but then I will remove the collection view. It depends on the user feedback.

**Comment by bbsixzz** [comment]
Ok, functionality wise the list view was better.

1. More albums per page
2. Easier to read the titles in a vertical list
3. #124

**Comment by carlflash** [comment]
I think the list view was better for the same reasons + you could swipe on each album for various functions.

Now you have to tap and hold on each album which is inconvenient and takes more time.

It takes you out of the usage flow when browsing for something to listen to, please change it back.

**Comment by bbsixzz** [comment]
Amperfy 1.1.2 (2) is much better now!

Thank you
