### ISSUE TITLE
[Interface] Streamline player interaction and functionality

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#166]
Amperfy 1.1.2 (2)

I would like to suggest tapping the album artwork to expand and minimize the size like on the lock screen.

https://user-images.githubusercontent.com/47334163/206569893-4282be1e-f47d-4a9b-b2c9-b8b2365a520a.MP4

That would make the top left button redundant, replace it with `Clear Music Player` instead.

That removes the extra step of having to go into the kebab menu to clear the playlist.

![IMG_9A0839F5E190-1](https://user-images.githubusercontent.com/47334163/206570261-ff318163-c45c-42b5-8439-c0ce343575c7.jpeg)

**Comment by sandersantema** [comment]
I think having the album artwork as the button to open the queue might be too confusing as there is nothing to indicate tapping it will do something. 

I think it might be a nice idea to access the queue and the info screen currently under the three dots button located top right, via a swipe to the left or right. I don't think it's too important which is accessible via which swipe, it might be nice to have it configurable just as the functionality discussed in #89.

This cleans up the player and allows for easier access to both the info screen and queue, currently not quite so ergonomic to access.

To solve the problem of this functionality not being apparent dots like seen in the screenshot below above the safari and messages app can be used:
![image](https://user-images.githubusercontent.com/21057514/212770280-366f5e40-3991-4791-ab37-146b968ec841.png)

Alternatively `<` and `>` glyphs similar to the one currently displayed left of show queue button and music button could be used. 

Although there might be a better option which doesn't require hiding these UI elements when the queue or info screens are accessed (as they would take up space on these screens).

**Comment by bbsixzz** [comment]
> I think having the album artwork as the button to open the queue might be too confusing as there is nothing to indicate tapping it will do something.

Maybe we needed extra affordances on what is tappable back in 2007 but clearly Apple is ok with it like shown in the video.

We should strive for UI consistency following Apple's lead.

Frankly the queue should always be available from the main playback screen, just add it below and let us scroll down. Tapping the album art should only resize the album art and nothing more.

![FC399FD5-ACF0-42DA-A6B0-92091796E213](https://user-images.githubusercontent.com/47334163/212774862-d25e79d4-5a5b-4e97-8e63-6897db2706db.png)

Adding more swipes is unnecessary.

**Comment by carlflash** [comment]
Always available queue and minimize/maximize artwork by tapping on it makes a lot of sense and improves usability without introducing complexity.

Right now switching between the two modes makes you lose queue functionality just to view a larger image. For this reason I have the artwork in compact mode 99% of the time.

Having to go into the menu to clear the queue is also unnecessarily convoluted when you could just have the button in the top left like suggested.

**Comment by bbsixzz** [comment]
Any update on this with the new redesign?

Why have a button for it when you could just tap the icon instead? It would declutter the interface with one less button.

https://github.com/BLeeEZ/amperfy/assets/47334163/50f4789c-79d7-4ac4-bfc7-005a15c66f93

**Comment by BLeeEZ** [comment]
Artwork acts as button to switch between large image and playlist view (0649b058534506c637254d10ddd85ede4840396a).

**Comment by BLeeEZ** [comment]
This feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25
