### ISSUE TITLE
Wait longer before scrobbling

### ISSUE THREAD

**Issue by cwolfe3** [BLeeEZ/amperfy#167]
Currently the app scrobbles after 5 seconds, which is sometimes shorter than how long it takes me to identify a song or to decide whether to listen to it. This means a lot of songs get scrobbled even though very little of the song was played. Can this be extended or be user-configurable? The last.fm recommendation is 50% of the song played or 4 minutes, whichever is earlier.

**Comment by bbsixzz** [comment]
I agree, I think the default duration should at least be increased to 30 seconds.

**Comment by BLeeEZ** [comment]
Scribble time has been adjust in this commit: 199ed11bde5890e773546b9528510ae86adb7eed
I choose the last.fm config @cwolfe3 suggested.

**Comment by cwolfe3** [comment]
Fixed in release v1.1.2 for cached music. Thank you.
