### ISSUE TITLE
Navidrome support

### ISSUE THREAD

**Issue by argus-core** [BLeeEZ/amperfy#17]
I'm running a [Navidrome](https://www.navidrome.org) server and cannot login using Amperfy (Login failed, Not able to login, please check credentials! message). I can connect using the same address and credentials in iSub and SubStreamer as well as the web app. There are no logs server-side.

**Comment by BLeeEZ** [comment]
Thank you for reporting this issue. Did you provide http/https in the server URL?

**Comment by argus-core** [comment]
I tried both with and without https. It just occurred to me that this could be caused by the fact that I run Navidrome behind an Nginx reverse proxy with a self-signed certificate.

**Comment by argus-core** [comment]
Yup, I managed to log in when I removed the proxy from the equation and hit the http endpoint directly.

**Comment by argus-core** [comment]
It looks however like the library is not synchronizing, a message "Synchronizin 0.0" pops up and disappears. Looks like this may turn into two separate requests:
- Support a self-signed certificate case (I would expect it to be quite common in local network deployments)
- Investigate the synchronization with Navidrome

And since I failed to submit the original request properly:
- Navidrome is version 0.39.0 running in Docker on a Synology NAS
- Amperfy is the App Store version, I can't find a version number

**Comment by BLeeEZ** [comment]
I will set up a Navidrome server on my Desk to test Ampfery with it soon.

**Comment by argus-core** [comment]
Thanks! Do you want me to create a separate issue for the self-signed certificate?

**Comment by BLeeEZ** [comment]
Yes I think a separate issue helps tracking them.

**Comment by argus-core** [comment]
New issue created: https://github.com/BLeeEZ/amperfy/issues/18

**Comment by BLeeEZ** [comment]
I was able to reproduce your issue.
The issue is related to the ids of artists/albums/songs/playlists received from the subsonic API.
In Ampache and all other Subsonic API supporting server variants, i have seen so far, ids are integers.
Navidrome sends very big hexadecimal value as ids (they look like hash values).

I am currently working on a patch for Amperfy to switch ids from integers to strings.
With that Navidrome should be supported.

**Comment by argus-core** [comment]
Thanks for the quick turnaround!

**Comment by BLeeEZ** [comment]
Navidrome is supported with this aa1fbf2effef506d73a40257d6714a42eaaccfea commit.
With the upcoming Amperfy App Store version you can access your Navidrome server.

**Comment by BLeeEZ** [comment]
Version 1.0.3 has been released on the App Store.
Navidrome should now be supported.
Can you confirm this?

**Comment by argus-core** [comment]
Confirmed. With the new version I can connect to my Navidrome instance, sync the library and play songs. I can also (most likely [1]) download them. I would consider this issue solved, thanks!

[1] Songs are added to download queue and disappear over time but I don't see a way to check which songs have been downloaded. I see "cached songs" under Library Settings and the count corresponds to the downloaded album size.

**Comment by BLeeEZ** [comment]
Nice to hear. Cached songs have a blue artist name. In the search tab or under library songs you can select to search only for cached songs.
