### ISSUE TITLE
Automatically resume playback after it has been interrupted 

### ISSUE THREAD

**Issue by mediadev123** [BLeeEZ/amperfy#171]
When the playback gets interrupted from a call, video or any other app that starts playback audio, amperfy doesn't automatically resume playback, unlike many other music apps. 
It would be great if amperfy could mirror other apps in that regard.

**Comment by BLeeEZ** [comment]
I agree, added to the feature list.

**Comment by john8329** [comment]
Yup, having this issue too. It'd be nice if it resumed like all other music apps do. This is currently my favourite OSS player, and I'm gonna donate for it by the way.

**Comment by BLeeEZ** [comment]
I currently have not much time for this hobby development but this feature is on top of the feature list.
@john8329 Thank you very much

**Comment by BLeeEZ** [comment]
The bug is fixed with this commit: b742256

**Comment by BLeeEZ** [comment]
This bug fix can be tested in the latest beta: https://github.com/BLeeEZ/amperfy/issues/25
