### ISSUE TITLE
[Feature request] Allow different playback speeds

### ISSUE THREAD

**Issue by benjaminbhollon** [BLeeEZ/amperfy#178]
I'd love to be able to use this for my podcasts as well as my music, but I listen to all my podcasts at 1.5x speed, so this doesn't really work for that. Would it be possible to get an update allowing different playback speeds? Thanks!

**Comment by yugonline** [comment]
+1 it seems there's no inbuilt way in iOS to modify playback speed at an audio driver level. So this feature would really be necessary until an alternative is found

**Comment by buchankn** [comment]
+1 I also listen to a lot of audio books at 1.5x speed, so I'd love to see this implemented as well!

Looking through the code and Apple documentation, it looks like the BackendAudioPlayer uses an AVPlayer, which has a rate variable to control playback speed, so it seems like it should be do-able, with a UI update. I'd work on implementing it myself, but I don't have a mac for development...

**Comment by yugonline** [comment]
@buchankn i do. But my swift coding is meh at best. Can you point me to relevant code files to look into? I'll try to work on this over the next weekend (not the one coming up the one after)

**Comment by BLeeEZ** [comment]
Feature is implemented in 8ce9c00 and can be tested in the next beta version.
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-12-08 at 20 56 19](https://github.com/BLeeEZ/amperfy/assets/17556018/a26d033d-1a50-4b3f-9657-b472af6a0c53)

**Comment by benjaminbhollon** [comment]
Oh, fantastic!
