### ISSUE TITLE
[Request] Total play time in music player

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#181]
Please consider showing total play time in the music player. It's important to know how long your list is going to be playing.

On a tangent, please consider adding track length to the tracks in music player as per  https://github.com/BLeeEZ/amperfy/issues/126#issuecomment-1137675369

If you don't want to add them to browsing that's fine, but at least get us some control in the music player where extra information is not cluttering up the main interface.

**Comment by bbsixzz** [comment]
Now that https://github.com/BLeeEZ/amperfy/commit/29dbe6b15ba1ef6fa702e11fedc5bc9c63c787c5 is being added would you please consider showing total play time in the music player as well? At least as an option.

It's dearly missed info, especially when having added a bunch of tracks for a trip without knowing the duration.

**Comment by BLeeEZ** [comment]
I currently don’t know where to display this information. Do you have a suggestion?

**Comment by bbsixzz** [comment]
I think it would work fine at the bottom.

If you need to know just scroll to the bottom, no need to show it anywhere else all the time.

![IMG_8529](https://github.com/BLeeEZ/amperfy/assets/47334163/8830b99f-95e7-473e-931f-16a226b13586)

**Comment by BLeeEZ** [comment]
This feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25

**Comment by BLeeEZ** [comment]
The blinking comes from the live update. If the song is paused the blinking stops.
