### ISSUE TITLE
Library not updating

### ISSUE THREAD

**Issue by RoaldNL** [BLeeEZ/amperfy#183]
After adding music to Navidrome it does not show in Amperfy. The only solution I found so far is to reinstall the app. Is there a way to refresh the library from the server without reinstalling the app?

**Comment by BLeeEZ** [comment]
No there is currently no other way to update the library. New elements should be appearing in „recent songs„.

**Comment by BLeeEZ** [comment]
With c49edc3 library reset and resync is possible without reinstalling Amperfy. The option can be found under Settings->Library->"Resync Library".

**Comment by BLeeEZ** [comment]
This feature can be tested in the latest beta: https://github.com/BLeeEZ/amperfy/issues/25
