### ISSUE TITLE
[Bug] Artists disappearing and crash

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#185]
1.1.3 Build 1

Searching artist 808 State makes it disappear from results after tap. Also disappears from Library > Artists.

Searching album and playing track by 808 State is no problem. Tapping the artist from playback view finds the artist.

App crashes to springboard shortly after.

This happens to some other artists as well.

I've tried resyncing library and deleting app to no avail.

https://www.dropbox.com/s/zrfbw10xp54l1aa/RPReplay_Final1680747570.mp4?dl=0

**Comment by bbsixzz** [comment]
This is still happening, do you have any idea how to fix it?

https://www.dropbox.com/scl/fi/nrrycoewterhaofvzku7a/crash.MP4?rlkey=v5ykjdts4oe5c2p4yblufqbuw&dl=0

Cheers

**Comment by BLeeEZ** [comment]
Fixed with be663dc24439d60c5eab9ca4999568e5d31024fb.

**Comment by BLeeEZ** [comment]
This bugfix can be tested in v1.1.5 (2). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25
