### ISSUE TITLE
[Bug] Crash when downloading large wav files

### ISSUE THREAD

**Issue by peterNordin** [BLeeEZ/amperfy#186]
I have run in to some trouble when trying to play album discs consisting of large wav music files.
Version 1.1.2, Build Number 3

I have several albums in uncompressed wav format, these contains multiple song in one file each with a size between 30 - 50 Megabytes. Some of the albums also contain an additional continuous DJ mix of all the tracks on the disc, ranging in size between approximately 500 and 700 Megabytes. 

I browse these albums in “Directories” mode, and when I start playing from the start (track 1) the automatic download caching feature seems to work as intended, each track and the next few tracks are automatically downloaded and cached.

The large DJ mix files are always listed as the last track (due to filename), and when the automatic download function reaches that large track the application will eventually crash during the download.
The same happens if I manually trigger the download for that track.
For some DJ mixes the download succeeds. I believe that files closer to 500 MB succeeds while larger ones closer to 700 MB fail. I download using WiFi so transfer speed should be quite high.

After the application has crashed in this way and been restarted any one of the following odd behaviors  may occur, I have not been able to find a way to reproduce them reliably though.

- It is possible to play and download the other files in the directory that crashed, but the app will not try to re-download the large file that previously crashed. (this is the best case)
- If the lower sized files (each individual track) were previously “not downloaded”, they are now no longer possible to download. They can be played, and the app downloads them as needed, but the do not stay cached. This only affects the directory where where the crash occurred, other directories still work as expected.
- Trying to play any track in the directory that crashed leads to the app crashing again, regardless if the track was downloaded or not. But tracks in other directories can be played and downloaded without problems. 
- Sometimes a mix of the problems listed above occurs.

Clearing the cache sometimes resolves some of these odd issues, but sometimes I need to reinstall the app completely to resync the library (I saw that a built-in resync library feature is coming in the next version).

I don’t know if it matters, but I am using airsonic-advanced as the server, and I have verified that the download seems to work using some other clients, though they seems to “cheat” and requests transcoded mp3 from the server. So download size is smaller in those cases.

**Comment by BLeeEZ** [comment]
I can confirm that the app can crash with very big audio files. After downloading the file, it gets loaded to be saved in the database. It depends on your iOS device how large your available RAM is. The problem here is that a simple memory overflow occurs and the app gets killed by the OS. What iOS device are you using?

**Comment by peterNordin** [comment]
Yes you are right. Its an old iPhone 8, and I looked up the specs, only 2 GB RAM, so I guess its a device limitation in this case. It make sense for a 700 MB file to cause problems, its almost half the RAM size. 
You can close this issue then as it is not a bug in the application.
