### ISSUE TITLE
[Feature request] Disable screen lock

### ISSUE THREAD

**Issue by JOJ0** [BLeeEZ/amperfy#189]
When downloading larger amounts of files it would help if amperfy would prevent screen locking since I think downloading in the background doesnt seem to work / stops at some point. At least on ios it's what I experience with a lot of apps. A config option would be nice to let users choose whether amperfy prevents locking or not.

Do you think it's doable? I recently saw this feature in another subsonic client on ios. Not sure which language/framework it is written in though...

**Comment by Jaffex** [comment]
I second this request - I use my phone for playing music in my car (i don't have carplay) and it'd be great if amperfy would prevent locking the screen so I can always see album art and media controls without tapping the screen.

It may make sense to create a setting like this:

Prevent Screen Lock
- Never
- When connected to charger
- Always

**Comment by JOJ0** [comment]
@Jaffex thanks for seconding! My main usecase is that I'm never able to finish my downloads because screen locks before that. How are you managing this issue when caching stuff for a car ride?

**Comment by Jaffex** [comment]
I didn't cache the entire library yet, so when a song plays that is not cached yet, I stream it via mobile data.

**Comment by JOJ0** [comment]
Ok I understand. I use it differently. I only stream at home and I dont have my subsonic compatible server facing the internet. Only offline mode when on the go / in the car. Thus making huge amounts of playlists available offline is a key feature of a subsonic client.

You said "whole library", that wouldnt even fit on my 64GB phone, haha ;-)

**Comment by JOJ0** [comment]
@BLeeEZ what's your thoughts on a feature like this? Since it's a FOSS project I wouldnt consider anything really soon now. Do you think it's useful and what are your next goals in the project?

**Comment by JOJ0** [comment]
Hi @BLeeEZ, thanks for the response. Yeah I get that, maintaining and at the same time coding new features in a FOSS project eats up a lot of time and often even is a "one person show". Unfortunately no iOS/Swift programmer, just Python-dev but currently also taking a "summer break" from the projects I'm involved with :-) 

I'm not sure what iOS download session is, I guess it is a Swift feature? 

From what I can say from my usages of iPhones and not only this app but other apps (even the Spotify app): I'm really not sure if it really "stays up" in background forever. I have the feeling that at some point the app / the phone gets to sleep and massive download sessions always end up dead. The only way, very often, is to keep the screen running, thus the app in the foreground. Sorry for not being technical here, I will try to tail my Navidrome server logs and make some definitive statements about if I see that transcoding/downloading stops if my desplay turns black.

One more thing to report which fits into this feature request is that I can definitely say, because I have just watched my navidrome containers log and  can repro it definitely is:

"Download all artwork" stops like 1-2 minutes after my screen locks - if I unlock the phone again I suddenly see that downloads in my containers log are continuing. It certainly might be that you coded this feature differently and it does not use "iOS download session" and thus this is expected.

**Comment by BLeeEZ** [comment]
This feature is implement via 19a06ec:
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-12-10 at 22 06 44](https://github.com/BLeeEZ/amperfy/assets/17556018/86bec2f4-b234-4b8e-91b8-b505060ed3ef)

**Comment by JOJ0** [comment]
Awesome news @BLeeEZ , let me no if you publish a testflight release. I'll test it and report back my experience. HTH

**Comment by JOJ0** [comment]
Hi @BLeeEZ did this make it into 1.1.4? Thanks!

**Comment by BLeeEZ** [comment]
Hi, this feature will be available in v1.1.5.

**Comment by BLeeEZ** [comment]
This feature can be tested in v1.1.5 (2). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25

**Comment by JOJ0** [comment]
Thanks so much! Sorry for not reporting back! Works flawlessly on my iphone13 mini!
