### ISSUE TITLE
Album track order?

### ISSUE THREAD

**Issue by PaulWalkerUK** [BLeeEZ/amperfy#19]
I might be missing something, but when viewing an album, it appears that tracks are listed alphabetically (by track title). Is there a way to get them listed by track number order?

**Comment by BLeeEZ** [comment]
Yes, you are right. The songs in an album are sorted alphabetically. It should sorted by track number if provided. I will fix it.

**Comment by BLeeEZ** [comment]
With this commit 7f0dcd1c983757e46b37fc65b8cc59cd614acd7e album songs are sorted by track number
