### ISSUE TITLE
Displaying artists / Album rtists

### ISSUE THREAD

**Issue by pierrec18** [BLeeEZ/amperfy#190]
Hi

Thanks for your very cool app. I have a question about the list of artists displayed in the artist view.
In this view I see the equivalent of Album Artist and not just Artist.
I see the issue: https://github.com/BLeeEZ/amperfy/issues/155 and when I try REST request with getArtists, I get the list of Artist and not ArtistAlbum (and this is what I want 😅)

So I don't really understand why I see a list of ArtistAlbum in the Artist view of your app.

I hope my question is clear

**Comment by BLeeEZ** [comment]
Done in 5fcaa1b1acf41f309e918bd9473fc4ce4b1ea494.
