### ISSUE TITLE
[Feature Request] Automatically switch quality when on WiFi and Mobile Data

### ISSUE THREAD

**Issue by Sakooooo** [BLeeEZ/amperfy#193]
I would like to use my subsonic server outside of my home but since mobile data plans are limited it would be nice if there was an option for automatically switching quality
this is the one missing feature that is not letting me switch from iSub

**Comment by BLeeEZ** [comment]
Implemented in a11ebe96da98603127bb0004908fd5c618a306cc.
![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-22 at 21 03 21](https://github.com/BLeeEZ/amperfy/assets/17556018/9e18760f-1aaf-42cc-a9ce-f53b5848d499)

**Comment by Sakooooo** [comment]
yay thanks :DDDD
