### ISSUE TITLE
[feature request]. Allow sorting by length.

### ISSUE THREAD

**Issue by cocoonkid** [BLeeEZ/amperfy#196]
[feature request]. Allow sorting by length.

Awesome player!  Absolutely great product. just WorksTM

But it would really be great if I could sort by track length.  Basically a really important feature in my humble opinion!

Thanks so much for your consideration!

**Comment by BLeeEZ** [comment]
This feature can be tested in v1.1.5 (2). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25
