### ISSUE TITLE
Precise timeline navigation controls in the music player view

### ISSUE THREAD

**Issue by alexander-nf** [BLeeEZ/amperfy#198]
I'd like to have controls to skip time intervals forward and back in the music player view.

It is useful for listening long audiobooks, meeting/seminar records, live concert tracks, language lessons and so on. I pretty often:
-  navigate back to listen some phrases/parts again (reasons: haven't got an idea/explanation, speaker has lowered his/her voice, train passed by, loud environment, track without normalization, the passage/sentence/interlude was cool, etc),
- or skip forward to listen incrementally and look for a next point of my interest.

Skipping is very convenient not only from the content consumption position but also from a physical, real life actions point of view:
- it is quite difficult to drag player cursor precisely on a narrow screen / in a compact UI for the hour(s) long duration track,
- it adds safety while the listener is going/moving (walking/running/riding/driving), no need to refocus cognitively on the phone screen and to drag the cursor patiently with micro movements.

I haven't found related discussion in "Issues", there are my thoughts:
- `[Feature request]` Some switch or setting could be implemented in the app to swap _tracks seeking panel_ and _a track navigation panel_ of the music player view.
- `[Help/Wiki/FAQ request]` I should somehow rethink the case as my personal issue and use _the podcast view_ (which has such a navigation controls) to navigate playback of long tracks. But I haven't found how to save audio files as podcasts on a streaming server**s**. I've tried to do this and searched information about subsonic servers, it looks the only option to load podcast is somehow via XML RSS feed.
So at the moment I cannot utilize the podcast player view in order to achieve presice timeline navigation and skipping.

**Q: How to skip time intervals forward and back in the music player as it's implemented in the podcast view?**

**Comment by BLeeEZ** [comment]
This feature can be tested in v1.1.5 (2). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25

**Comment by BLeeEZ** [comment]
I added an option to display the skip forward/backward in music player too.
