### ISSUE TITLE
Can play downloaded songs, not undownloaded ones. (transcoding)

### ISSUE THREAD

**Issue by johnruck** [BLeeEZ/amperfy#199]
I will note upfront this might be related to [#159 ](https://github.com/BLeeEZ/amperfy/issues/159) as I am also using .flac files.

This is with the latest IOS client (1.1.3 Build 1) and with Ampache 6.0.2.

I am able to successfully download playlists and then amperfy will play any of those without issue, but if I go directly to an undownloaded track and tell it to play it will eventually show the artwork for the song, but the player stays at showing 0 seconds into the song and 0 seconds left in the song with no audio being produced.

This state confuses me as it is able to download via the playlist download as well as it knows the songs are there on the server as it lists them in the inventory to allow telling it to play, so I am confused if this related so need to transcode the flac files maybe? (Actually I just tried it with an .mp3 file with the same result so it seems to not be transcoding related).

So I guess my question is whether the download playlist request is getting a valid url while straight url from the catalog is incorrect?  As Ampache is doing it all via web calls its not like there is a blocked port or firewall issue involved between the two paths.

Any ideas on things I can test?  Note that I have only been using Amperfy for a few months at this point, but this behavior has been consistent over that timeframe.  (And before you suggest downloading the entire catalog, it is bigger than my phone's storage so that is not an option).

**Comment by BLeeEZ** [comment]
Transcoding is now implemented. This should fix the issue with iOS unsupported file types like flac.

**Comment by BLeeEZ** [comment]
This feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25

**Comment by BLeeEZ** [comment]
Did you have time test the feature? Is it behaving as you expected?
