### ISSUE TITLE
call for any API / change requests to make things easier for you.

### ISSUE THREAD

**Issue by lachlan-00** [BLeeEZ/amperfy#2]
I'm making a call out to all the xml-api client software devs to come over the the repo and make their issues known.

I'm working on updating Ampache to version 4 and would like feedback on those who use the API to actually tell me what they need to make it better.

So far i've added smart playlists to the playlist calls as well as recording/flagging songs.

Please come by when you can and I hope to make all ampache-related software better for everyone! :)

**Comment by BLeeEZ** [comment]
Currently im feeling fine with the ampache XML API.
If I feel the need for new functionality, I will raise my hand.
