### ISSUE TITLE
Short songs are not scrobbled

### ISSUE THREAD

**Issue by jan666** [BLeeEZ/amperfy#200]
Hello,

I'm using Amperfy 1.1.3 on my iPad and short songs (e. g. track 1 of https://unclem.bandcamp.com/album/kmpfsprt) are not scrobbled. When I play it via navidrome webinterface it gets scrobbled.

I guess you implemented a limit for the tracks size. Could you remove that limitation or make it a setting to ignore the limit?

**Comment by BLeeEZ** [comment]
Hi,
should be solved with: 1ca8e76

**Comment by jan666** [comment]
Works with latest AppStore version. Thanks!

**Comment by jan666** [comment]
Hm, I noticed now I get multiple scrobbles for the same song when I pause and continue the song. Could this be related?
