### ISSUE TITLE
Enable more robust Siri support with CarPlay

### ISSUE THREAD

**Issue by yllekz** [BLeeEZ/amperfy#203]
Hello, I have been enjoying this app's CarPlay integration, especially compared to other AirSonic apps.

I did notice however that when I was trying to use the app with only my voice, Siri reported back that Amperfy didn't have integration with advanced/specific voice commands for selecting/starting songs/playlists/etc.

Is this on the roadmap by any chance? It would be nice to control this app via voice more often than using the touch screen.

**Comment by BLeeEZ** [comment]
Hi,
voice commands are now implemented with 2ce18ebf8e64886c31ee22b3ac6c201760618985.
It can be tested in the upcoming beta version v.1.1.5
Supported are the usual voice commands like:
- "play song \<title\> by \<artist\>"
- "play song \< title\>"
- "play album \< title\>"
- "play artist \< title\>"
- "play \<Rock\>"
- "play playlist \< title\>"
- "play podcast \< title\>"
- all above command but replace "play" with "shuffle"
- provided repeated information in the command is supported too

**Comment by rhauff1** [comment]
I'm also looking forward to this.  Just installed Amperfy as I'm looking for a player with Siri support.
Hope v.1.1.5 releases soon!

**Comment by BLeeEZ** [comment]
This feature can be tested in v1.1.5 (2). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25

**Comment by rhauff1** [comment]
Awesome, testing now!  Have not tried TestFlight beforeOn Jan 25, 2024, at 11:27 AM, Maximilian Bauer ***@***.***> wrote:﻿
This feature can be tested in v1.1.5 (2). It is now available as Beta via TestFlight: #25
