### ISSUE TITLE
Playback control

### ISSUE THREAD

**Issue by bmp** [BLeeEZ/amperfy#207]
It would be great if there was an option,
1. Speed up listening speed (1x,1.5x,2x, etc. based on the user's input).
2. Would it be possible to dynamically shortens silences in podcasts ala Overcast? It really helps when listening to a tonne of podcatsts
3. Also, an equalizer setting would be great, some podcasts have only speech, but nowadays, the rise in production quality has also meant lots of background music, etc. As I listen to podcasts when I am in commute or while in transit, I change the equalizer settings (used to it from other applications) to ensure the voice comes through.

**Comment by BLeeEZ** [comment]
Playback rate is implemented in 8ce9c00:
![Simulator Screen Shot - iPhone 14 - 2024-01-01 at 12 24 28](https://github.com/BLeeEZ/amperfy/assets/17556018/33a1681f-7840-45d0-87d0-7cb38d928482)

**Comment by bmp** [comment]
@BLeeEZ Has this made it to the App Store? The last update on the appstore is from 8 months ago. Here are the screenshots for me,

**Version History from the App Store**
![amperfy_version](https://github.com/BLeeEZ/amperfy/assets/1095177/8f22ba19-4159-4fc7-8422-d46d2c4a38d8)

**Screenshot from playing the podcast**
![amperfy_podcasts](https://github.com/BLeeEZ/amperfy/assets/1095177/0af2211c-b44a-46fa-b156-38c00c200735)

**Comment by BLeeEZ** [comment]
You are right. In AppStore is version v1.1.3. You can install v1.1.4 via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25
Version v1.1.4 fill soon be published to official AppStore. The playback rate feature will then be available in v1.1.5 which can then be tested via TestFlight.

**Comment by bmp** [comment]
@BLeeEZ Thank you for the clarification, I am on 1.1.4 on Testflight now. Will look forward to 1.1.4 soon!

**Comment by BLeeEZ** [comment]
The only way to test feature now is to build Amperfy by your own. If you don't own a Mac you need to wait till v1.1.5 is on TestFlight.

**Comment by BLeeEZ** [comment]
This feature can be tested in v1.1.5 (2). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25
