### ISSUE TITLE
[Feature] Include favourite status in track list row.

### ISSUE THREAD

**Issue by Karta775** [BLeeEZ/amperfy#208]
I really like the app but something I miss from Spotify is favourite status. It would be great to have the ability to see at a glance which songs in my library, search results, or in an album are favourited. 

I made a mockup of what I mean:
<img src="https://github.com/BLeeEZ/amperfy/assets/83785288/12b09cff-3e7a-4943-813a-3c38383da0d5" width=35% height=50%>

I poked around the code a bit and saw that track duration has been added to the track list row at the trailing edge where I placed the favourite indicator. Since duration will be toggleable, could this also be toggleable? Or allow the user to choose between duration & favourite status with a picker?

The "Favourite Songs" list should probably not contain favourite indicators since it's redundant there.

Thanks, this is truly the best way to use Navidrome on iOS :)

**Comment by BLeeEZ** [comment]
I think this is a great feature. I need to find a solution, as you mentioned, how to handle duration and "is favourite" icon. Mutual exclusivity or display both. This needs to be tested.
Should this be possible only for songs or for albums/artists too?

**Comment by Karta775** [comment]
I hadn't thought about albums and artists, but that would be great too!

**Comment by BLeeEZ** [comment]
What do you think about this approach? This is the way Apples Music App displays favourite songs.
<img width="395" alt="Bildschirmfoto 2024-01-11 um 12 12 31" src="https://github.com/BLeeEZ/amperfy/assets/17556018/3ea53172-9b6e-43ad-8fbb-b6d9fe671150">

**Comment by Karta775** [comment]
That looks great!

**Comment by BLeeEZ** [comment]
This feature can be tested in v1.1.5 (2). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25

**Comment by Karta775** [comment]
I've installed the latest beta and it's perfect. Thanks again :)
