### ISSUE TITLE
XML parsing error when trying to access navidrome thats behind authelia

### ISSUE THREAD

**Issue by haitispaceagency** [BLeeEZ/amperfy#210]
I use Amperfy to access a instance of Navidrome on my home server, that is reverse-proxied to a VPS via nginx. I recently tried to put that behind an instance of Authelia for 2FA and I am getting "XML Parsing error"

Are these things just not compatible, or should I disable password requirements on Navidrome or something? Everything works through the native web player just fine.

   
![Amperfy](https://github.com/BLeeEZ/amperfy/assets/126473500/1ed38db2-d93b-4814-b517-527899073294)

**Comment by BLeeEZ** [comment]
It seems like you are able to access your server via Amperfy otherwise there would be no albums.
When does this error occur?

**Comment by haitispaceagency** [comment]
The error pops up anew every time I click a song to play. I’m pretty sure it throws the error upon first opening the app as well. 
 
I’ve put my old configuration in place for now, but kept a copy of the one throwing this error for further testing if you need more info.
