### ISSUE TITLE
[Feature] Show Favorite status in main player view

### ISSUE THREAD

**Issue by rhauff1** [BLeeEZ/amperfy#215]
While listening to music I like to mark songs favorite or unfavorite as I add new music or tastes change.  As it is, I end up clicking the 3 dot menu on nearly every song to check.
Could the favorite status be shown on the main player page?  A toggleable heart would be nicest, maybe a solid red heart to indicate favorite and a white outline heart to show it is Not marked.
Thanks!

**Comment by BLeeEZ** [comment]
This sounds good. I will add it to upcoming features.

**Comment by michaelkrieger** [comment]
Would love this added to the CarPlay interface.  A favourite or rating (1-5 star) would be helpful for listening to music and being all “I want to hear this song again”.  At the best least the toggle heart for songs I like.

**Comment by BLeeEZ** [comment]
CarPlay is very limited in respect of of customizability. It is currently possible to show only the favorite ones. 
@michaelkrieger did you test the current beta? There I added support for favorite star in the remote control center.

**Comment by michaelkrieger** [comment]
> I added support for favorite star in the remote control center.
I’m just moving to the TestFlight chain this morning so will check it out. That’s the feature I was hopeful for :)
Thank you for this amazing work.

**Comment by michaelkrieger** [comment]
> I added support for favorite star in the remote control center.
I don’t show a favourite icon in the latest testflight.  By comparison, I also show Apple Music which does have one


![IMG_7383](https://github.com/BLeeEZ/amperfy/assets/7321259/705e5eb6-2c7e-4769-a353-ef589fda55cc)
![IMG_7384](https://github.com/BLeeEZ/amperfy/assets/7321259/069de64d-72ff-4ecb-932e-cf5f4da6969a)

**Comment by BLeeEZ** [comment]
I implemented it in e36c5603321c4e741a39b428fbbd3a8ea9384a1b.
<img width="698" alt="Bildschirmfoto 2024-04-14 um 20 22 10" src="https://github.com/BLeeEZ/amperfy/assets/17556018/967c4e92-6a2d-498d-bb6e-c2c8ca82049a">

**Comment by BLeeEZ** [comment]
The favourite button on CarPlay can be tested via TestFlight in version 1.2.0 (3).
