### ISSUE TITLE
Scrobbling doesn't seem to work in 1.1.5

### ISSUE THREAD

**Issue by Jaffex** [BLeeEZ/amperfy#218]
I installed the testflight version 1.1.5, but scrobbling does not seem to work there at all.

None of the songs I listen to get added to my last.fm profile.

I tried deleting the cache as well as logging out and back into my server, but songs still do not get scrobbled.

**Comment by BLeeEZ** [comment]
See https://github.com/BLeeEZ/amperfy/issues/217 for answer. I close this issue since from my point of view it is an issue of Navidrome.
