### ISSUE TITLE
[Feature Request] Sort songs by recency

### ISSUE THREAD

**Issue by D3viloper** [BLeeEZ/amperfy#219]
Hey,
I really love the player!

Would it be possible to sort all songs like the recent songs tab? Since the tab is very limited, it would be much easier to find newly added songs after some time.

Best wishes!

**Comment by BLeeEZ** [comment]
Hi, this is not possible. Recently added is not only a  sort mechanism but a filter too. The api doesn’t tell me when the album has been added to library on server. I need to fetch the recent albums and give them a order. The only thing I can do is to add the other sorting options to „recently added“ too.

**Comment by BLeeEZ** [comment]
I am currently reworking the complete "recently added" system. At this point this issue is a duplicate to https://github.com/BLeeEZ/amperfy/issues/172. Please provide additional input there.
