### ISSUE TITLE
Support for genre

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#22]
Genre is currently not supported in either the library view or search, I think adding it would be a great improvement.

**Comment by sandersantema** [comment]
On an somewhat unrelated note (but not wanting to clutter your issue tracker) I do understand this app is probably somewhat of a one man show and implementing any of these features (if they're implemented at all) would take some time. But I found the app to be very performative (especially compared to play:Sub and AVSub) and I thought posting some thoughts on potential improvements could therefore be valuable.

**Comment by BLeeEZ** [comment]
Feature requests and bug reports are always welcome. I was thinking about this feature too. Genres are supported on Ampache API since version 5.0. My implementation supports version 3.4. I am also interested in this use case so think this feature will come sooner than later.

**Comment by sandersantema** [comment]
In the meantime if a workaround is desired smart playlist could be used as a replacement for genres.

**Comment by sandersantema** [comment]
I suppose this can be closed given https://github.com/BLeeEZ/amperfy/commit/9c347df4a12d0453623b713baacc13144e82a6a9 ?

**Comment by BLeeEZ** [comment]
Yes you are right. With v1.0.5 genre is supported and automatically synced in the background.
