### ISSUE TITLE
Carplay Voice Control errors

### ISSUE THREAD

**Issue by lkernan** [BLeeEZ/amperfy#225]
I use Amperfy with Carplay to listen to music in my car and the voice control is great, but errors out sometimes.   

Asking Siri to "Play Music" or "Play All Songs" returns "An error has occurred in Amperfy" and nothing plays.
If I include a track or artist name such as "Play Track (trackname)" or "Play (artistname)" it works fine.  

I've deleted the Apple Music app off my iPhone so Amperfy is the default for Siri.   

Amperfy in Carplay has a menu option to play all the songs randomly, that's what I'd expect a generic "Play Music" to do.

**Comment by BLeeEZ** [comment]
Thank you for the report.
I will take a look at it.

**Comment by BLeeEZ** [comment]
"Play Music" is now working with this fix: 5be9976

**Comment by BLeeEZ** [comment]
This feature can be tested in v1.2.0 (1). It is now available as Beta via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25

**Comment by lkernan** [comment]
Thanks, i've tested it a few times and it works great!
Now I can jump in the car, press the voice button and say "Play music" without having to think about artists or albums.
