### ISSUE TITLE
Music stops when app is minimized on IPad

### ISSUE THREAD

**Issue by JanM802** [BLeeEZ/amperfy#228]
Upon first using the app on the iPad, I noticed that the music always pauses when I minimize the app. Background refresh is turned on, and the Battery Saver is turned off. I´m using IPad OS 17.4

**Comment by BLeeEZ** [comment]
Is this issue still occurring in version 1.2.0?

**Comment by BLeeEZ** [comment]
I was able to reproduce and fixed it with 3105ff67fb952b91449e5889952393a43ea3a610.
A quick fix should be to force close the App and reopen. Then the background playback should work again.

**Comment by BLeeEZ** [comment]
This bug fix can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25

**Comment by JanM802** [comment]
Hello, 
sorry for the late response. Now everything works out perfectly.
Thank you very much.
