### ISSUE TITLE
Performance: queuing a big playlist blocks the app

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#23]
When queuing a big playlist the gui of the app gets blocked, I suspect this is because the whole playlist gets added to the queue at once. I don't know how hard/ easy this would be but a solution I could think of is queuing lazily, since the results aren't actually needed until:

- the user looks/ scrolls to the part of the queue
- the unloaded part of the queue is next to be played

Although this might also be solved by changing the queuing code to be non-blocking.

**Comment by BLeeEZ** [comment]
These are really good improvements. I will take at look at both in detail. The second point should be no problem to realize. I think an asynchronous  playlist append is nevertheless unavoidable.

**Comment by BLeeEZ** [comment]
With this commit f2c3fb0515ac02af4dc581043c81fdd84c794814 the performance is greatly improved. The main issue was that after every song append a context save (write to database) has been performed. With this fix only one context save after all songs is performed.

**Comment by BLeeEZ** [comment]
Can this ticket be closed?

**Comment by sandersantema** [comment]
Queuing a playlist with 2455 songs (smart playlist of my whole library) is instant! So I believe this is solved.
