### ISSUE TITLE
Artwork for Artist

### ISSUE THREAD

**Issue by seantdavidson** [BLeeEZ/amperfy#230]
Thanks for a very nice looking app. Not sure if I am missing something but when I pull up the Artist section I don’t have any artwork for the Artist. The app does pull up artwork for the albums but not Artists. 

Not sure if I need to do something different in my tags or the Navidrome server I am connecting Amperfy to.

**Comment by markesss** [comment]
I’m connecting to a Gonic backend, album and artist artwork come through to Amperfy, so it might be something specific to Navidrome.

**Comment by seantdavidson** [comment]
Thanks I will update that and post back results.

**Comment by seantdavidson** [comment]
@3zero2 thanks for the info. I updated my Navidrome docker container and the artist artwork is now showing. Updated my notes for future if I rebuild the container from scratch.

**Comment by Batwam** [comment]
I have save a file called artist.jpg into each of my artist folders and they are all showing in Amperfy. No Spotify integration needed here.

**Comment by mkayontour** [comment]
Hi, I need to reopen the issue. I'm not sure what's the issue on my side. As the previous comments states, the artist.jpg in the folder should be good enough. 

Many artists are working, the cache of artworks said there are all artworks downloaded. On navidrome I can see artists pictures but not in the app. 

I've checked if the filesize of the artist.jpg is the issue - I saw that every artist.jpg which is shown ist 120KB or less. 

So I downsized artist.jpg for death grips to 95KB, deleted the image cache from navidrome and restarted, and resynced the library. No luck. 

Can you give me some tips on how to debug it? 
The eventlog is showing nothing. 

Server Version: 1.16.1
Client Version: 1.13.0 
OS: Apple IOS 18.1.1
<img src="https://github.com/user-attachments/assets/27accbea-769d-4939-9d19-d220fda56b57" alt="Slice the Cake Navidrome" height="300">
<img src="https://github.com/user-attachments/assets/7ad05eda-7d28-4523-b512-135dee01ee95" alt="Slice the Cake App" height="400">

<img src="https://github.com/user-attachments/assets/1031dd50-e2d7-409e-a3a6-97c8a7f804e9" alt="Death Grips Navidrom" height="300">
<img src="https://github.com/user-attachments/assets/2e63249a-0d11-411d-a766-1387c1f8a6f6" alt="Death Grips App" height="400">

**Comment by mkayontour** [comment]
Sorry for Bothering, I deleted everything from database on the server. The container its running in and now the artwork is showing. 
For everyone else, reset the whole server and then it should do it without problem .
