### ISSUE TITLE
Shuffle Button Text Large

### ISSUE THREAD

**Issue by seantdavidson** [BLeeEZ/amperfy#232]
Due to me having Dynamic Text size set to a midway point the text on the library page flows out of the button. Just wanted to point out just in case you don’t use larger text like I do since I have bad eyesight. 
![Uploading IMG_2993.png…]()

**Comment by BLeeEZ** [comment]
Could you please reupload the provided image?
Is the shuffle font size big enough or is it necessary to increase this font size too?
How about the other labels and icons and buttons? Are they well displayed for you or are there any improvements needed.

**Comment by seantdavidson** [comment]
Hopefully this works and helps out. For Dynamic Text in iOS it is Setings -> Display & Brightness -> Text Size
![screenshot](https://github.com/BLeeEZ/amperfy/assets/36809456/6050ce65-dca7-4862-865d-42763a9725bf)

**Comment by BLeeEZ** [comment]
Thank you. I will fix that.

**Comment by BLeeEZ** [comment]
Is fixed with 17af81627ac800570459f20f7c4001b08c3fadf1.

**Comment by seantdavidson** [comment]
Thanks…I am using the current beta version so will test once the new one is released.

**Comment by BLeeEZ** [comment]
It can be tested in 1.2.0(2): https://github.com/BLeeEZ/amperfy/issues/25

**Comment by BLeeEZ** [comment]
Very interesting, tested it nearly every device.
Which device are you using?

**Comment by seantdavidson** [comment]
I am using an iPhone 14 Pro.

**Comment by BLeeEZ** [comment]
It should now be fixed with: 33a69ad3cb6b5cd450e7caf321fd05918ba9c4e2

**Comment by BLeeEZ** [comment]
It can be tested in 1.2.0 (3).

**Comment by seantdavidson** [comment]
Fixed. Looks great, thanks again.
