### ISSUE TITLE
iCloud backup fails with large Amperfy cache, cannot disable

### ISSUE THREAD

**Issue by jasonfish** [BLeeEZ/amperfy#235]
With Amperfy freshly installed, iCloud backup works.

After downloading a large playlist (>5GB), iCloud backup fails due to "not enough free space."

As Amperfy does not appear under _Apps Using iCloud_, it cannot be disabled, so one must choose between backing up their phone, or having pre-cached music.

Please have Amperfy announce itself as a iCloud backup entity so it can be excluded.

Update: I tried this with playSub and it does not repro. But playSub also does not appear in the iCloud list, so somehow its cache is being stored in a way that makes it invisible to, automatically excluded from, the backup process.

**Comment by BLeeEZ** [comment]
Hi,
Amperfy is not using iCloud, so it makes no sense to add it that list.
After some reading I found out that data stored on the file manger can be excluded from iCloud backups.
Amperfy stores all data in the local database. To exclude the cache a big refactoring would be needed.
The quick fix here is to delete the cache via Amperfy Settings->Library->"Delete Cache" and then do the iCloud backup.

**Comment by BLeeEZ** [comment]
This feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25

**Comment by BLeeEZ** [comment]
Did you have time test the feature? Is it behaving as you expected?
