### ISSUE TITLE
[Bug] Search missing correct results

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#236]
Search for the track **Tha** doesn't find it. The track is playing, so obviously it's in my library.

Amperfy 1.2.0
Navidrome v0.51.1

![IMG_9048](https://github.com/BLeeEZ/amperfy/assets/47334163/2578a075-4968-4d68-8d7d-3ca33d60f38c)

**Comment by bbsixzz** [comment]
Well it still seems like a very bad search result when I search for Tha and get anything but the track named Tha. 

It should be the top result in Songs, don't you think?

**Comment by bbsixzz** [comment]
Combining artist and track gives no results:

![image](https://github.com/BLeeEZ/amperfy/assets/47334163/0d23a40e-18cb-48a7-94dc-9c9075fbd2cb)

**Comment by BLeeEZ** [comment]
Artist name is ignored when searched for songs.

**Comment by BLeeEZ** [comment]
I will implement a fuzzy search for the search tab.

**Comment by BLeeEZ** [comment]
Implemented in 3713eba194e456a0777bb854ff43a4ccc99991e9 (Fuzzy and async search).

**Comment by BLeeEZ** [comment]
This feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25
