### ISSUE TITLE
[Feature request] Filter track artists or album artists

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#238]
Please add an option to the kebab menu to filter track artists or album artists.

![image](https://github.com/BLeeEZ/amperfy/assets/47334163/121e7ee7-5917-4629-ade7-20751cf1d547)

**Comment by BLeeEZ** [comment]
Can you please provide more info for this feature:
- What should be displayed?
- What are the properties to display the artist?

**Comment by bbsixzz** [comment]
I think what I meant to say is I want to exclude artist from albums with various artists like Navidrome does it.

I want it to look like this:

![IMG_9143](https://github.com/BLeeEZ/amperfy/assets/47334163/5afb1111-b66e-40b5-a46a-3c7109966944)

…instead of this:

![image](https://github.com/BLeeEZ/amperfy/assets/47334163/40d58b23-814e-43c2-b0b4-e45ac1285737)

If the album artist is different from song artist I want to exclude the song artist. This is a fast way of cutting down artists bloat while scrolling.

A bit of a niche feature for sure.

**Comment by PleaseStopAsking** [comment]
#190 #155 related requests

**Comment by Darksecond** [comment]
I'm also running into this problem, the artists list shows *all* artists, not just album artists like all my other subsonic clients do. I would very much like a toggle to only show album artists (basically the list you get back from the getArtists call)

**Comment by BLeeEZ** [comment]
Album artist filter is added (5fcaa1b1acf41f309e918bd9473fc4ce4b1ea494). I set it as default on.

![Simulator Screenshot - iPhone 15 - 2024-06-18 at 20 48 14](https://github.com/BLeeEZ/amperfy/assets/17556018/a48c69f7-6eaa-40d8-9865-75280bbd6217)

**Comment by NeuroDawg** [comment]
In which version is this implemented? I am running v1.2.1 build number 3 and all I see when I select sort when my artist list is open is "Name", "Rating", and "Duration". I'd like to use your app, but I only want to see album artists listed in my Artists tab.

**Comment by BLeeEZ** [comment]
Hi, this is implemented and available for developer builds. It will be available in the upcoming beta version 1.2.2 which you can install via TestFlight.

**Comment by NeuroDawg** [comment]
> Hi, this is implemented and available for developer builds. It will be available in the upcoming beta version 1.2.2 which you can install via TestFlight.

Perfect. Thank you for the reply.
