### ISSUE TITLE
Code Improvement: reduce code duplication using generics

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#24]
While looking trough the code I saw quite some functions which seemed to have roughly the same code but only differed in types, while I don't have any experience (other than looking trough this code :)) with swift I know from programming in C# that in the case of mostly the same functions but differing types I'd use generics. It seems that these exist in swift too: https://docs.swift.org/swift-book/LanguageGuide/Generics.html

Although functionally by changing these functions into generic ones there might not be any change I still think it would be a good idea with the whole `DRY` (`D`on't `R`epeat `Y`ourself) principle and all. Having less code means you need to maintain less. 

An example:
```swift
    private func playAllSongsInAlbum(album: Album) {
        guard let player = player else { return }
        player.cleanPlaylist()
        addAlbumSongsToPlaylist(album: album)
        player.play()
    }

    private func playAllSongsInPlaylist(playlist: Playlist) {
        guard let player = player else { return }
        player.cleanPlaylist()
        addPlaylistSongsToPlaylist(playlist: playlist)
        player.play()
    }

    private func addArtistSongsToPlaylist(artist: Artist) {
        guard let player = player else { return }
        player.addToPlaylist(songs: artist.songs)
    }
        
    private func addAlbumSongsToPlaylist(album: Album) {
        guard let player = player else { return }
        player.addToPlaylist(songs: album.songs)
    }
```

I think it would become something such as the following (although I'm not at all sure about the syntax/ whether this even compiles):

```swift
    private func addItemSongsToPlaylist<T>(item: T) {
        guard let player = player else { return }
        player.addToPlaylist(songs: item.songs)
    }
    
    private func playAllSongsInItem<T>(item: T) {
        guard let player = player else { return }
        player.cleanPlaylist()
        addItemSongsToPlaylist(item: item)
        player.play()
    }
```

If the behavior of the function is dependent on the type of the argument such as is the case in the following functions:
```swift
    func prepare(toWorkOnArtist artist: Artist?, with player: MusicPlayer) {
        self.artist = artist
        self.player = player
    }
    
    func prepare(toWorkOnAlbum album: Album?, with player: MusicPlayer) {
        self.album = album
        self.player = player
    }
    
    func prepare(toWorkOnPlaylist playlist: Playlist?, with player: MusicPlayer) {
        self.playlist = playlist
        self.player = player
    }
``` 

Then I think pattern matching on the types using a `switch` statement can be used (again not even sure whether this compiles):

```swift
func prepare<T>(toWorkOnItem item: T, with player: MusicPlayer) {
    switch item {
    case let artist as Artist:
        self.artist = artist
    case let album as Album:
        self.album = album
    case let playlist as Playlist:
        self.playlist = playlist
    }

    self.player = player
}
```

In general I think this would improve the overall quality of the code base. Although there might be some arguments against this which I have missed given my inexperience in regards to swift.

**Comment by BLeeEZ** [comment]
These are good points. I think I will implement an interface and use it in these scenarios.

**Comment by BLeeEZ** [comment]
The improvement is realized with this commit 8a2e3367aaf13d332eff8390897bae1b9609f1ad.

**Comment by BLeeEZ** [comment]
Can this ticket be closed?

**Comment by sandersantema** [comment]
Given that this was only a pointer and you've implemented generics this can be closed.
