### ISSUE TITLE
[Feature Request] Search Ability in CarPlay

### ISSUE THREAD

**Issue by seantdavidson** [BLeeEZ/amperfy#242]
Been using your app for a few months, one thing that would be great if there was a search ability for CarPlay.

**Comment by BLeeEZ** [comment]
As far as I understood the Apple CarPlay documentation, Search is only allowed/possible for Navigation Apps.
Have you tested the recent TestFlight version 1.2.0 (2)? There you have direct access to Siri to request media.

**Comment by seantdavidson** [comment]
@BLeeEZ thanks for this. I did not know it was only allowed for Navigation apps. The Siri option has not worked well at all. 

Maybe a listing of all artists. I know that may or may not be good as you go through a list. Right now I have been starting my listening via iPhone at a stop light or before I drive from my parking spot.

**Comment by BLeeEZ** [comment]
Regarding that I want to point to that discussion: https://github.com/BLeeEZ/amperfy/issues/140#issuecomment-1999339131

**Comment by seantdavidson** [comment]
@BLeeEZ thanks for this info.
