### ISSUE TITLE
Album and Artist lists empty in CarPlay

### ISSUE THREAD

**Issue by Batwam** [BLeeEZ/amperfy#243]
I have Navidrome set up and can see artists and album in the mobile app. I can play music and the song name /cover will show on CarPlay. However in Carplay, **both Artist and Album lists are completely empty** so I am unable to scroll to select an Album or Artist. All I can do is access is access the content of Favorites and Recently Added so that works at least.

I reset my library in Amperfy but it’s still the same.

Would anyone have any idea how to troubleshoot this?

**Comment by BLeeEZ** [comment]
Have you testes the recent TestFlight version 1.2.0 (2). There should CarPlay be fixed.

**Comment by Batwam** [comment]
Thanks for the quick response!

I have just installed the test flight version. I will test and revert back.

**Comment by BLeeEZ** [comment]
Regarding that I want to point to that discussion: https://github.com/BLeeEZ/amperfy/issues/140#issuecomment-1999339131

**Comment by Batwam** [comment]
Ok, I can confirm that I can search songs using Siri and now understand that the app never intended to display a full list of Artists/Albums.

I have some comments on the app but they as far as this issue is concerned, I believe that this is now clarified/closed.
