### ISSUE TITLE
Amperfy crashing roughly 50 seconds to 1 minute into any song

### ISSUE THREAD

**Issue by haitispaceagency** [BLeeEZ/amperfy#247]
Navidrome version 0.50.1
Amperfy version 1.1.5
iPhone 14 Pro Max iOS 17.3

I have hit shuffle many times and have found it to crash every single time after about 1 minute.  Does not matter if I am in offline mode or online. If I am using remote server or local address. If I am in airplane mode or on WiFi. If song is cached or not, it always crash after a certain amount of time. 

You can skip to :56 second mark of video to witness behavior of crash. 

https://github.com/BLeeEZ/amperfy/assets/126473500/162bdbfb-617a-45d3-840b-a60ac5ba5db9

**Comment by BLeeEZ** [comment]
Could you please tell me the background song sync percentage in Settings -> Library. I fixed a performance issue in the latest version v1.2.0. Could you please update and tell me if the crash still occurs.

**Comment by haitispaceagency** [comment]
Song sync is at 100%. 
I’ve update to 1.2 and it appears to be working fine now.
