### ISSUE TITLE
Album/Playlist doesn't start when triggered via shortcut when the app is totally clowned

### ISSUE THREAD

**Issue by TheMBeat** [BLeeEZ/amperfy#252]
If the App is opened in the background all works smooth. But when the app is closed the app opens the correct album/playlist but it doesn't start. 
I used a iPhone and nfc to trigger the shortcut.

**Comment by BLeeEZ** [comment]
I found the root cause and fixed it in cfd6adaca2230244054310455663d181878ca21c.

**Comment by BLeeEZ** [comment]
All shortcuts are now processed in background: 8d9486024b6899a22aa7482d4a41e113c73aa41e

**Comment by BLeeEZ** [comment]
This bug fix/feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25
