### ISSUE TITLE
Strange Siri search feedback in Carplay

### ISSUE THREAD

**Issue by Batwam** [BLeeEZ/amperfy#255]
I noticed that when doing a search using Carplay like "play Radiohead", the app will respond "Now playing Amperfy" which sounds strange. This feedback message also doesn't allow to make sure Siri understood what was requested.

Is there a way to change this so the response is "Now Playing [Radiohead]"?

**Comment by BLeeEZ** [comment]
All shortcuts are now processed in background. Siri responds now with the fetched MedaItem ("Now Playing [Radiohead]"): 8d9486024b6899a22aa7482d4a41e113c73aa41e

**Comment by Batwam** [comment]
Excellent, would it be possible to test this? When will it be released in test flight?

**Comment by yllekz** [comment]
Are there examples of accepted Siri commands? Earlier I used the "ask Siri to play music" button and when I named a playlist all I got was "sorry, a problem occurred"

**Comment by BLeeEZ** [comment]
In the upcoming beta v1.2.1 the complete handling is reworked. Siri will tell the user what she found / tell the user that nothing matched the request.

Here are some example requests:
>             // "play music" => mediaType: 18
>             // "play podcasts" => mediaType: 6
>             // "play song <blub> by <artist>" => mediaType: 1; mediaName: blub; artistNames: artist
>             // "play song <blub>" => mediaType: 1; mediaName: blub; artistNames: -
>             // "play album <blub>" => mediaType: 2; mediaName: blub; artistNames: -
>             // "play artist <blub>" => mediaType: 3; mediaName: blub; artistNames: -
>             // "play <Rock>" => mediaType: 4; mediaName: -; artistNames: -; genreNames: Rock
>             // "play playlist <blub>" => mediaType: 5; mediaName: blub; artistNames: -
>             // "play podcast <blub>" => mediaType: 6; mediaName: blub; artistNames: -

**Comment by yllekz** [comment]
ah cool. As an aside I remembered the specific thing I tried - I said 'play my "recently added" playlist' which ended up in Siri getting confused and giving up.

**Comment by BLeeEZ** [comment]
This feature can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25
