### ISSUE TITLE
Scrobbles submission should be delayed

### ISSUE THREAD

**Issue by Batwam** [BLeeEZ/amperfy#256]
Hello,

I noticed that Amperfy appears to submit Scrobbles to Last.fm pretty much as soon as the song start. This is a problem for me as it means that a song I skip after a few seconds (e.g. because I don't like it) still gets submitted and listed in my scrobbles.

As [per Last.fm API](https://www.last.fm/api/scrobbling#when-is-a-scrobble-a-scrobble):
> A track should only be scrobbled when the following conditions have been met:
>- The track must be longer than 30 seconds.
>- And the track has been played for at least half its duration, or for 4 minutes (whichever occurs earlier.)

>As soon as these conditions have been met, the scrobble request may be sent at any time. It is often most convenient to send a scrobble request when a track has finished playing.

Based on the above, Amperfy does not follow the methodology set up by last.fm.

Would it be possible to update the scrobble submission to either meet the definition or only submit once a song completes? Either of those would be better than the current method.

**Comment by BLeeEZ** [comment]
I already reworked the scrobble behavior for 1.2.1. These criteria should be fulfilled and can be tested in the next beta.

**Comment by Batwam** [comment]
Amazing, I'm on the test flight version 1.2.0(3). Hopefully this update will get pushed soon?

**Comment by Batwam** [comment]
I can confirm that amperfy now submits Now Playing upon song start and the scrobble
