### ISSUE TITLE
Bug: Completed downloads don't get cleared from active downloads list

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#26]
Using the latest testflight beta (1.0.4)  when a download is done it doesn't get cleared of the list of active downloads.

**Comment by BLeeEZ** [comment]
The download list has never been cleared. It should show the user the status of current active downloads / downloads that have been finished. It is cleared on every app restart.

**Comment by sandersantema** [comment]
I see, but the menu name is confusing nonetheless given that it states "Active Download" while a completed download is not active anymore. Furthermore they cause the actually active downloads to be not visible after awhile. 

Perhaps it might be a nice idea to rename the menu to "Downloads" and structure it in the same way as the queue: 
![image](https://user-images.githubusercontent.com/21057514/113489202-1b26e700-94c3-11eb-82d3-259998831b42.png)

Where the play/pause and related buttons obviously wouldn't be visible and the "Previous" text would be "Previously Downloaded" and "Next" would be "Currently Downloading" alternatively it could be "Downloaded" and "Downloading" respectively.

**Comment by BLeeEZ** [comment]
In this commit 8bb121cc4968841859ec4c252be81218150bda0a the downloads are now grouped by "Completed", "Active" and "Next". I also added the possibility to cancel all downloads.

**Comment by BLeeEZ** [comment]
Can this ticket be closed?

**Comment by sandersantema** [comment]
This can be closed.
