### ISSUE TITLE
Smart playlist tracks are not refreshed when playing via Siri / Shortcuts

### ISSUE THREAD

**Issue by reillymc** [BLeeEZ/amperfy#260]
When playing a smart playlist from siri or a shortcut, the tracklist is not re-fetched before playing the playlist - it just uses the last retrieved set of tracks. Opening the playlist page manually in the app will refresh the tracks. Would it be possible for this refresh behaviour from the page to be applied before playing from siri / shortcut?
Thanks for all the work put into the project - it's a fantastic client!

Tested on Amperfy version 1.2.1 running against Navidrome Server 0.52.0.

**Comment by BLeeEZ** [comment]
Yes I will add this

**Comment by BLeeEZ** [comment]
Done in 98413ff33865eb909a6f26db7e7fcd38d29fc54a.

**Comment by reillymc** [comment]
I have been running a build from develop on my device today and the change is working great! I can verify it refreshes my smart playlists when using Siri and Shortcuts. Thanks so much for implementing this!
