### ISSUE TITLE
CarPlay pauses music when using apple maps

### ISSUE THREAD

**Issue by Belugaking** [BLeeEZ/amperfy#264]
First off, just want to say this app is amazing, I've been able to hook into my server running Navidrome and the app works almost perfectly, so thanks to all the contributors to this project. The issue I'm having is whenever I either go into the split view in apple car play while playing or I just go full screen with apple maps, it stops the music from playing and I'm unable to play it again. Has anyone else had this issue?

**Comment by BLeeEZ** [comment]
Hi, thank you. It sounds like a bug I already fixed regarding iOS AudioSession (3105ff6). This can soon be tested in the upcoming beta v1.2.1.

**Comment by Belugaking** [comment]
Awesome, I'll definitely be sure to try out the beta whenever it releases.

**Comment by BLeeEZ** [comment]
This bug fix can be tested in the newest beta v1.2.1 (2): https://github.com/BLeeEZ/amperfy/issues/25
