### ISSUE TITLE
[Bug]old data bug

### ISSUE THREAD

**Issue by Yumega** [BLeeEZ/amperfy#265]
Delete an album from navidrome server, but on amperfy side, the album is still there, can't synchronize with the server

**Comment by BLeeEZ** [comment]
Does your mentioned album contains cached songs?
Deleted albums will still be displayed when it contains cached songs.
Albums are marked as deleted for example when the album is opened or the artists of the album is displayed.
And of course Offline Mode must be inactive.

Which API is your server using Subsonic or Ampache?
