### ISSUE TITLE
Carplay

### ISSUE THREAD

**Issue by Ang3er** [BLeeEZ/amperfy#269]
Play music which is streamed and not offline as well as offline Musik.
Currently K must first download /cache Musik to be able to play it in CarPlay is that the designed workflow?

How can I enable music streaming over mobile internet, as well as have my complete library available

best

**Comment by BLeeEZ** [comment]
Yes this is intended behavior. Apple suggests in their CarPlay guidelines to use offline / cached elements to ensure two things: 
1. no additional costs due to mobile streaming 
2. Avoid driver concentration interruption due to streaming and connection issues

**Comment by BLeeEZ** [comment]
Added a new tab to CarPlay which only contains the downloaded elements (142bcf9c640b726be897ad7f8788cf8c691eefe3):
![image](https://github.com/user-attachments/assets/574af804-3797-4dc0-b915-03cc08586ac3)
Library tab will display the elements taking OfflineMode into account: If OfflineMode is active the elements are equal to Cached tag. In OnlineMode all elements of the sections are displayed.
