### ISSUE TITLE
Improvement: bad text contrast on currently playing screen

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#27]
As you can see in the screenshot the contrast between the gray text and symbols is quite bad, this hinders readability. For me personally it's only a hindrance, but for someone who's visually impaired I'd imagine it could become unreadable. There are some good guidelines available online such as [this one](https://material.io/design/usability/accessibility.html#color-and-contrast), although I think the easiest fix would be to simply set the color to black. You might still want to look into whether this still delivers the desired contrasts given the changing colors of the backgrounds. 

![image](https://user-images.githubusercontent.com/21057514/113409496-b465d880-93b1-11eb-8261-26c5cab0cad2.png)

**Comment by BLeeEZ** [comment]
Yes you are right. I will replace  the gray color with black/white. Do you think the blue color has enough contrast?

**Comment by sandersantema** [comment]
I think it's better to rely on the formula/ guidelines of W3C than subjective judgements, it is described [here](https://css-tricks.com/understanding-web-accessibility-color-contrast-guidelines-and-ratios/) with references to the guidelines of W3C itself, but those are quite elaborate.

**Comment by BLeeEZ** [comment]
With this commit 02c344fdc0883906e1a69f7bc3302631636c15b2 contrast has been improved.

**Comment by BLeeEZ** [comment]
Can this ticket be closed?

**Comment by sandersantema** [comment]
Contrast is very good now.
