### ISSUE TITLE
Download Album Not Working

### ISSUE THREAD

**Issue by misaligar** [BLeeEZ/amperfy#272]
Some albums cannot be downloaded for some reason. Not exceeded the cache limit. I can confirm that. What other information can I provide for troubleshooting? Backend is Navidrome on my local network. iPhone 13 latest iOS. Nothing in the Event Log related to this issue.

**Comment by BLeeEZ** [comment]
How did you trigger the download? Long press on the album and in the detail menu pressed download or did you press the „…“ button in the album detail view and then download? Can single songs from this album be downloaded? Are any error messages shown when you trigger the download? How does the songs of this album look like in the Download view (Downloads can be disabled in the library view via edit in the upper corner)?

**Comment by misaligar** [comment]
I tried both options. No error messages. No single songs could not be downloaded.

What eventually fixed the issue for me is to Resync Library. I am now able to download the albums that previously did not work.

Feel free to close the issue now. If you want to investigate, I can try to answer any more questions you may have.

Thank you.
