### ISSUE TITLE
[Request] Grid view (especially for albums)

### ISSUE THREAD

**Issue by el-tiuri** [BLeeEZ/amperfy#273]
A grid view would be fantastic for albums. This would be especially nice for iPads.

Some notes:

* Resizing the grid (choosing the number of albums per row) greatly improves this feature. In my opinion the Manet screenshot (see below) would look a lot better with three or perhaps even four albums per row, but that’s not an option.
* Options for rounded corners might be a good idea. The iOS music app rounds them by default, but the corner radius could also be an option the user could adjust
* It could be an option to change which metadata is displayed under each album, though just defaulting it to album and artist also makes sense.
* Defaulting to available album art might be a good idea for the artist view, if no image is available

[Example from the default Music app on iPad](
https://github.com/BLeeEZ/amperfy/assets/60013019/ba87c8e8-1eff-4c08-be74-6eb1ea7a3b31)

[Example from Manet on iPhone (Jellyfin music player)](https://github.com/BLeeEZ/amperfy/assets/60013019/d8f961fb-f34e-4b8b-9f5d-8214b8400b5f)

[Example from Marvis (alternative app for Apple Music)](
https://github.com/BLeeEZ/amperfy/assets/60013019/d2e52e4c-91bf-424c-8535-b16bbf52efcb)

[Settings pane for Marvis, which might provide inspiration and is an example of a couple of things I mentioned](https://github.com/BLeeEZ/amperfy/assets/60013019/e934d344-5379-4373-bb0f-6b026a7d1ab4)

**Comment by BLeeEZ** [comment]
This feature was once implemented (486368d) and got removed due to wishes from the community (899a771).
To that time I didn't let the user choose which style is wanted (Collection view was the only one).
I will add it again again with the option to let user choose the style.

**Comment by BLeeEZ** [comment]
Done in 8ed3352c84fa84a2527be194b66c870bb7f51ec6:

![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-22 at 16 46 32](https://github.com/BLeeEZ/amperfy/assets/17556018/c4158776-5e63-429e-a58a-185d2e22cbad)

**Comment by el-tiuri** [comment]
Sweet! Did you also implement an option to adjust the size of the album art so more albums can fit on the screen? It’s not apparent from the screenshot.

**Comment by BLeeEZ** [comment]
Size is now adjustable with via 9051f68801c6cc53619f91c9c7625183a302dfdf.

**Comment by tobiaseisenschenk** [comment]
I used this in beta and it looks great - thanks for implementing!
