### ISSUE TITLE
[Request] Remember position in song

### ISSUE THREAD

**Issue by el-tiuri** [BLeeEZ/amperfy#274]
It’d be nice if the play position in the played song would be saved so you could pick up exactly where you left off if the app gets closed or suspended in the background.

**Comment by BLeeEZ** [comment]
Here is a requist quite similar to that one (first question): https://github.com/BLeeEZ/amperfy/issues/197

**Comment by andrew-oneill** [comment]
Thank you for this wonderful app. Would it be possible to make this an option in the settings so that the user can choose whether songs automatically resume their position?
