### ISSUE TITLE
[bug] when amperfy opened, the voice from other app disabled

### ISSUE THREAD

**Issue by Yumega** [BLeeEZ/amperfy#276]
as I said, when open amperfy,the playing audio from other app automaticly stoped.

it's a bug

**Comment by BLeeEZ** [comment]
Which version of Amperfy are you using? I am testen the following scenario:
1. open the iOS Music App
2. Start playing a song
3. Open Amperfy
The playback of iOS Music is still playing. Amperfy takes only over if I press play in Amperfy.
What are the steps you are doing, so I can reproduce the situation?

**Comment by BLeeEZ** [comment]
I did some changes to the audio session handling. Could you please install the beta v1.2.1 and verify if it still occurs there. Here you can find details https://github.com/BLeeEZ/amperfy/issues/25.

**Comment by BLeeEZ** [comment]
Is this issue still occurring?
