### ISSUE TITLE
Bug: Toggling shuffle causes the player to freeze and stop playback when song is skipped for smart playlists

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#28]
This happens when toggling shuffle on a smart playlist but it seems like the result is either cached or it's not 100% reproducible since I had no problem shuffling a smart playlist after I'd shuffled it before.

**Comment by BLeeEZ** [comment]
I can confirm this. On my phone it occurred with a very big playlist. I will investigate it.

**Comment by BLeeEZ** [comment]
The shuffle algorithm was a computational complexity nightmare. The performance has been dramatically improved with this commit ce414c3a95bcdb046efdaf7cfb7c35ed7ebf3ac2.

**Comment by BLeeEZ** [comment]
Can this ticket be closed?

**Comment by sandersantema** [comment]
This might be a separate issue which I can open a issue for if that's indeed the case. When you toggle shuffle on or off and skip a song sometimes it will not play and the duration will be `0:00`, I tried to figure out a way to reproduce this issue but it seems it's not dependent on shuffle being turned on or off but rather the toggling itself. So by simply playing a song from a smart playlist turning shuffle on or off skipping a song (possibly repeatably) you should be able to reproduce the issue.

**Comment by sandersantema** [comment]
I seems to be fixed for the most part, fiddling around a bit pressing queue, skipping songs and adding the whole smart-playlist to the queue I was however able to get the song to pause after which I was however able to resume playback. This might be a whole other issue though and I can't reproduce this with any certainty yet. If I do discover a pattern I'll open a new bug.
