### ISSUE TITLE
[Bug] Leading swipe sometimes shows delete option instead of intended options

### ISSUE THREAD

**Issue by el-tiuri** [BLeeEZ/amperfy#280]
Basically what I said in the title. Sometimes swiping returns the intended actions, sometimes it shows a delete button.

[This video](https://github.com/BLeeEZ/amperfy/assets/60013019/512c10a3-5d0e-4a95-8923-ef414acebc0c) I just recorded is a particularly bad example, usually it happens significantly less.

**Comment by BLeeEZ** [comment]
Thank you for reporting this bug.
I was able to reproduce it and got it fixed with: 1617208fd05cbef31bb56bcc72e8bcb66efdb41a
