### ISSUE TITLE
(SOLVED) "status code 50 all downloads disabled" msg after every track..

### ISSUE THREAD

**Issue by greenfishgit22** [BLeeEZ/amperfy#284]
Hello!

First of all thank you so much for this excellent application. I'm using it to serve my navidrome setup. However on default setup on ios, I get "status code 50, downloads disabled" everytime I cue a new track or the next song plays. Anyways to fix this?

Thanks
![IMG_3834](https://github.com/BLeeEZ/amperfy/assets/123745120/b3ea0dbe-b545-4f06-93d1-8d88c77cafa1)

**Comment by BLeeEZ** [comment]
Hi,
thank you. There are two ways to fix this:
- enable downloads on your server
- In Amperfy go to Settings->Player-> disable „Auto cache played songs“
