### ISSUE TITLE
[Feature request] X-Callback URL for track rating

### ISSUE THREAD

**Issue by kzssc** [BLeeEZ/amperfy#288]
thanks for the great work! 

it'd be great if one can rate the currently playing track using Shortcut! 

Many thanks

**Comment by BLeeEZ** [comment]
Rating and Favorite for currently playing song has been added in 9fd99f9f20110bff183edda34a3a5f1c55cc9253.

**Comment by BLeeEZ** [comment]
This can now be test on iOS via TestFlight (https://github.com/BLeeEZ/amperfy/issues/25) in v1.2.2 (2).
