### ISSUE TITLE
Bug: Looking at library settings page crashes amperfy 1.0.4

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#29]
Looking at the library settings page crashes the app. I suspect it has something to do with the cache information code given that these don't display any numbers but only the waiting symbol before crashing.

**Comment by BLeeEZ** [comment]
Mhh, I can’t reproduce it. Can you provide me additional information: How many songs are cached on your phone? Did you cache all song in your library (How many songs are in your library)? Can you tell me how big your app data is from iOS settings?

**Comment by sandersantema** [comment]
The ios settings report a size of 5.70 GB, which means it hasn't yet downloaded my whole library since that's about 30GB. I can't tell you the precise stats given that it crashes before showing i.e. it crashes before showing the number of cached songs and song cache size and instead only shows:
![image](https://user-images.githubusercontent.com/21057514/113488894-37c21f80-94c1-11eb-89e7-0fa8afa1572f.png)

On the off chance the iOS version I'm running (14.3) has anything to do with this I'll update in a bit and try again.

**Comment by BLeeEZ** [comment]
Puhhh, this bug was a very tough one.
I was not able to reproduce it with the simulator. After intensive testing the bug occurred on my iPhone.
The issue is the size of the cache. During calculation the whole cache is loaded into RAM.
The device runs out of space and crashes.
For now i removed cached song size in MB/GB and only display the number of cached songs.
The same issue occurred at triggering a "Download all songs" on a large playlist due to a inefficient check of isCached.
This is fixed in this commit 55d51448fde24b85de440b322b045a09678921d4.

**Comment by sandersantema** [comment]
I've posted a possible fix or rather draft/ idea for a possible fix here: https://github.com/BLeeEZ/amperfy/pull/30 

You might want to investigate this lazy functionality (with caution!) for other performance improvements, although in another languages which I know lazy computation from, namely Python and even more so Haskell, it can be a bit tricky and I believe it doesn't always improve performance.

**Comment by BLeeEZ** [comment]
After some investigation and reading about CoreData I was able to fix this issue with this commit 562e02cee113092fc4b6ae5d6e4da2ba4d1e0e8f. I am requesting only the meta data of the song files directly from Core Data. With that the file itself is not loaded into RAM.

Thanks for the remark regarding ```lazy``` functionality. I first read about one month ago about this functionality and try to used it wherever I see the opportunity. The ```reduce()``` function is completely new to me, but it seems that I will use it in the future too.

**Comment by BLeeEZ** [comment]
Can this ticket be closed?

**Comment by sandersantema** [comment]
This issue itself can be closed given that the whole library settings page is removed, but I think it would still be a good idea to report some statistics about the storage usage of the app. Although other issues might be more important as of now given that you can get this information from the iOS settings app too.
