### ISSUE TITLE
[Request] Download queue view

### ISSUE THREAD

**Issue by el-tiuri** [BLeeEZ/amperfy#293]
A download queue view would be useful to see pending downloads. Having options to prioritise certain pending downloads and cancel specific/all pending downloads would also be useful to add in this view.

**Comment by fidoriel** [comment]
Sometimes I try to download music and it does not download anything. A reinstallation solved it, but a queue would help make the download process explicit.

**Comment by BLeeEZ** [comment]
There is already a download queue view. You can activate it via: Library -> Edit -> Activate "Downloads"
