### ISSUE TITLE
[Feature] Option to only show an artists albums, songs, or both

### ISSUE THREAD

**Issue by Insprill** [BLeeEZ/amperfy#296]
In my library, I have an artist with ~380 albums (live shows) totaling 10,100+ songs. When going to the artist page, the fact that all albums + songs are always shown makes it quite difficult to get to a specific album since the scroll bar is useless at that size and the interface is slow. Having an option to show only albums (what I care about), only songs, or both would be great.

**Comment by BLeeEZ** [comment]
Album artist filter is added (https://github.com/BLeeEZ/amperfy/commit/5fcaa1b1acf41f309e918bd9473fc4ce4b1ea494). It is default on.
