### ISSUE TITLE
Deployment to phone

### ISSUE THREAD

**Issue by muellerj** [BLeeEZ/amperfy#3]
First of all thanks for your work. I'm a total newbie when it comes to iOS development and could not get the project deployed to my phone. The error seemed to be something with app IDs:

![Screenshot 2019-05-19 at 15 15 39](https://user-images.githubusercontent.com/53246/57982711-72e01480-7a49-11e9-9872-7626dd0bd250.png)

Could you provide instructions on how to deploy the app to a device?

How hard/cumbersome would it be to place the app on the official store?

Kind regards and again thanks for your work -
Jonas

**Comment by BLeeEZ** [comment]
Hi,
thank you, i appreciate your response. 

I think this post could help you to bring Amperfy on your device:
https://stackoverflow.com/questions/39603667/failed-to-create-provisioning-profile

I wanted to release the app free of charge on the app store.
The apple developer fee to officially release Amperfy on AppStore is 100$/year.
A tax id is also neccessary to get an apple developer account.
This is for me to much work (i don't like to do) for a free time project.

Kind regards
Max

**Comment by muellerj** [comment]
Hi Max,

thanks for the fast response. I managed to deploy that App by just entering some random string under "Bundle Identifier". In case someone else stumbles across this, here is a screenshot:

![Screenshot 2019-05-19 at 21 49 47](https://user-images.githubusercontent.com/53246/57987387-f2d5a100-7a80-11e9-8731-9a7cf23f3556.png)

I totally get you not wanting to spend 100 $/year. As I said, I'm completely new to iOS development. I'll post new issues as I go along - I already had trouble confirming the initial signin dialog ;)

Keep up the good work and thanks again -
Jonas
