### ISSUE TITLE
Crash during sync iOS 14.5

### ISSUE THREAD

**Issue by 3Dscrewer** [BLeeEZ/amperfy#31]
Subsonic and Airsonic Advance, crash during Album sync at very large Database. 
See message TestFlight

**Comment by 3Dscrewer** [comment]
It‘s 10.4 (2) showing, I have send the Crashfile with a note in German language.
Regards Heinz (he.s@xxxx.com)

**Comment by BLeeEZ** [comment]
The crash should be fixed with this commit 5647bd52d598913037c2e7f5782daf249aea41ab.
The support for huge libraries has also be implemented and will be testable in the upcoming beta release.

**Comment by BLeeEZ** [comment]
Beta v1.0.5 (2) is now available (TestFlight: https://testflight.apple.com/join/HCZzB1fU).
Can you test your issue with this version please?

**Comment by 3Dscrewer** [comment]
Yes, the crash is fixed at one system (Airsonic) with only music , but 15 Minutes for scan ?
The Subsonic system with also Video and other stuff is still crashing.

**Comment by BLeeEZ** [comment]
With this commit the sync duration of the subsonic server (with video) is reduced to 1 minute 18 seconds and is not crashing: 28c336aa1ebc60793e8955cf43e26961fe03cb8a
