### ISSUE TITLE
(UX) Issue: refresh playlist action is duplicated

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#32]
To refresh a playlist there are currently two options:
1. Pull down playlist
2. Press the `...` symbol and select `Update from server`

I propose to remove either one of these, not only because these actions are duplicated but also because it's quite easy to accidentally trigger a refresh by pulling down. Refreshing big playlists is currently very slow, so it's something which I think should be harder to do accidentally. Even better would be to refresh playlists automatically but I think this is a lot more work (and might not be possible due to limitations of ampache?)

**Comment by BLeeEZ** [comment]
In the next view days a new commit will be pushed, which includes your suggestions. I am reworking the sync completely. 

Playlists will always be synced -> If you add a song to a playlist, this change will be directly synced to the server. This will also be done if you remove a song or change the order. Deleting a playlist be synced too.

One change will also be done to speed up Sync at the beginning:Songs are not synced directly after the login in Amperfy. They will be synced only when needed (Open the artist or album in the App).

**Comment by sandersantema** [comment]
This sounds fantastic, I'll close this for now than and revisit when I can test.
