### ISSUE TITLE
[Feature request] Tap on song behavior

### ISSUE THREAD

**Issue by arvigeus** [BLeeEZ/amperfy#321]
Currently tapping on song clears the queue and plays this song only.

I prefer the classic behaviour where taping on song plays the song, then plays either the next song in the playlist, or a random song.

Maybe this behaviour should be configurable via setting?

**Comment by BLeeEZ** [comment]
I assume this is only for the "Library"->"Songs" view. Is this correct?

**Comment by arvigeus** [comment]
Technically, should be applicable to any list, ex:

- Library -> Albums -> (Album Name)
- Library -> Artist -> (Artist Name) -> Songs

But since I am the only one requesting it (strangely enough), I wouldn't push for any complex solutions.

**Comment by BLeeEZ** [comment]
The two views you are mentioning already behave in that way. The player's playlist will be replaced with all songs from that album and when the selected songs finished the next song from that album plays.
Maybe I am not getting your requested feature right?

**Comment by atomheartbrother** [comment]
I am looking for this exact functionality! I created (and now closed due to duplication) https://github.com/BLeeEZ/amperfy/issues/340 for the same feature.

As mentioned in my, now closed, issue, this functionality feels a lot more natural and is how most music players handle single song selection.

**Comment by BLeeEZ** [comment]
Implement via d8c002f357c0c80c079d9e4b0d48007e0b51e6bd. Pressing a song in Songs or "Favorite Songs" will add the next 39 song to the player too (total player queue size 40).

**Comment by BLeeEZ** [comment]
This can now be test on iOS via TestFlight (https://github.com/BLeeEZ/amperfy/issues/25) in v1.2.2 (2).
