### ISSUE TITLE
publish .dmg in releases for MacOS

### ISSUE THREAD

**Issue by pandalanax** [BLeeEZ/amperfy#324]
Hi, thanks for this awesome app.

would it be possible to add the .dmg file in releases? i have the security policy set to 'Permissive Security' which apparently the app store does not like..

i can take a look at it later how the workflow would look like. 
![image](https://github.com/user-attachments/assets/a2f53db1-20c1-49fc-b1b1-45ae3ceb03f9)

**Comment by Schlaubischlump** [comment]
Are you trying to use the current AppStore version? 

If I'm not mistaken the current app store version has no support for macOS. That means, you are actually trying to execute the iOS version on macOS. That might be prohibited by your security policy. 

I don't see a reason, why an official macOS app (which the next release should be) from the AppStore should not work. That is as secure as it gets.

**Comment by pandalanax** [comment]
ah i see, yes that's exactly what happened. i was trying to run the iOS app thinking it was the mac app. thanks!

**Comment by BLeeEZ** [comment]
Hi @pandalanax,
just for your notice. The macOS version is now available via TestFlight.

**Comment by pandalanax** [comment]
Sorry, just saw your comment. The linked Button in the readme directs me to the ipad version in app store.. not the testflight one

**Comment by BLeeEZ** [comment]
The TestFlight version can be installed as described here #25. The current macOS version is still the iPad version till the official release of v1.2.2.
