### ISSUE TITLE
Regression: swipe actions don’t work in album view anymore

### ISSUE THREAD

**Issue by el-tiuri** [BLeeEZ/amperfy#328]
After the latest update, swiping on a song in the album view just registers as a tap, and plays the song immediately rather than showing the popover menu.

**Comment by BLeeEZ** [comment]
Fixed in 87eda391c6446a94e60a10a380d3f52f2cda81b4.

**Comment by BLeeEZ** [comment]
This can now be test on iOS via TestFlight (https://github.com/BLeeEZ/amperfy/issues/25) in v1.2.2 (2).
