### ISSUE TITLE
Long audio or audio books loose their place

### ISSUE THREAD

**Issue by plastikman** [BLeeEZ/amperfy#332]
Version: 1.2.1
Build: 3
Airsonic version: 11.0.0-SNAPSHOT.20240424015024
Host: Windows 11
iOS version: 18.1 (but has happened in 17.x and 16.x too)

The actual playback of audio books is totally fine, the issue is after the audio is stopped many times the position is lost.  

I listen to audiobooks on the drive into work, then when i get to work i have to screenshot the playback position since more often than not the application seems to have been killed in the background and the playback position is lost resulting in the chapter being re-started.

**Comment by plastikman** [comment]
seems like a duplicate of https://github.com/BLeeEZ/amperfy/issues/305

Ill add my comments there, this can probably be closed.

**Comment by plastikman** [comment]
After reading that bug more its not the same,  This issue happens with downloaded or non-downloaded media.  I think this is more about not keeping the correct position data somewhere when the app has been "put to sleep" by iOS.

**Comment by plastikman** [comment]
Its actually a duplicate of https://github.com/BLeeEZ/amperfy/issues/197

**Comment by BLeeEZ** [comment]
Do you press Continue: Music in CarPlay?
I found a bug (fixed with b6e9dacca07a201be2365552ff976f6f0895cba2): when you press Continue Music in CarPlay the music progress gets deleted.
Nevertheless you are right: When Amperfy gets closed either by user or iOS the progress of the currently played song gets lost.

**Comment by BLeeEZ** [comment]
Song progress is now kept in case of an App crash or when switching between Music/Podcast mode (3478a5110936f63d4df9a230686ddf3ced4f90f9).

**Comment by plastikman** [comment]
This does not usually happen when in CarPlay it’s usually just at random. 

Thank you for taking the time to review this and implement a fix. I look forward to trying this when there is a release. 

If this makes it to TestFlight I will try it there.

**Comment by BLeeEZ** [comment]
This can now be test on iOS via TestFlight (#25) in v1.2.2 (2).

**Comment by plastikman** [comment]
I am running the test flight version, but have not had time to listen to any of my audio books.  I will keep testing and update here.

**Comment by plastikman** [comment]
I just rebooted my phone and m audio book restarted from the same place!!!!  I would say this appears to work for me <3

**Comment by plastikman** [comment]
I have confirmed that the application went to sleep on my phone, the progress bar when I opened the app was at "0", I hit play and the audio book resumed its last place!  

To me this is solved.

**Comment by BLeeEZ** [comment]
I added a new option to activate song playback resume (84e740db9e340da1b91145cbef5a5bccb206c3fd). By default it's off, which means songs will always start at the beginning.
<img width="387" height="107" alt="Image" src="https://github.com/user-attachments/assets/c53a4ffd-93da-43ee-bb34-c1fd78ef363f" />
