### ISSUE TITLE
Group same artist (featuring songs)

### ISSUE THREAD

**Issue by krupupakku** [BLeeEZ/amperfy#335]
Hey, 
In artist page, is there a way to group artist with a featuring if the song is part of same album?

I have multiple cases in which in an album, the artist has a lot of featuring and it's splitted in a lot of different artists, making the screen a bit hard to read. 

I attach a comparison between amperfy and navidrome reading same source.

| Amperfy     | Navidrome      |
| ------------- | ------------- |
| <img src="https://github.com/user-attachments/assets/fb29a37f-fd3c-47cd-b4df-03fe84e64c4e" width="300" /> | <img width="300" alt="image" src="https://github.com/user-attachments/assets/b65c445b-7554-4da3-bd54-25ae0fa7ef60"> |

https://github.com/user-attachments/assets/3e3df20d-eb4b-4daa-9209-19a265ce5f09

-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-..-.-.-.

or with another artist (Electric Callboy): same album (TEKKNO) but featuring songs are separated:

|  Photo1   | Photo2   |
| ------------- | ------------- |
| <img src="https://github.com/user-attachments/assets/9dfe271c-1f12-4c60-af5a-8293f9eb3f4b" width="300" /> | <img src="https://github.com/user-attachments/assets/a1b194cd-d513-403c-ab93-ca5a33d60e4c" width="300" /> |

Thanks for your hard work!

**Comment by Schlaubischlump** [comment]
Did you try to set the filter in the upper right corner to "Album Artist"?

**Comment by krupupakku** [comment]
Ups, not using beta. I'll join it, thanks!

**Comment by krupupakku** [comment]
Done! much better, thanks for the suggestion!
![IMG_ECD4375DAC10-1](https://github.com/user-attachments/assets/11dabaff-1449-4316-8559-36a78e547ea3)


Anyways I was expecting songs to be available in the song list, no?
![IMG_81BC8D0B1FE1-1](https://github.com/user-attachments/assets/ba30bdf6-38f3-4a05-9f38-deab24020301)

**Comment by BLeeEZ** [comment]
I think this is a bug. The query for artists detail does not take the filter into account.

**Comment by BLeeEZ** [comment]
Query is fixed in a35893935892bfbece3de7da6243dff87d68076e.

**Comment by krupupakku** [comment]
Wonderful! I built the code locally and it works as expected, ready to be in new beta.

I'll close the issue, thanks a lot for being so quick!
