### ISSUE TITLE
Tracks not foud

### ISSUE THREAD

**Issue by hec666** [BLeeEZ/amperfy#35]
First test.
Connection to my server ok.
Ok
Syncing, ok, found a lot of artist and albums, but only 4 track/songs !
There are about 8000 tracks, but all albums show 0 track, the 4 in ramdomly on 4 diffetent albums.

**Comment by BLeeEZ** [comment]
What music server (API) are you using (Ampache/Subsonic)?
On which version is your server running?

**Comment by hec666** [comment]
Server: NextCloud 21.0.0
Subsonic api 1.11.0

This morning I've found 136 songs, not 4, but it has to be around 8000.

This morning I've also tried to switch to the ampache version (also on the same nextcloud server, api 400001).

Now i can see a lot of artists, but 0 songs, albums, or playlist.

**Comment by hec666** [comment]
Hi.
Now I've updated to NextCloud 21.0.1
The Subsonic Api is the same 1.11.0
Now the app finds 53 Songs (599 Artist, 114 Albums, 0 Playlist).
It's strange because the songs found are different every time .

**Comment by BLeeEZ** [comment]
Currently I don't have a clue what the problem could be.
This issue is easier to investigate with the upcoming beta of v1.0.5.

**Comment by hec666** [comment]
Ok, waiting for the new version, thanks.

**Comment by BLeeEZ** [comment]
Beta v1.0.5 (2) is now available (TestFlight: https://testflight.apple.com/join/HCZzB1fU).
Can you test your issue with this version please?

**Comment by hec666** [comment]
> Beta v1.0.5 (2) is now available (TestFlight: https://testflight.apple.com/join/HCZzB1fU).
> Can you test your issue with this version please?

Ok, just installed.
tested subsonic and ampache connection.
Now the synchronization end instantaneously, and no media are present in the library (0 songs, artists, albums or playlist).
please note that the version indicated on settings is 1.0.4 (opened from testflight)

**Comment by BLeeEZ** [comment]
I was too fast. The beta is currently in review at Apple. It will be available soon.

**Comment by BLeeEZ** [comment]
It is now available in TestFlight (v1.0.5 (3)).

**Comment by hec666** [comment]
Ok, with the v.1.05 happens this:
Using Subsonc API:
at the first time found: 599 artist, 105 album, 0 song, 0 playlist.
after some time, i'll find  my 3 playlist, and 0 songs, but opening the play list, the relative songs were detected and became playable.
Strange, after this operation, i'll find also some songs that are not present in any playlist (the 2 library chached have 135, song, i've found 148 songs.


Using Ampache API:
at the first time found: 619 artist, 1091 album, 0 song, 4 playlist (my 3 playlist and ine playlist "all the songs")
no songs detected after some time, but after many hour i've find 8029 songs, many of them are rendomly duplicated.

I've tested another time Ampache (frist of previous test, but not reported), it' finds corretly 6493 songs in the "all songs playlist" and no duplicates.

At the end, I've tried anoter time with Subsonic, and I've created (by browser interface)a new playlist with all that the songs,now i'm waiting if the songs will be present after some time...

**Comment by BLeeEZ** [comment]
In the current beta songs are only fetched when requested:
- songs that are in a playlist that you are looking to
- songs in albums you are looking to
- songs that match a search you enter (The search API function is used)

I need to change the songs view to only display songs when a search query is entered. Also the naming in settings should be changed from "songs" to "Fetched songs meta info".

**Comment by BLeeEZ** [comment]
I have done some renaming in this commit: 83b32778006c440e0a513417ffd6524d62cac2a2
This will be testable in the upcoming beta.

**Comment by hec666** [comment]
Ok, great.
Now, after 2 days of "sleeping", i've found 6520 songs (near at all songs, see previous 6493, strange that there are small changes).
Played several randomly and it's work..
Thanks for your work
