### ISSUE TITLE
Catalyst 1.0 (5) crash

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#355]
I get this nasty crash when navigating to albums, app worked fine for a while.

I can navigate to artists and play music without crash.

https://hastebin.com/share/delakivuje.php

**Comment by Schlaubischlump** [comment]
It's working fine for me on 15.1. Anything particular that I need to do to reproduce the crash except for clicking the "Albums" sidebar item?

**Comment by bbsixzz** [comment]
![Screenshot 2024-12-02 at 20 59 21](https://github.com/user-attachments/assets/adf08768-d7e3-43ee-8645-396e144478c6)

I deleted server, I deleted cache.

Backend Navidrome v0.53.3

I will try reinstall

**Comment by bbsixzz** [comment]
My suspicion I played around with album display settings, I set it to list view see if you can reproduce a crash there.

**Comment by Schlaubischlump** [comment]
I think I can reproduce the bug.

Steps to reproduce: 
1. Change Album view to list
2. Change Album view back to grid
3. Select different sidebar item
