### ISSUE TITLE
Keep the help menu item on macOS

### ISSUE THREAD

**Issue by Schlaubischlump** [BLeeEZ/amperfy#356]
Even though Amperfy does not have a dedicated help menu, the "Help" menu item is still useful. I regularly use it to quickly search, find and highlight menu bar items. If there is no particular reason to remove the "Help" menu item, I would suggest to add it back in.

**Comment by BLeeEZ** [comment]
In the current master I already activated it again. It now as an direct menu item to report an issue on GitHub.

**Comment by BLeeEZ** [comment]
6f0cdace8c12528bb5156b2f025b7b04f3bfb188
