### ISSUE TITLE
macOS: Settings in the Amperfy menu instead of File

### ISSUE THREAD

**Issue by tehabe** [BLeeEZ/amperfy#358]
Usually "Settings…" is in the second block in the "Amperfy" menu but here it is in the File menu. So I couldn't find it at first.

<img width="243" alt="Screenshot 2024-12-03 at 08 12 51" src="https://github.com/user-attachments/assets/c1b588d5-2c02-4165-82d3-6d24016d5c09">

**Comment by BLeeEZ** [comment]
I am going to move it to "View".

**Comment by tehabe** [comment]
Please don't, in every macOS app it in the App name menu. That is the place where users expect it to be. Like this in Safari.

<img width="259" alt="Screenshot 2024-12-03 at 08 13 07" src="https://github.com/user-attachments/assets/6e36edec-cc2d-445a-a91b-118bf1d7db60">

**Comment by BLeeEZ** [comment]
Moved to "Amperfy" window menu (3b18350f8c58a710a58d04f928ad7201251c2df1).
