### ISSUE TITLE
Covers messed up in 10.05(3)

### ISSUE THREAD

**Issue by 3Dscrewer** [BLeeEZ/amperfy#37]
Ok, scan is working but cover art fully messed up.
I guess you can see difference without comment.

![B15A6D10-25AE-4918-8D83-F937CDAED726](https://user-images.githubusercontent.com/34925249/118349848-8e585a00-b553-11eb-9e6e-7f5f3baec7c5.png)
![C95BCEDC-E2D0-49D3-AD44-84B438882053](https://user-images.githubusercontent.com/34925249/118349855-931d0e00-b553-11eb-80dc-006fbf617f15.png)
![F3DB307A-3F4C-4CBD-AF64-77B2EDA22B17](https://user-images.githubusercontent.com/34925249/118349856-944e3b00-b553-11eb-9ed3-b8aa1e73d218.png)
![6CACC99E-8CDE-46EF-81C4-B23218A52A63](https://user-images.githubusercontent.com/34925249/118349857-94e6d180-b553-11eb-938e-187082ac1ee9.png)

**Comment by sandersantema** [comment]
I had to take a closer look to see what is actually going wrong but it seems your covers aren't properly cropped right? I'm not experiencing this issue using the latest Amperfy version together with the latest main version of Ampache:
![image](https://user-images.githubusercontent.com/21057514/118360336-68e54380-b587-11eb-953f-bfc3220c69bd.png)

It might be very helpful to know what server you are using Amperfy with and what version of Amperfy itself you are using. In general with bug reports it's key to include as much relevant details as possible to make it easier to solve it.

Judging by your github profile you are using airsonic-advanced right? One possible solution would be to use [Ampache](https://github.com/ampache/ampache) instead, it's a bit more trouble to setup but it really pays of and doesn't seem to suffer from the bug you're experiencing as you can see in my screenshot.

**Comment by 3Dscrewer** [comment]
Ok, I’m going to waisting my time. As before (a couple of times), I’m using Subsonic AND Airsonic Advanced. I have never seen a better maintained collection as mine. Round about 95% of all tracks (more than 230.000 Tracks) are named the same and also they have cover art included into the Tags, also a lots having embedded lyrics.
So far I know Ampache is using the Subsonic Api.
Play:Sub and AVsub including a lots of other tools are showing the cover art including into the Tags, but now you’re telling me it’s not proper tagged?
I have send the crash reports, as advised.
If your tool is unable to show Subsonic content, at this time, your app is still crashing at subsonic valid content, you should not say it is for subsonic servers.
I’m out, I have better things to do. 
cheers

**Comment by sandersantema** [comment]
I'm sorry you seem to feel frustrated, that certainly wasn't my intention. This is not my tool, nor do I have any experience with any of your earlier bug reports, I'm just a user of this app like you. I was trying to give you some tips to resolve this bug faster or use a workaround.

In any case, this app still seems to be in full development with all work done for free, wouldn't that would merit a little more gratitude and leniency for the developer?

**Comment by 3Dscrewer** [comment]
I‘m sorry, I didn’t realize that you’re not Maximilian, he wrote to me already. 
For your information, I don’t need this tool because I have two main tools where I have payed for and sending from time to time a tip, they are far beyond this tool with a lots of useful options like Car Play, Sonos integration, playing Videos, Chromecast, FireTV and so on. Also one of these developers are using my two systems for testing and debugging like the Developer of Amperfy too. I’m spending my time and my well maintained systems for guys like you, to have a good and bug free tool, nothing else … 😉🤷
Have a nice Weekend

**Comment by BLeeEZ** [comment]
I took a look at your database and you are definitely right. The artwork are messed up. I will take a look at my Subsonic API implementation to fix this.

**Comment by BLeeEZ** [comment]
This commit 38becfc9691a50bc3bf5575a21c0d23e02474845 fixes the subsonic artwork mess. A resync is necessary, but with the other fix the sync time is reduced dramatically.
