### ISSUE TITLE
Song not found due to wrong server URL when using AirPlay

### ISSUE THREAD

**Issue by mokkun** [BLeeEZ/amperfy#374]
Amperfy iOS cannot play songs, it fails with the following message:

```
Status code: 70
data not found

URL:
http://SERVERURL/rest/stream.view?u=USER&v=1.13.0&c=Amperfy&t=AUTHTOKEN&s=SALT&id=4cdd02473dc7e4d3e919aa563b5cae5e&format=mp3

Error Content:
{
  "statusCode" : 70,
  "topic" : "Download",
  "message" : "data not found",
  "cleansedURL" : "http:\/\/SERVERURL\/rest\/stream.view?u=USER&v=1.13.0&c=Amperfy&t=AUTHTOKEN&s=SALT&id=4cdd02473dc7e4d3e919aa563b5cae5e&format=mp3",
  "data" : "<subsonic-response xmlns=\"http:\/\/subsonic.org\/restapi\" status=\"failed\" version=\"1.16.1\" type=\"navidrome\" serverVersion=\"0.53.3 (13af8ed4)\" openSubsonic=\"true\"><error code=\"70\" message=\"data not found\"><\/error><\/subsonic-response>"
}
```

My server configuration is correct and I'm able to play songs normally, but as soon as I try to play to my speakers via Airplay, I start to get this error.

Also, sometimes the song will play for a few seconds until it stops completely.

I have used AirPlay successfully in the past with the app, so I'm not sure what could be causing this issue.

**Comment by BLeeEZ** [comment]
Since Apple released iOS 18.0 there are a lot of bug reports regarding AirPlay. I haven’t change code regarding AirPlay, I think this is an iOS issue. Are these errors occurring since your iOS upgrade?

**Comment by mokkun** [comment]
Unfortunately when I started to use the app I was already on iOS 18.0. I noticed that I have the same issue on macOS, probably related.

iOS Version: 18.1.1
iOS Amperfy: 1.2.2/3

macOS Sequoia 15.1
Amperfy: 1.0/5

**Comment by mokkun** [comment]
Closing this since it is a duplicate of https://github.com/BLeeEZ/amperfy/issues/373.
