### ISSUE TITLE
Bug: long songs/ mixes don't play or download.

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#38]
Using amperfy version 1.0.5(3) together with the latest Ampache main version it seems that songs (or mixes in my case) which are long don't play or download. This seems to depend on both the length and bitrate e.g. a 30 min 128kbps mp3 plays fine but a 30 min 320kbps mp3 or 2 hour 128kbps mp3 doesn't Amperfy isn't able to download those either and simply adds them to the completed download list despite failing to download them (the text stays gray).

**Comment by gsora** [comment]
Had something similar happening with FLACs.

I tap on a song, see in the logs that download finished correctly but nothing happens.

If I then press "back" and then "next" (essentially moving a song behind the current one, and then moving back) it works.

**Comment by sandersantema** [comment]
I think this might be another issue, given that the long songs seemingly don't download properly at all i.e. they're added to the completed downloads list but their text never turns blue (which seems to be an indicator a song is downloaded). Furthermore for the bug which I'm encountering codec doesn't seem to be a factor, rather filesize/ bitrate given that both AAC and MP3 files play fine as long as they're not too long or of too high bitrate e.g. a half our 128kbps MP3 plays fine while a 320 kbps MP3 doesn't. 

Although I'm not able to test it as thoroughly as you did so I'm not completely sure. Maybe you can try it out with a long mix too and look into the logs?  If it's not the same bug it might be a good idea to open a new issue.

**Comment by BLeeEZ** [comment]
@sandersantema I will take a look at large files but I was already able to download a video and listen to the audio track. I will take an investigation on songs with high bitrate.

@gsora I think you are right: If the server doesn't send the mime type information it can come to problems. I am thinking about adding your AVPlayerItem mimeType as default to the code base. Thank you for this suggestion.

**Comment by sandersantema** [comment]
I was thinking another possible cause of this bug could be some sort of download limitation imposed by my Ampache server. But looking trough the settings I couldn't find any limitations of that kind or at least not any enabled. But that might be another angle to tackle the problem from.

**Comment by BLeeEZ** [comment]
@gsora I have added your code suggestion in this commit 29db9bb7f7c72cf52d1c53981b0919f9d7eabe84.

@sandersantema Is it possible that the songs you are mentioning have a incompatible content type (mime type)? I did some testing and added an error message for known incompatible content types that are directly displayed to the user. Content type "audio/x-ms-wma" for example can't be played.

**Comment by sandersantema** [comment]
If I'm to believe this snippet of python code (or rather whether the guess_type function of the mimetypes module) is correct than no the only "content types" which I assume are mimetypes are `'audio/mpeg'` and `'audio/x-m4a'`.

```python
#!/usr/bin/python3.9
from mimetypes import guess_type
from pathlib import Path
from typing import Union

music: Path = Path("/home/sandersantema/Music/iTunes/iTunes Media/Music/")
files: list[Path] = list(
    filter(lambda f: f.is_file() and not f.name == ".DS_Store", music.glob("**/*"))
)

mimetypes_filenames: list[Union[str, None]] = list(
    map(lambda f: guess_type(f)[0], files)
)

mimetypes_filenames_unique: list[Union[str, None]] = list(set(mimetypes_filenames))
print(mimetypes_filenames_unique)
```

I don't think it would be logical either since I can play all files which are short or have a lower bitrate, it would be weird if only the larger files would have weird mimetypes. Some more info: the songs don't get timestamps, the seekbar only displays `0:00`.

**Comment by sandersantema** [comment]
Using `1.0.5 (5)` trying to download a problematic mix now makes it appear with red text below and a `!` to the right of it under the completed items. Do you have any idea how to go about fixing this bug or what I could test?

**Comment by BLeeEZ** [comment]
Good to hear. I added additional error messages with this commit 3cf94ad8813d8538f99ba583e6cccfc118df7e68 especially for download errors.

**Comment by BLeeEZ** [comment]
Is this issue still present or can this ticket be closed?
A simular problem with a fix can found here: https://github.com/BLeeEZ/amperfy/issues/50

**Comment by sandersantema** [comment]
I think so yes.
