### ISSUE TITLE
Ux/ Improvement: keyboard should dissapear when clicking on a song after search

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#39]
Currently the keyboard stays up when clicking on a song after a search even though it should disappear.

**Comment by BLeeEZ** [comment]
You are right. I haven't noticed this yet. I will look at this issue.

**Comment by BLeeEZ** [comment]
It is fixed with commit 50a4811540572b34ae0c7406d6ea58a0de7dad35.

**Comment by sandersantema** [comment]
Is this fixed in 1.0.5 (3) yet? The keyboard still seems to be up for too long i.e. scrolling trough search results. It shouldn't be up by then since it hides the search results itself.

**Comment by BLeeEZ** [comment]
Issue is fixed but no new beta in meantime.
My fix will hide the keyboard when a song is pressed to play.

**Comment by sandersantema** [comment]
Is it possible to hide the keyboard when scrolling trough the results too? If a song is hidden under the keyboard then you're not able to press it.

**Comment by BLeeEZ** [comment]
The keyboard will disappear with this commit 09de60c11db81b1d86613366df244f96f95aeac6 as soon as the tableview is draged.

**Comment by BLeeEZ** [comment]
Is this behavior ok in the latest beta?

**Comment by sandersantema** [comment]
I haven't tested it that much but it seems to work perfectly now. One minor potential improvement I can think of is to also hide the keyboard when the user presses the `All` or `Cached` buttons but that could also be undesired behaviour.
