### ISSUE TITLE
Sign In dialogue needs work

### ISSUE THREAD

**Issue by muellerj** [BLeeEZ/amperfy#4]
This is roughly what the sign-in dialogue looks like when a password manager is installed:

![Screenshot 2019-05-19 at 22 04 17](https://user-images.githubusercontent.com/53246/57987498-64621f00-7a82-11e9-8541-f4acb8eec4d6.png)
(the "Log In" button is hidden underneath the "Passwords" panel)

It would be nice if the dialogue could either be scrolled somehow or if the keyboard could be hidden after the password is entered. Or if pressing "Return" after the password would submit the form. Right now, selecting the URL again makes the "Password" panel disappear and the "Log In" button becomes visible again :)

Also, the text fields have a slightly different feel to the "usual" fields in the sense that they don't have a blinking cursor and are slightly smaller than the ones in search field for example.

**Comment by BLeeEZ** [comment]
Yes you are right. I aligned the textfield styles and added an open button to the keyboard. 
Should be fixed with 0a95dd2ec9848fd7cf22df7c976d1f2995e482d9

**Comment by muellerj** [comment]
Cool, thanks! Im on holiday and will be back in two weeks. Please feel free to close this issue.
