### ISSUE TITLE
macOS Catalyst version

### ISSUE THREAD

**Issue by gsora** [BLeeEZ/amperfy#40]
I've fiddled a little with the codebase and had a macOS version running quite easily.

It's not perfect but it works!

I had to ditch Carthage and use SwiftPM to make the dependencies compile for Catalyst, but I'm not really used to it - maybe you might be able to keep running on Carthage!

Are you planning a full-blown macOS version in the future?

<img width="1792" alt="Screen Shot 2021-05-15 at 22 08 24" src="https://user-images.githubusercontent.com/145909/118376725-1416ec80-b5ca-11eb-998e-650017569a56.png">

**Comment by BLeeEZ** [comment]
I have a M1 Mac and I am already running Amperfy on it via the Mac App Store (M1 Macs are able to run iOS Apps natively).
I haven't thought yet about a macOS version (pre M1).
This currently not a top priority feature.
I think I will do some test runs just to see how much effort it cost to create a Catalyst release.

**Comment by bbsixzz** [comment]
Any update on this?

Would be great for those of us still using Intel.

**Comment by BLeeEZ** [comment]
No updates yet. My focus is still on new features and bug fixes for iOS. @gsora Can you maybe share your adjustments via a pull request?
