### ISSUE TITLE
playlist not loaded correctly from server 1.0.5 (3)

### ISSUE THREAD

**Issue by flrnns** [BLeeEZ/amperfy#42]
Playlists are not loaded correctly from the ampache server.

The playlist Title is loaded and displayed along with the number of songs, but missing the duration ("0s").
Opening a playlist will show an empty list, so the individal songs are not being displayed and thus cannot be played.

**Comment by BLeeEZ** [comment]
Thank you for the reported issues. Which version does your ampache server has? Can you please provide me the api versions under Amperfy->Settings->Server too?

**Comment by flrnns** [comment]
Ampache 
Server API version 400001

**Comment by BLeeEZ** [comment]
With the current beta I switched to ampache api v5. Is it possible to upgrade your server to v5? V4 has some disadvantages for example genres are not supported. I am not shure if I want to support v4 in the future. I will at least add a error message so the user knows whats wrong.

**Comment by BLeeEZ** [comment]
Maybe I change the api to subsonic for this cases. Than the app would be still usable.

**Comment by flrnns** [comment]
I didn't know that ampache was not backward compatible, sorry.

As soon as I have v5 server, I will try again

**Comment by BLeeEZ** [comment]
Over the weekend I did some additional reading and testing regarding your issue.
Server API Version 400001 is quite buggy as you can read here: [Ampache API Changelog](https://ampache.org/api/api-changelog).
I set up an older Ampache server (API Version 430000) by myself. Amperfy works fine with that.
I would suggest you to update your ampache server.

**Comment by flrnns** [comment]
Thanks for your reply.
In the meantime I found out, that with Nextcloud there is no real ampache server involved that I could manually upgrade.
The music app of nextcloud seems to just provide server side api which is meant to be compatible with ampache 400001 and they have no plans to update

**Comment by BLeeEZ** [comment]
OK, I See the problem.
I assume you are using this: https://github.com/owncloud/music#ampache-and-subsonic
I think I will add a selector at the login screen to choose the backend API manually.
With that you would be able to use the Subsonic API.

**Comment by flrnns** [comment]
Yes, that's correct. That sounds awesome - hope it'll work!

**Comment by flrnns** [comment]
I just noticed, that I can setup Amperfy so that it interacts with the Subsonic backend of the music app.
Server settings:
Backend API: Subsonic
Server API Version 1.11.0
Client API Version 1.11.0

Howerver, the exact same issues with playlists do occur here, too.

**Comment by BLeeEZ** [comment]
With this commit a14cd6883c1b73d4637f2f2a7223efbd40cc3212 the API is selectable on the login screen.
