### ISSUE TITLE
playlist overwritten and emptied on server 1.0.5 (3)

### ISSUE THREAD

**Issue by flrnns** [BLeeEZ/amperfy#44]
Playlists are not loaded correctly from the server and appear to be empty in the app (see issue #42).
Adding songs to such a playlist in the app will work, but removes all other songs from the playlist on the server.
Because the synchronisation of newly added songs does not work properly, the user ends up with an empty playlist on the server.
The next time the app is started, the songs added via the app are gone too (see issue #43).

**Comment by BLeeEZ** [comment]
Can this issue be closed or is it still occurring with the latest beta?
