### ISSUE TITLE
artist image not being displayed 1.0.5 (3)

### ISSUE THREAD

**Issue by flrnns** [BLeeEZ/amperfy#45]
despite having an "artist.jpg" oder Artist-Name".jpg" in the artist folder on the ampache server, the default artist image provided by amperfy is being displayed.
the album images are displayed correctly.

**Comment by BLeeEZ** [comment]
I assume this issue is related to the ampache server version too.

**Comment by flrnns** [comment]
Yes, correct 400001

**Comment by BLeeEZ** [comment]
Can this issue be closed?
