### ISSUE TITLE
Compatibility with latest Ampache 5 db updates

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#47]
I was wondering whether amperfy is compatible with the latest Ampache 5 db updates which were merged 3 days ago:
https://github.com/ampache/ampache/pull/2926

I could imagine that this would only be a backend change which would change any API details but I don't know for sure and I'd like to know before upgrading my Ampache server to the latest version.

**Comment by BLeeEZ** [comment]
I will check this next week.

**Comment by lachlan-00** [comment]
If you have any trouble please tag me directly and I'll I'll help. The server changes are big but they are not actually breaking to an external client.

**Comment by BLeeEZ** [comment]
I am running Ampache via docker.
In the currently uploaded docker image the mentioned commit is not included. 
To test the commit I changed my docker-compose file from
```
  ampache-app:
    image: ampache/ampache:develop
```
to
```
  ampache-app:
    build: https://github.com/ampache/ampache-docker.git#develop
```

With that I tried to build the current image by myself.
After executing `docker-compose build` I get the following error message:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for scn/phptal v3.1.0 -> satisfiable by scn/phptal[v3.1.0].
    - scn/phptal v3.1.0 requires ext-gettext * -> the requested PHP extension gettext is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/php-cli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
ERROR: Service 'ampache-app' failed to build: The command '/bin/sh -c tar -xzf /tmp/develop.tar.gz --strip=1 -C .     &&  apk add --no-cache php-intl icu-dev     &&  docker-php-ext-install intl     &&  composer install --prefer-source --no-interaction     &&  rm -rf .git* .php_cs .sc .scrutinizer.yml .tgitconfig .travis.yml .tx *.md     &&  mv ./public/rest/.htac* ./public/rest/.htaccess     &&  mv ./public/play/.htac* ./public/play/.htaccess     &&  mv ./public/channel/.htac* ./public/channel/.htaccess     &&  chmod -R 775 .' returned a non-zero code: 2
```

**Comment by lachlan-00** [comment]
i'll be rebuilding this week, just prepping a new point release for the master branch and will redo develop

**Comment by lachlan-00** [comment]
in about 60000 ish seconds my poor mysql box will have built a new develop docker
![image](https://user-images.githubusercontent.com/1305249/120247158-eadaa980-c2b5-11eb-9131-64815cc59dcb.png)

**Comment by lachlan-00** [comment]
> I am running Ampache via docker.
> In the currently uploaded docker image the mentioned commit is not included.
> To test the commit I changed my docker-compose file from
> 
> ```
>   ampache-app:
>     image: ampache/ampache:develop
> ```
> 
> to
> 
> ```
>   ampache-app:
>     build: https://github.com/ampache/ampache-docker.git#develop
> ```
> 
> With that I tried to build the current image by myself.
> After executing `docker-compose build` I get the following error message:
> 
> ```
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for scn/phptal v3.1.0 -> satisfiable by scn/phptal[v3.1.0].
>     - scn/phptal v3.1.0 requires ext-gettext * -> the requested PHP extension gettext is missing from your system.
> 
>   To enable extensions, verify that they are enabled in your .ini files:
>     - /usr/local/etc/php/php-cli.ini
>     - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
>     - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
>     - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> ERROR: Service 'ampache-app' failed to build: The command '/bin/sh -c tar -xzf /tmp/develop.tar.gz --strip=1 -C .     &&  apk add --no-cache php-intl icu-dev     &&  docker-php-ext-install intl     &&  composer install --prefer-source --no-interaction     &&  rm -rf .git* .php_cs .sc .scrutinizer.yml .tgitconfig .travis.yml .tx *.md     &&  mv ./public/rest/.htac* ./public/rest/.htaccess     &&  mv ./public/play/.htac* ./public/play/.htaccess     &&  mv ./public/channel/.htac* ./public/channel/.htaccess     &&  chmod -R 775 .' returned a non-zero code: 2
> ```

Alpine made a change to their build which required an update since my last build. it's updated now too if you want to build yourself

**Comment by BLeeEZ** [comment]
@lachlan-00 Thank you for your support
@sandersantema I updated the Ampache server. As far as I can see Amperfy runs fine with the updated version.

**Comment by BLeeEZ** [comment]
I encountered a issue with "artist_albums" and reported it directly on Ampache: https://github.com/ampache/ampache/issues/2932

Due to this bug all albums will display "0 songs" after a fetch.

**Comment by sandersantema** [comment]
I've updated as well, no problems so far :tada:
