### ISSUE TITLE
Session Expired, how to renew?

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#48]
After updating ampache to the newest develop version  (API version `500000`)  and amperfy `1.0.5 (5)` my session seems to have expired, how do I refresh this without resetting app data that is. Is this a bug or some missing functionality?

Amperfy seems to have saved some logs to the event log, can you access those?

**Comment by BLeeEZ** [comment]
To get a new session you should simply force close the app via the app overview.

I can't directly access the event log. You can send it to me via Settings -> Support -> "Send issue or feedback to developer". There is a log file attached which helps me.

**Comment by sandersantema** [comment]
Restarting the app solved the issue.

**Comment by sandersantema** [comment]
Foto finish! :)
