### ISSUE TITLE
songs tab show displaying songs

### ISSUE THREAD

**Issue by Canorus** [BLeeEZ/amperfy#49]
https://user-images.githubusercontent.com/7209435/121761548-64eb1800-cb6b-11eb-967d-93bfc9f436d1.MOV

I tried to leave this on 1.0.5(5) through testflight but it seems didn't make it. Now that official 1.0.5 is released I decided to leave the issue on github(maybe I should've done it this way from the first place).

As seen from the video above, songs list is empty but when I start typing in the search bar it will show some results. I'm not sure if it's my server causing this but I'm reporting it anyway. Please let me know what to do if that's the case.

backend API Ampache
Server API version 441000
Client API version 500000

thanks.

**Comment by BLeeEZ** [comment]
A empty song list is intended. With v1.0.5 songs are not synced after login. Song getting synced via:
- Select an album
- Select an artist
- Select a playlist
- Search

I set the song list empty to avoid confusion of missing songs. 

I am interested and open for other solutions. I come up with these other possible solutions (for an empty search bar):
- Show only cached songs
- Show all songs that have been synced so far
- Show only songs that are in a playlist 

What would be your preferred solution or do you even have better one?

**Comment by Canorus** [comment]
```
I set the song list empty to avoid confusion of missing songs.
```

By _missing songs_ I assume you're talking about the songs that's already on server but not synced to device yet.

I thought it's more natural to show synced songs list in songs tab because

1. that’s how default Music app works
2. there’s dedicated search tab below

But now I see your point: triggering songs/playlists/artists sync would be much natural and convenient this way. I was about to request manual sync feature as well.

How about adding a new row _cached_ or _synced_ (though I'm not really sure if _synced_ is very useful) to Library view at the very bottom? Or maybe sync can be triggered by starting search while list shows already synced songs.

**Comment by BLeeEZ** [comment]
You are right I should display all songs that have already been synced.

How about adding an info dialog when clicking on songs the first time: „Only already synced songs are displayed. Please use the search bar to find and update your song collection.“ 

With that info I think I can display all already synced songs and the user should not be irritated about missing (not yet synced) songs.

**Comment by Canorus** [comment]
Apologies for slow response, final term exams are killing me.

```
How about adding an info dialog when clicking on songs the first time: „Only already synced songs are displayed. Please use the search bar to find and update your song collection.“
```

I agree, info dialog should reduce the confusion by far.

Plus I don't think Amperfy should follow default Music app works, since it's mechanism isn't same. Maybe it can be Amperfy's selling point(albeit it's free).

**Comment by BLeeEZ** [comment]
All already synced songs are now displayed by default: 5468f80db40008db805f751a6a37d3b32f15720d
I have added an info popup: fb211d1349cbb7981202b52e01964ec98a508bee

![Bildschirmfoto](https://user-images.githubusercontent.com/17556018/122399951-8be68700-cf7b-11eb-9065-6948cd36e8ba.png)
