### ISSUE TITLE
Problems playing .m4a songs

### ISSUE THREAD

**Issue by BLeeEZ** [BLeeEZ/amperfy#50]
This bug has been reported by @Canorus.
.m4a songs are streamed with reduced quality and can not be played from cache.
Server API Ampache.

**Comment by BLeeEZ** [comment]
I can confirm this issue as a server issue. The .m4a file can be played without problem via the Ampache Web GUI.
The url to the song provided by the Ampache API is correct.

If the url is tried to be downloaded, Amperfy gets a mp3 file back with the same name of the requested .m4a file (file ending changed). The size is also dramatically smaller and with that the audio quality. This "converted" file can only be streamed but not played from cache.
The curiouse thing about this bug ist that if you hit download in the Ampache Web GUI you get a link to the download API function. This link lets you download the "true" .m4a file. Only the direct link in the "Songs" API function returns the "converted" file.

As a quick fix to at least listen to song in lower quality you can deactivate automatic cache under Settings -> Player -> "Auto chache played songs". After that: Long press on the song and click "Remove from cache".

**Comment by BLeeEZ** [comment]
I have reported this issue: https://github.com/ampache/ampache/issues/2948

**Comment by Canorus** [comment]
```
As a quick fix to at least listen to song in lower quality you can deactivate automatic cache under Settings -> Player -> "Auto chache played songs". After that: Long press on the song and click "Remove from cache".
```

Thanks. That explains why it didn't happen on previous version. I was worried if anything is wrong on server configuration.

By the way cleaning from cache after disabling 'Auto cache played songs options' didn't solve the issue. Looks like I might have to disable transcoding from server. Thanks.

**Comment by BLeeEZ** [comment]
I disabled transcoding and everything works as intended.
