### ISSUE TITLE
[Feature]: Track seeking should show current time

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#53]
I don't know all the names of these GUI elements so I hope this makes sense. But what I'd like to see is the time changing when seeking trough a song. Currently it continues to show the current time in the song. To illustrate I've annotated a screenshot of my desktop music player:

![image](https://user-images.githubusercontent.com/21057514/122912423-9e383a80-d358-11eb-9dd6-276880bab3ec.png)

Here the time in red changes when moving the blue circled gui element, I think amperfy should do so too.

**Comment by BLeeEZ** [comment]
Feature is implemented in: fc6cb9dee23d424eabe1bc13a3f74e92089bd65f

**Comment by sandersantema** [comment]
Also works perfectly now!
