### ISSUE TITLE
[Bug]: Playlist duplicated songs

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#55]
When refreshing a playlist it sometimes ends up having duplicated all songs, this happens to a normal playlist.

**Comment by BLeeEZ** [comment]
I will investigate on this.

**Comment by BLeeEZ** [comment]
I will investigate on this.

**Comment by BLeeEZ** [comment]
Is this bug still occurring?

**Comment by sandersantema** [comment]
I don't believe so, or I haven't encountered it lately at least so I believe it's fixed. I'll close for now and if it occurs again I'll reopen.
