### ISSUE TITLE
[Bug]: After deleting a playlist on ampache amperfy doesn't sync up

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#57]
When deleting a playlist on ampache, amperfy doesn't sync up i.e. deletes the playlists but rather shows an error when trying to open these playlists the error states: `API Error Occured, Status code: 4704, Not Found: 9`.

**Comment by jfdnet** [comment]
delete songs/albums won't sync ether

**Comment by BLeeEZ** [comment]
Playlist are now getting deleted via this commit 31041f79706fdb189bc3b7e8f5c37234bb1c3e3d.

Songs and albums are a little bit tricky. All playlists and podcasts are included in one API request. With that the app can determine which playlists/podcasts are delete on server.
There is no API function to get the deleted songs or albums. The only possible solution would be to remove caching. This would result in a missing "offline" mode and empty lists till the app receives the answers from the server.

**Comment by jfdnet** [comment]
> Playlist are now getting deleted via this commit [31041f7](https://github.com/BLeeEZ/amperfy/commit/31041f79706fdb189bc3b7e8f5c37234bb1c3e3d).
> 
> Songs and albums are a little bit tricky. All playlists and podcasts are included in one API request. With that the app can determine which playlists/podcasts are delete on server.
> There is no API function to get the deleted songs or albums. The only possible solution would be to remove caching. This would result in a missing "offline" mode and empty lists till the app receives the answers from the server.

Can we make an manual refresh function like “pull to refresh” the list in album page to get the latest albums/songs?

**Comment by BLeeEZ** [comment]
I can think of a button like the "Delete cached songs" button. This one would be renamed to "Delete downloaded song files".
And a new button called "Reset cached library". This would delete all artists, albums and songs. Then the new data would be synced via the search functionalities.

**Comment by BLeeEZ** [comment]
Another approach could be to add new button "Resync library". This button would then return the app to the sync screen. What would you prefer?

**Comment by jfdnet** [comment]
“resync library” is good enough and simple too understand.

**Comment by sandersantema** [comment]
I think "resync library" by way of deleting all cached songs wouldn't be a great solution. My library is 37 GB and takes quite long to download, wouldn't want to do that every time I delete something. We could ask the Ampache dev whether there is a better solution?

**Comment by BLeeEZ** [comment]
The API offers two additional parameters :

Input | Type | Description | Optional
-- | -- | -- | --
'add' | set_filter | ISO 8601 Date Format (2020-09-16) | YES
  |   | Find objects with an 'add' date newer than the specified date |  
'update' | set_filter | ISO 8601 Date Format (2020-09-16) | YES
  |   | Find objects with an 'update' time newer than the specified date

There is no argument like "deleted in the meantime". Subsonic has also not such a function.
There is an API function to check if a song is still on the server. But with that a lot of server traffic would be generate to check if a song is still available each time. This would also take quite a time for a large library.

I can also think of a solution to let the user delete Artists/Albums/Songs manually from the library. Or the mentioned function "Resync library" only resyncs library element which have no cached songs.

**Comment by sandersantema** [comment]
I've asked about this in the ampache telegram group. To me this function seems quite essential so I think there's a good chance the developers will add it to the Ampache api sometime. In the meantime I thought of a solution, which is quite a hack but I think better than deleting all cached songs or only refreshing uncached songs which to me seems like it would become very confusing and require lots of manual deleting of cached songs. 

If I'm not mistaken the problem here is not syncing the playlists one by one but simply the songs. I think we can assume that it's fine to sync playlists one by one right? Shouldn't be that many so that it can be done one by one, or so I assume. 

So what remains is to check whether a song is deleted. The hacky solution I could think of is to create a smart-playlist which adds all songs in the library to it and when syncing check whether it has the same amount of items as a previously cached list with song id's (or whatever is needed to identify a song) and if that's not the case to check which songs where in the cached list but not in the newly received playlist. But this might still be very slow, I wouldn't know exactly.

**Comment by sandersantema** [comment]
Yes! The developer added the API function: https://github.com/ampache/ampache/commit/29324f6dfd8b198989ab9404b9289e30bd98b86a

**Comment by BLeeEZ** [comment]
Ok, Good to know. This will be an asymmetrical feature (subsonic does not support it). The api calls for deleted objects will be triggered via a Button press in settings.

The implementation will take some time. Every deleted object is a new kind of xml object. Due to this fact I need to write new xml parser.
