### ISSUE TITLE
[Bug]: Songs view only shows songs after search

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#58]
I assume this is a bug, if not I think it would be an improvement. The song view only show a list of songs after a search query has been entered, I think it should show a list of songs before that just as the apple music app does.

**Comment by BLeeEZ** [comment]
This has been „fixed“ in the meantime in this issue https://github.com/BLeeEZ/amperfy/issues/49.

**Comment by sandersantema** [comment]
I see with a nice and friendly info box too, very nice! Please excuse the duplicate issue.
