### ISSUE TITLE
[Feature]: Clickable artist/ song in the now playing view

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#59]
It would be nice feature to allow the user to click on the artist which would then show the artists page and clicking on the song would show the album.

e.g. clicking on Creative Heads in the picture below would show the album/ single containing this song and clicking on Example artist would show the artist view. For a better example of this UI you could take a look at spotify which implements this already.
![image](https://user-images.githubusercontent.com/21057514/122914207-b01add00-d35a-11eb-94bc-6a9f4fc49638.png)

**Comment by BLeeEZ** [comment]
Feature has been implemented with: c4eae17a78db64397f50a3ec63f3230f7448f865

**Comment by sandersantema** [comment]
Again works perfectly :)
