### ISSUE TITLE
[Feature]: Carplay support

### ISSUE THREAD

**Issue by cfredericksen** [BLeeEZ/amperfy#60]
Enable carplay support? 

Found Amperfy recently, and have found its the cleanest and fastest subsonic IOS client out there. Thanks for creating this project!

**Comment by BLeeEZ** [comment]
Thank you very much. I already did some reading about CarPlay. The problem here is that an Apple Developer account is required. Currently I am developing the app and Dirk is publishing it. I am not able to request CarPlay functionality for Amperfy. I will see if we can find a way.

**Comment by cfredericksen** [comment]
> Thank you very much. I already did some reading about CarPlay. The problem here is that an Apple Developer account is required. Currently I am developing the app and Dirk is publishing it. I am not able to request CarPlay functionality for Amperfy. I will see if we can find a way.

@BLeeEZ Carplay is working with Amperfy. You skip forward/back, pause and the album art is displayed.

**Comment by BLeeEZ** [comment]
What you describe is the airplay functionality of iOS 😄 
The "true" CarPlay can offer the user the possibility to search for songs and get for example all artists or albums displayed. This functionality can only be implemented with the above described Apple Developer account.

**Comment by cfredericksen** [comment]
Ha, interesting. It doesn't work for all music clients. Hopefully someone will read this in the future and take advantage of the built-in functionality.

**Comment by BLeeEZ** [comment]
I am happy to tell that CarPlay is now fully functional and can be tested in the current Beta v1.1.0(3).

**Comment by mfat** [comment]
Carplay doesn't show anything except for now playing.
