### ISSUE TITLE
[Feature/ Bug]: Background downloads/ downloads fail when ampache is currently opened app

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#62]
This might be a bug or just something which isn't implemented yet but currently ampache isn't able to download songs while the iPhone is locked or ampache is not the currently opened app. It wouldn't be nice to be able to lock my phone or use other apps while ampache is downloading songs.

**Comment by BLeeEZ** [comment]
I reworked the compled download process with 943dcf26eca6ac6bffc1f594eace2ee2522ca1c6 and fb930e4e7760a198d08a0948bcfeeae2b78f9d1c.
- Downloads are now persistent (Success or failed will be displayed even after app restart)
- Downloads are continued/started in background and while app is suspended
- Failed downloads can be restarted
- Downloads can be canceled
- Completed/Failed downloads can be removed from downloads view

**Comment by sandersantema** [comment]
Great! I'll report back by the time the new version is available in testflight.

**Comment by BLeeEZ** [comment]
Is this still an issue or can it be closed?

**Comment by sandersantema** [comment]
Ah sorry forgot about this, I haven't downloaded stuff in a while and am a bit busy at the moment but I'll try it out again shortly.

**Comment by sandersantema** [comment]
Seems to work fine now!
