### ISSUE TITLE
[Feature]: Display album on the now playing screen

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#63]
There is currently a enough space (or at least that's the case for me and the screen size of my iphone SE 2nd edition) to display the album between the artist and the name of the song. This would allow for a somewhat more intuitive interface for clicking on the album to go to the album too, although if this would be implemented the current behaviour of clicking on a song to go to the album should be preserved since it's the behaviour in apps such as spotify so as to not confuse people familiar with that. But in general I'm not all that sure if the album should be displayed there, I don't see any really important reasons why it shouldn't be but other apps don't do it and it might lead to some issues when an album has a long name.

**Comment by BLeeEZ** [comment]
Is implemented in 85b3e0d292fed179a0de87545f690cb04b4e4517

**Comment by BLeeEZ** [comment]
This feature is now available in the latest beta version 1.1.2 (1): https://github.com/BLeeEZ/amperfy/issues/25. Can you give me some feedback?

**Comment by sandersantema** [comment]
I don't recall this feature request anymore that clearly (and tbh didn't find my own description all too clear :)) but I believe it's about the album name between the artist and song name when the now playing is full screen right?

If so then it's working perfectly! Clickable and all, it even scrolls to the song in the album. I also like how the difference in font sizes indicate what is what, i.e. the album font being smaller than the the fonts of the song and artist. Very nice. 

One thing which I could think of to test is what happens when a song has no album, but it seems my Ampache instance gives every track without the album the "Unknown (Orphaned)" album. I can't exactly figure out if you've dealt with this edge case from [85b3e0d](https://github.com/BLeeEZ/amperfy/commit/85b3e0d292fed179a0de87545f690cb04b4e4517), although again it's working perfectly with my setup!
