### ISSUE TITLE
Change server settings

### ISSUE THREAD

**Issue by ghost** [BLeeEZ/amperfy#66]
Currently it is not possible to update the server information, for example if the server address or the username/password has changed and needs updating. Instead, resetting the entire app data is required and everything must be set up again from scratch.

Is it possible to make the server information editable so that these changes can be made without losing the rest of the data?

**Comment by BLeeEZ** [comment]
Password change is implemented in the current beta: https://testflight.apple.com/join/HCZzB1fU

Username and url change will not be supported. A change of this credentials can lead to library sync issues.
