### ISSUE TITLE
AppStore Version?

### ISSUE THREAD

**Issue by albertkun** [BLeeEZ/amperfy#7]
Thank you for creating this app for ampache!! I'm trying to setup an music streaming service, but my family uses iphones and I do not have a Mac. Is there a way you can put this app on the apple store? Thank you again!

**Comment by dhharris** [comment]
Yes I would love to see an appstore version! I use this app all the time and it would be convenient to be able to get the latest updates without having to rebuild the app.

**Comment by BLeeEZ** [comment]
Hi,
thank you, i appreciate your response.

I wanted to release the app free of charge on the app store.
The apple developer fee to officially release Amperfy on AppStore is 100$/year.
A company tax id is also necessary to get an apple developer account.
This is too much work for me for a free time project.

Kind regards
Max

**Comment by ccp-codex** [comment]
I maintain an apple developer account for other purposes and would be happy to publish this as a free app with your permission. I probably won't have time to go through the build/publish cycle until my vacation rolls around in August. Let me know if this is acceptable to you.

**Comment by BLeeEZ** [comment]
Yes, you have my permission. Thank you for your time. If there’s anything else you need, just let me know.

**Comment by YasserAntonio** [comment]
@ccp-codex Thanks ! I 'm very interested.

**Comment by Dirk23** [comment]
If you want, I can publish it with my Developer Account. I have some time an I can do it now.

**Comment by BLeeEZ** [comment]
@Dirk23 If you still have time and interest I would be glad if you would publish it.

**Comment by Dirk23** [comment]
Hi. No Problem. You Need to do Dome Things. Wen Need Icons and Pictures of the App and a Text describing your App. You can Contact me at dirk@diehildebrands.de (German if you want)

**Comment by Dirk23** [comment]
@BLeeEZ please contact me via E-Mail. I need some informations from you and I don't want to start registering the app, without talking to you

**Comment by octave-syndicate** [comment]
No I haven't started yet. Was on vacation. Super happy if Dirk23 wants to publish it instead.

**Comment by BLeeEZ** [comment]
## Update

With the kind help of @Dirk23 we created a submit request for the official Apple App Store.

Sadly we ran in some issues during review period.
The following app store guideline violation has been stated in the review reply:

>Guideline 5.2.3 - Legal - Intellectual Property
>
>Your app allows users to save or download music, video, or other media content without authorization from the relevant third-party sources.

Due to this violation i don't think that a submit to the official Apple App Store is possible.

**Comment by Dirk23** [comment]
@BLeeEZ i think we Need to explain what this App and Ampache does. There are other Apps like this one available on the Appstore. I think that we have nothing to loose by trying this.

**Comment by BLeeEZ** [comment]
# Official App Store Release

I am proud and glad to announce:
Today Amperfy has been officially released on the Apple App Store.
Click [here](https://apps.apple.com/app/amperfy-music/id1530145038#?platform=iphone) to go directly to the App Store.

I also want to use this chance to say thank you:
Special thanks to @Dirk23 for his support to bring Amperfy in the App Store.
Also thank you to all the contributors, bug reportes and other supporters.

**Comment by sandersantema** [comment]
Is there any chance beta versions could be tested using testflight (https://testflight.apple.com/)?

**Comment by BLeeEZ** [comment]
Yes, we will provide a public link to the TestFlight beta as soon as it is available (The build for version 1.0.4 is currently in review)

**Comment by BLeeEZ** [comment]
Additional information and the link for this and future beta tests can be found here: #25

**Comment by albertkun** [comment]
awesome!! thank you for this everyone here! should i close this issue now @BLeeEZ ?
