### ISSUE TITLE
How to see what's available offline?

### ISSUE THREAD

**Issue by PaulWalkerUK** [BLeeEZ/amperfy#71]
Unless I'm missing something, there doesn't seem to be a way to view just the downloaded content. Is there any way to filter the library lists (Artists, Albums, etc) to only show things that are available offline? Without this, I'm struggling using it offline - I can download content, but when I'm away from home, it's not easy to see what I can play.

I don't know if it could either be an option to filter the exisiting lists, or a separate set of lists under a top-level "Offline" section maybe?

**Comment by BLeeEZ** [comment]
Currently only songs are filterable for being cached.
The filter option "Cached" can also be added to artists and albums to see if one of them has at least one cached song.

**Comment by BLeeEZ** [comment]
With this 291fcbc77b8bbba5bf5aed59ee69ec6333083447 I added a full-blown "Offline Mode". If activated no communication with the server happens. All Library categories are automatically filtered for cached items.

**Comment by PaulWalkerUK** [comment]
Sounds perfect, thanks 👍

**Comment by BLeeEZ** [comment]
Can this issue be closed?
