### ISSUE TITLE
[Feature] Add sort to songs list and display 'recently added'

### ISSUE THREAD

**Issue by cfredericksen** [BLeeEZ/amperfy#73]
Is this possible?

**Comment by sandersantema** [comment]
What kind of sort would you want? By genre for instance? It might be a nice feature to have an option to display the genres in the same way as the song list. 

In regards to recently added, if you're using ampache this can be done server side using a smart-playlist:
![image](https://user-images.githubusercontent.com/21057514/132380820-5e4139e3-775c-4f19-a499-f6a652014f05.png)

**Comment by BLeeEZ** [comment]
@sandersantema  good idea as a quick solution.
@cfredericksen The problem here with 'recently added' is that the server does not provide the date and time when songs have been added (At least not in the API response). With that said Amperfy has no attribute which could be used to sort the songs.

**Comment by cfredericksen** [comment]
Thanks for the quick responses. I am using a Navidrome and figured out a workaround. I run a 'ls -1t > new songs.m3u' (sort the mp3s by creation date) and dump it to inside of the music folder and Navidrome will auto add it as a playlist.

**Comment by BLeeEZ** [comment]
With this commit c84c3c4 RecentlyAdded Albums/Songs can be filtered.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
