### ISSUE TITLE
[Feature]: Read album art from files

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#75]
This would be a bit of a hacky solution but since I'm having problems both with album covers on the ampache server itself and also quite often have errors related to album art on amperfy such as lots of error messages and about 90% of my songs missing album art I'd rather simply have amperfy read album art from the files themselves or at least have an option to do so.

**Comment by BLeeEZ** [comment]
As you already mentioned, I think this request really a bit hacky 😄 
This feature is quite a lot work to manipulate/add the artwork in the database at song fetch.
I prefer to listen to the server response regarding artworks.

**Comment by sandersantema** [comment]
I don't think there would be any need to add anything to the database, in so far I understood it this should do the trick:
https://developer.apple.com/documentation/mediaplayer/mpmediaitem/1621743-artwork

If you're already using that framework I would imagine it'd be easier to implement. To be clear this wouldn't fetch anything from the server but rather look at the album artwork embedded in the files themselves. 

And although it's hacky it would compensate for the somewhat buggy way in which album artwork works in Ampache.

**Comment by BLeeEZ** [comment]
The ID3 artwork will now be used (706e2e41b1c79eb809c57a4a60818c570c62eae1).
It is available after the song is played the first time.

**Comment by sandersantema** [comment]
Amazing! Thanks a lot, album artwork has been finicky since I've started using ampache and therefore in all clients I've tried. This should fix that :)

**Comment by sandersantema** [comment]
I think this feature request can be closed, the functionality has been added and I've opened new issues for other things I've encountered. For reference these are the issues: https://github.com/BLeeEZ/amperfy/issues/87, https://github.com/BLeeEZ/amperfy/issues/88
