### ISSUE TITLE
How to sync library?

### ISSUE THREAD

**Issue by PaulWalkerUK** [BLeeEZ/amperfy#76]
I've added new songs to my Ampache library. How do I get Amperfy to sync so it shows the new artists, albums, etc in the library lists? I've tried pulling down in a few places to try to trigger a refresh, but that doesn't do anything, and I can't find any refresh or sync buttons anywhere - am I missing something?

**Comment by BLeeEZ** [comment]
You can sync the elements via search or add them to a playlist and open it.

**Comment by PaulWalkerUK** [comment]
It looks like for the search to trigger the list to update, I need to search for _that specific artist_. This kinda works if I know which artists have been added, but is a bit inconvenient, especially if other people have added to Ampache. Would I have to do a search for each letter of the alphabet?

I guess creating some kind of playlist that returns all new content might work, but still feels like a slightly awkward workaround.

Maybe I'm still misunderstanding something. It seems to me that there should be a straightforward way to update the lists in Amperfy to match Ampache - the kind of thing that in other apps often has a sync button or a "pull down to refresh"?

**Comment by BLeeEZ** [comment]
You are right. I will take a look at it.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
