### ISSUE TITLE
Supporting Navidrome server with http basic authentication 

### ISSUE THREAD

**Issue by jimmy09140456** [BLeeEZ/amperfy#77]
Hi there, I've installed the Navidrome server with http basic authentication enabled. And I've also exposure the /rest endpoints for mobile clients to connect the API. Both Substreamer and Play:Sub can login and play songs, however, Amperfy can't. I've checked the server access log and see that Amperfy will try to send a get request to the server address, that one user input on the UI. Since I have enabled http basic authentication and Amperfy will fail because of that.

IMMO, Amperfy should test the server address with `/rest` API endpoints, i.e. https://hostname.com/rest, if the user input https://hostname.com/.

**Comment by BLeeEZ** [comment]
Hi, the first step after pressing login is to check if the server is reachable.
Can you provide me the Amperfy error message you get after pressing login?

**Comment by jimmy09140456** [comment]
Yes, you are right. That's the case.

**Comment by jimmy09140456** [comment]
Yes, I can connect to my server now. However, I have another question about that commit. If the server responses 404 or 504, Amperfy will show invalid credential which is confusing. How about only ignore 401 status code?

**Comment by jimmy09140456** [comment]
It's pretty nice! Thank you!
