### ISSUE TITLE
Feature request: scrobbling support

### ISSUE THREAD

**Issue by icyphox** [BLeeEZ/amperfy#79]
Hey, it would be great if you could add support for scrobbling to the server. I think this is supported by the `/scrobble.view` endpoint in the Subsonic API.

**Comment by BLeeEZ** [comment]
Hi, this looks easy to implement. This will be done for the next release.

**Comment by icyphox** [comment]
That would be amazing — thank you!

**Comment by BLeeEZ** [comment]
Scrobble is now supported with this commit d3211c9de6495e5b37ae9d9cb5a78f01dccbdc41.

**Comment by icyphox** [comment]
That was quick! Thank you. :) I'll go ahead and close this now.
