### ISSUE TITLE
[Feature]:  Automatic context switching of the non user queue 

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#85]
_continuation of: https://github.com/BLeeEZ/amperfy/issues/34#issuecomment-1004225020_

First of all a few definitions (because I noticed I use a lot of words of which the meaning isn't clear):

- Non user queue: the queue which isn't queued by the user but can be set by the user using the `Play all` button.
- Context: the context where from a song is playing which can be an artist, album, the `Songs` tab in the `Library` screen, genre, directory and playlist. 

The non user queue context is changed whenever a user manually taps on one of the possible contexts enumerated above. Automatically switching the context would replace the `Play all` button and make the context switch implicit. As far as I can think of this reduces the amount of clicks needed to get the queue like you want it quite a lot and works really well together with a user queue since the user queue never changes context (it doesn't have one either). It would furthermore then be possible to replace the `Play all` button with a shuffle button (the functionality of the play all button is replaced by simply clicking the first song in a context). This further reducing the amount of taps needed to shuffle which currently takes two taps. Two taps isn't that much but for some users like me who mostly shuffle certain playlists these two taps add up, with a shuffle button it would only take one.

Here's an example use case to show how automatic context switching reduces the number of taps needed. If a user wants to play all songs in a playlist which come after certain song in a playlist what you'd have to do at the moment is add the whole playlist to the queue, open the queue, scroll down to the song (which can take quite some time if you've got a big playlist) and tap on the song. If I counted correctly this takes 4 taps excluding the scrolling needed to find the appropriate song in the queue.

If the context of the non user queue changed automatically you'd be done by clicking on the song in the playlist, thus only requiring one tap.

**Comment by sandersantema** [comment]
> The complete context switch/ "play all" behavior is a lot more effort that I will not implement till the next release.

Understandable, might it be an idea to replace the `Add to play next` button with a shuffle button after everything is queueable? Given that that would somewhat replicate this function.

> I am also not quite convinced about this context mechanism.

Could you maybe explain why? I really think it is quite an ergonomic and user friendly mechanism, so I can't really think of any downsides, I'm interested to hear (and possibly discuss about) what you think might be a downside.

**Comment by BLeeEZ** [comment]
I think there are to approaches: 
1. the player has one playlist or queue 
2. the player has an context

For me personal preferences if I click on song in album or artist, I expect it to be added to the player at the end or after the currently playing song. If I want to play only one album to be played I can choose "play all" -> replace the player queue and fill with the album songs. Or I append It to the player ("add to play next").

The context is an other approach. This concept is better if you always want to play a specific order of songs in an album/playlist/genre. This fastens up the speed as you already described.

I personally simply add songs I want to hear to the player and have shuffle always on. sometimes I save the player playlist to have it persistent (if I click wrongly and the player playlist gets wiped) but my player queue is always quite large.

**Comment by sandersantema** [comment]
Again a few definitions to make it easier to talk about this:
1. Swipe right (i.e. from left to right): the action where you swipe left on a queueable element and add it to the end of the user-queue
2. Swipe far right: swipe even further right to add a queueable element to the end of the user-queue but shuffled (you know one of those two staged swiping things which I mostly know from email apps)
3. Swipe left (i.e. from right to left): the action where you swipe left on a queueable element and add it to the start of the user-queue, this would be a to be implemented function. Of course a different gesture could be chosen but let's call it a swipe left for now.
4. Swipe far left: swipe even further left to add a queueable element to the start of the user-queue but shuffled

> For me personal preferences if I click on song in album or artist, I expect it to be added to the player at the end or after the currently playing song

Isn't this use-case covered by the ability to swipe right? This doesn't replace the user queue but that function could be replicated with a swipe left. The swipe far left/right would even add more functionality be allowing you to instantly shuffle these queueable elements. 

> If I want to play only one album to be played I can choose "play all" -> replace the player queue and fill with the album songs. 

This use-case could be covered by the swipe right, although it would obviously keep on playing if the user would have either a context selected or something in their user-queue but either clearing the queue manually (and possibly adding the capability to clear the context of the non-user queue) or simply pressing pause would solve this and are things you wouldn't need to do very often. If you're use case is falling asleep to an album or something similar a "Stop Playing After n minutes" option might be nice, it adds nicely to the podcast functionality of Amperfy too.

> Or I append It to the player ("add to play next").

This is covered by a swipe right too am I right?

> The context is an other approach. This concept is better if you always want to play a specific order of songs in an album/playlist/genre. This fastens up the speed as you already described.

I don't think that's the only use-case. I personally shuffle almost exclusively mostly playlist which are automatically generated and contain the latest n number of songs I've add to my library. Having the context change automatically is still very handy in this case, this reduces the amount of taps needed to start playing a playing namely only tapping on a song in the playlist (assuming shuffle is still turned on and doesn't need to be pressed manually). 

Like you said there seem to be two approaches:

> 1. the player has one playlist or queue
> 2. the player has an context

I think Amperfy currently has a mix of these two but I think that if you'd choose approach two together with the swipe (far) left/right functions most of the use-cases of approach 1. could still be covered two all the while providing a more ergonomic queueing experience.

**Comment by BLeeEZ** [comment]
I see your point. Under the assumption of the four different swipes all points would be met.
I am not sure if the app is then still user friendly with so many swipes (But fast for experienced users).
Either four perfect icons are needed or some kind of tutorial popup at the start to describe all this behavior.
What could also be confusing: Usually swipe to the left is the movement to delete elements, like in the PopupPlayer.

**Comment by BLeeEZ** [comment]
After thinking all through again. Not all points could be met.
For example. I hear a lot of podcasts. When a new podcast episode is available I add It to the player and simple click on it to add it to the player. If I want to switch between episodes I simple click the other one. 
Via the user queue the previous podcast episode would be remove and I need to search it again in the podcast view.
I think about adding a new swipe. The new swipe would add the element to the "normal" queue as the next element (or a third swipe to add it to the bottom). 
But I am still not sold to the context concept. I think I am still used to the old one player queue style. But it is definitely not off the table.

**Comment by sandersantema** [comment]
>  Via the user queue the previous podcast episode would be remove and I need to search it again in the podcast view.

If I understand you correctly what you describe is you're playing podcast `x`, and want to add another podcast `y` to your queue after which you want to play podcast `y` and potentially return to podcast `x` again after a while. 

But what I don't understand how the queuing mechanism relates to this, isn't it possible already anyways to go back to the previous thing you were listening by using the `Previous` list in the queue menu?

**Comment by sandersantema** [comment]
Now that I'm thinking about it, there's obviously the possibility of adding a setting to toggle automatic context switching. The only thing it would change is whether clicking on a song to play it changes the context of the non-user queue as well. Since both mechanisms have their merits I think this might be a nice solution.

The swipes I mentioned above might be a nice addition to the user-queuing mechanism irregardless of the automatic context switching, I'll open a new issue for it since it's not really related to this one.

**Comment by bbsixzz** [comment]
Automatic content switching and swipes is basically how the default Music app works.

**Comment by BLeeEZ** [comment]
Did you get time to test this feature in beta v1.1.0?
I am interested to hear if there are any bugs or adjustments needed for this feature.

**Comment by bbsixzz** [comment]
This works I think but because of https://github.com/BLeeEZ/amperfy/issues/110 (race conditions) I haven't been able to use the app much.

The duplicates are really annoying so I'm waiting for the next TestFlight with fixes to test again.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
