### ISSUE TITLE
Feature request: Be able to rate songs 1-5 stars

### ISSUE THREAD

**Issue by mdeeter** [BLeeEZ/amperfy#86]
Just wanted to post a feature request.  

I'd love the ability to rate songs (perhaps a display of stars at the bottom of the now playing screen)

**Comment by BLeeEZ** [comment]
I am currently not sure where to put the rating system on screen.
5 Starts take a lot of space on the player. Maybe an addition dialog where the rating can take place.
Nevertheless this feature is quite big to implement, so I am not sure when it will be realized.

**Comment by mdeeter** [comment]
I would invision the rating stars that appear at the bottom of the now playing screen....

![image](https://user-images.githubusercontent.com/136902/148229415-e71209ed-2712-4395-ae55-80ee14099da8.png)

I understand that it's not likely a small task... but still thought it was worth seeing if it's possible to add at some point.

**Comment by BLeeEZ** [comment]
This looks like a very good spot.
I am always happy about new feature request/bug reports to further improve the App.

**Comment by mdeeter** [comment]
to further support the value of the ratings on the player... here's my use case:

I use smart playlists to filter out songs I don't want to hear again. I create a smart playlist that only plays songs that are 0 stars (unrated). While playing the playlist, I rate the song. Then I have another smart playlist that only plays songs that are 3-5 stars. So if I want to listen to songs that I know I like, I'll play the good stuff... but while I'm working, I can listen to unrated songs to curate my library over time.

Even if the feature never gets made, I really appreciate your responses to the request.

**Comment by BLeeEZ** [comment]
This feature can now be tested in the newest beta. All infos can be found here: https://github.com/BLeeEZ/amperfy/issues/25
