### ISSUE TITLE
[Feature]: Setting to switch between fetching album art from ID3 tags or server

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#87]
At the moment it seems both methods are used, I think it is better to use either one exclusively. It might even be an option to remove the functionality to fetch art from the server if it reduces the development work but that obviously depends on whether the function is used and if you want to remove it. 

In any case a setting to choose between either fetching album art from the server or ID3 would be nice.

**Comment by BLeeEZ** [comment]
For me both methods work great together. I don't see the necessity for such a switch.

**Comment by sandersantema** [comment]
Well consider two cases: 

1. The album art embedded in the files of someone's library is wrong, but they've got all the album art correct in Ampache
2. The album art associated with the files by Ampache is wrong, but they've got all the correct album art embedded in the files.

People who belong to use-case 1. would currently be forced to wipe all the album art of their files if they wanted to have the album art from Ampache. People who belong to use-case 2. (that's me!) currently have most of their use-case covered but tracks which don't have any album art can still get wrong album art assigned by Ampache, even though in my case and possibly others I'm not interested at all in Ampache album art and only in the album art contained in the files.

But I do think there's also a third and fourth use case:

3. Not all files have album-art embedded in their tags but this is supplemented by album art from Ampache
4. Not all files have album-art from the Ampache server but this is supplemented by embedded album-art

Currently only use-case 4. is covered, which I believe is yours. But I think it would be a nice addition to allow for choosing whether amperfy will fetch art from the embedded album art and the Ampache server (on-off toggle's) and whether it will prefer the embedded album art or the album art from the Ampache server (a switch).

**Comment by BLeeEZ** [comment]
The feature is implemented in this commit c732653229bf45b35383694e2c7e619d818adbb6.
The default values are the active ones in the screenshots:

![Simulator Screen Shot - iPhone 11 Pro - 2022-03-12 at 20 15 57](https://user-images.githubusercontent.com/17556018/158031905-173f4d43-cdcd-4422-81de-3882488bde71.png)
![Simulator Screen Shot - iPhone 11 Pro - 2022-03-12 at 20 16 03](https://user-images.githubusercontent.com/17556018/158031906-4ebaab0c-a5f9-4aef-9795-1bf3876d8ef6.png)
![Simulator Screen Shot - iPhone 11 Pro - 2022-03-12 at 20 16 08](https://user-images.githubusercontent.com/17556018/158031909-c304e103-1681-48be-945f-128fc708dfb0.png)

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
