### ISSUE TITLE
[Bug]: ID3 album art isn't fetched unless song is played.

### ISSUE THREAD

**Issue by sandersantema** [BLeeEZ/amperfy#88]
The album art from the ID3 tag isn't fetched unless the song is played after which I'm not sure whether it is actually set, or in any case the small album art in the playlists doesn't seem to change. 

A nice way to solve this might be to hook the ID3 art fetching function into the server art fetching function so that when a song is downloaded from the server if a user sets the setting (as described in https://github.com/BLeeEZ/amperfy/issues/87#issue-1093793353) to only fetch ID3 art the art will be set via the same mechanism as server art is set. Assuming this is possible since I haven't looked at the code :)

**Comment by BLeeEZ** [comment]
This currently intended. The only way I found to extract the album art from a file is to load it into the AVPlayer object. So for the first shot I use the existing player instance and extract the artwork when the file is completely loaded -> I already implemented the necessary callbacks for it.
To extract the files after download I need to create a player object for each download and manage its callbacks. This was too much effort at that time. 
I will take a look at it.

**Comment by sandersantema** [comment]
Ah I see, the apparently wonderful world of Apple's API's ;) If takes to much work a temporary solution might be to allow the user to this programmatically i.e. push a button in the settings called something like `Update Album Art From Tags` (or `Update Album Art from Tags`, hard one :thinking:) which would do all of this without having to manually play any songs, it would be even better if it did this in the background. Since it's a user triggered action it should be less important that it takes more memory etc.

**Comment by BLeeEZ** [comment]
With 3fb7eef3c99f468510ba840f84f05205d70314a0 file embedded artworks are now extracted directly after download.

**Comment by sandersantema** [comment]
Absolutely wonderful!

As an aside from this commit/ issue, thank you for the wonderful commits lately! So much paper-cuts resolved. I'm still looking into swift, although my progress has been rather slow since Amperfy is the only thing which I'd use it for but I hope to contribute some code soon.

**Comment by BLeeEZ** [comment]
I assume this can be closed. If not feel free to reopen it again.
