### ISSUE TITLE
[BUG] Scrolling stutter

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#91]
https://user-images.githubusercontent.com/47334163/150636101-1bb5ac08-9c9a-48bb-97e1-a645e654f75e.mov

iPhone SE 2016 running iOS 15.2.1 (not low powered mode).

The scrolling isn't smooth, there is a random stutter/fps drop.

This happens on amperfy 1.0.7 and 1.0.8 (4) beta.

**Comment by BLeeEZ** [comment]
The stutter results from artwork update.
The update frequency of already fetched artworks is now only performed 5% of the time (commit 514ec534331d0ad92e3f1cd80b1281a28be6d8a5).
Artworks that not have been fetched will still be fetched.
The stutter should now only occur if not all artworks are fetched and the user is scrolling very fast.

**Comment by BLeeEZ** [comment]
Is the stutter stille occurring with v1.08(5)?

PS: I further improved the artwork update in upcoming v1.1.0 to always keep all artworks up to date.

**Comment by bbsixzz** [comment]
The bug is fixed, thanks!

**Comment by bbsixzz** [comment]
Looks like a regression, the stutter is back; it feels choppy even with all the artwork cached.

https://user-images.githubusercontent.com/47334163/167980584-e7472edf-d5fe-48f1-be12-dafd241cdda3.MOV

**Comment by BLeeEZ** [comment]
Can you tell me your `artwork download` settings under Settings-> Artwork-> Artwork Download Settings? The stutter should not occur via `Download only once`. Nevertheless the stutter should not occur with `per session` too. I will reduce the fetch rate to 5% as it was previously.

**Comment by bbsixzz** [comment]
I have it set to Download once per session.

I tried Download only once but it didn't make a difference.
