### ISSUE TITLE
[BUG] Playback broken 1.0.8 (4)

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#92]
https://user-images.githubusercontent.com/47334163/150636286-e53299b8-1284-4d4f-a7d8-3aaf2ac65392.mov

iPhone SE 2016 running iOS 15.2.1

In the video I select play all on an album and switch to another album and select play all.

Player shows the new album and track but the old track and album is still playing.

P.S.

Album list view shows After The Rain… Erik Satie; Pascal Rogé as artist. 

When selected it shows Unknown Artist.

**Comment by BLeeEZ** [comment]
Thank you. I can reproduce the issue on my phone (current public beta) too. I hope I already fixed this issue with this commit c03c8e3a8b30d042c97776a78b21295406d790dc. I will test if the bug is still occurring with the latest master.

**Comment by BLeeEZ** [comment]
Bug is fixed via this commit 875dffaa285e84207992505e6bf25eaed702baee.

**Comment by bbsixzz** [comment]
Very nice, when is the next testflight?

**Comment by BLeeEZ** [comment]
I assume in the next two weeks.

**Comment by BLeeEZ** [comment]
Is this bug fixed with v1.0.8(5)?
