### ISSUE TITLE
[BUG] App crash artist view add track to queue with swipe

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#93]
https://user-images.githubusercontent.com/47334163/150679009-6c170786-28b9-42f6-84f5-8a31d3ce1a41.MP4

iPhone SE 2016 running iOS 15.2.1, Amperfy 1.0.8 (4)

Any track added from any artist view will crash the app.

**Comment by BLeeEZ** [comment]
I can reproduce this bug on my device too. I will take a look at it.

**Comment by BLeeEZ** [comment]
Bug is fixed via this commit a165fccd6671052adcd1a3c31707733260d4e59f.

**Comment by BLeeEZ** [comment]
Is this bug fixed with v1.0.8(5)?
