### ISSUE TITLE
[BUG] Show recently added - wrong sort order

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#94]
iPhone SE 2016 running iOS 15.2.1, Amperfy 1.0.8 (4)

The sort order does not correspond to the (correct) recently added sort order in Navidrome:

<img width="1029" alt="Screenshot 2022-01-25 at 01 27 06" src="https://user-images.githubusercontent.com/47334163/150888176-1b4763c7-f1dc-42fb-80bf-10cf3903a822.png">

![IMG_603243716EC1-1](https://user-images.githubusercontent.com/47334163/150888159-46d74ef4-a5af-4b05-b902-7d7ebb0e0b84.jpeg)

**Comment by bbsixzz** [comment]
Addendum iSub has the correct order:

![IMG_12C09649C182-1](https://user-images.githubusercontent.com/47334163/151204721-cea6629e-ee35-41bf-b461-293bfc3825aa.jpeg)

**Comment by sandersantema** [comment]
I might be misunderstood but I don't believe Amperfy has a recently added section, as you can see in your example albums are sorted alphabetically. There's not that much need for it either way, assuming you're running an Ampache server that is, where you can simply create a smart playlist with recently added songs. 
![image](https://user-images.githubusercontent.com/21057514/153211089-b11973a0-a213-46e0-a210-86c2d47956d3.png)

P.s. some nice music you've got there :) I particularly like Vril and Mumdance :)

**Comment by sandersantema** [comment]
I actually just saw the recently added menu item in the screenshots in the readme, which I suppose is the feature you're referring to. Weirdly enough I haven't got that menu :thinking:

**Comment by bbsixzz** [comment]
Nice, we have similar taste in music :]

I use Navidrome as my server, maybe that's why I have the menu?

![713E8B6C-9D33-499D-9199-BE824581A2AD](https://user-images.githubusercontent.com/47334163/153227417-d7329104-cd12-4047-976e-aa9471915fcf.jpeg)

**Comment by bbsixzz** [comment]
1.1.0 (1) still wrong sort order just in case you changed anything and need feedback.

**Comment by bbsixzz** [comment]
Hello, are you working on a solution to this? 

I still open iSub to look for the right order in order to play my albums in Amperfy.

**Comment by BLeeEZ** [comment]
I am currently refactoring the complete api handling. After that I will take care of this. In the meantime I did a lot of changes to the table view display system which should now support this feature better. Expect this bug be fixed in the upcoming release.

**Comment by BLeeEZ** [comment]
Sorting is now fixed in d09da0db50dbabcba65f151d33f776c704d7d822.

**Comment by BLeeEZ** [comment]
This should be fixed in the latest beta version 1.1.2 (1): https://github.com/BLeeEZ/amperfy/issues/25. Can you give me some feedback?

**Comment by bbsixzz** [comment]
This is great now, thank you!

**Comment by bbsixzz** [comment]
This issue has regressed with the new sort options in Amperfy 1.1.2 (2).

It is no longer possible to sort by time added in `Recent Albums`, `Recent Songs` is unaffected.

![IMG_AA4669ACF292-1](https://user-images.githubusercontent.com/47334163/206565971-d8a93abc-b087-47c1-add6-2a6f61377d81.jpeg)

![IMG_D348D521B32D-1](https://user-images.githubusercontent.com/47334163/206566013-bdeb6fce-2af5-4371-88b5-2ba48791d44e.jpeg)

**Comment by BLeeEZ** [comment]
You are right. This error came in with the revert to tableview. I will remove the sort option in „recent albums“ and default it to time added.

**Comment by BLeeEZ** [comment]
Fixed in 99956c84adb5bb4b581e91ab15ab93a2fe0f6c64
