### ISSUE TITLE
[BUG] AirPlay turns on TV when using Apple TV with home theater audio

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#97]
iPhone SE 2016 iOS 15.3, Amperfy 1.0.8 (4)
Apple TV 4K (second generation) tvOS 15.3
HomePod (not mini) tvOS (derivative) 15.3

AirPlay turns on the TV when streaming to Apple TV with home theater audio setup ([HomePod stereo pair](https://support.apple.com/en-au/HT207705)).

TV shows a black screen with playback controls and no artwork, clicking back or sleeping Apple TV stops the music.

This is not the correct behavior, streaming from the Music app or macOS doesn't wake the TV.

**Comment by bbsixzz** [comment]
AirPlay with regular Music app has album art and no controls, does not turn on TV display.
![IMG_5545](https://user-images.githubusercontent.com/47334163/152432859-1987e2a7-5d38-48c5-ba03-64b43ee7ac40.jpg)

Airplay with Amperfy turns on TV display and shows this.
![IMG_5548](https://user-images.githubusercontent.com/47334163/152432888-2d163222-2ff5-4540-b090-3ccbd88573df.jpg)

**Comment by BLeeEZ** [comment]
Very interesting. It seems Amperfy uses the video AirPlay api. I don’t have an Apple TV to reproduce this behavior but I will definitely take a look at it.

**Comment by bbsixzz** [comment]
Resolving this and gapless playback https://github.com/BLeeEZ/amperfy/issues/96 would be very welcomed for 1.1.0.

Let me know if you need me to test something.

**Comment by BLeeEZ** [comment]
I was able to reproduce the issue and fixed it with this commit e6f6bdeb4a2f6ac297c5c144a25dacf3a8e53a79.

**Comment by bbsixzz** [comment]
Can you please push a new beta on TestFlight so I can test this? 

It would be much appreciated for my setup.

**Comment by bbsixzz** [comment]
This now works correctly in Amperfy 1.1.0 (1).

Superb!
